### PR TITLE
Fix chip sw sysrst ctrl ec rst l

### LINKED ISSUE #15679: [test-triage] sysrst_ctrl_ec_rst_l_test assertion timeout
### Hierarchy of regression failure

Chip Level

### Failure Description

 UVM_ERROR @ 14969.358000 us: (sw_logger_if.sv:522) [sysrst_ctrl_ec_rst_l_test_prog_sim_dv(w/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c:148)] CHECK-fail: Timed out after 2500 usec (250000 CPU cycles) waiting for current_phase != kTestPhase
  UVM_INFO @ 14969.358000 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---

### Steps to Reproduce

- GH revision: [9c0b24ddb](https://github.com/lowrisc/opentitan/tree/9c0b24ddbeb5616bd8db661ec1395f2d4f326bc4)
- util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_sysrst_ctrl_ec_rst_l --build-seed 2483310614 

### Tests with similar or related failures

- [ ] sysrst_ctrl_ec_rst_l_test
- [ ] chip_sw_sysrst_ctrl_ec_rst_l

> estimate 16

### PR DESCRIPTION
**Pull request by engdoreis**
Fix #15679

### CODE REVIEW

File: sw/device/lib/testing/flash_ctrl_testutils.h [hunk 1]
```diff
@@ -274,10 +274,33 @@ void flash_ctrl_testutils_set_counter(dif_flash_ctrl_state_t *flash_state,
...
+ * Init the backdoor API, it should be called before
+ * `flash_ctrl_testutils_backdoor_wait_update`.
+ *
+ * @param flash_state A flash_ctrl handle.
+ */
+void flash_ctrl_testutils_backdoor_init(dif_flash_ctrl_state_t *flash_state);
+
+/**
+ * This is a backdoor API to be used with dvsim testbench.
+ * Backdoors variables seating on flash may not be updated when read by software
```
Comment (GregAC) [inline sw/device/lib/testing/flash_ctrl_testutils.h:293]: Perhaps 'Backdoor variables present in flash'?

**Review by GregAC — APPROVED** [review]

File: sw/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c [hunk 2]
```diff
@@ -140,12 +142,12 @@ static void check_combo_reset(void) {
 // indicate that the testbench is ready to proceed with the
 // next phase of the test.
```
Comment (ballifatih) [inline sw/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c:143]: small nit: since we are already changing `wait_next_test_phase`, we might as well update it as the function description as /* */ comments, instead of inline comment.

**Review by ballifatih — COMMENTED** [review]
Thanks for the PR @engdoreis! I just rebased my sysrst_ctrl test on it, and it passes. LGTM, but I better let others approve.

File: sw/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c (hunk 2 above)
Comment (ballifatih) [inline sw/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c:143]: nit: Since we are updating `wait_next_test_phase`, maybe we can also replace inline comments for consistency
```
/**
 * Waits for the kTestPhase variable to be changed by a backdoor overwrite
 * from the testbench in chip_sw_sysrst_ctrl_ec_rst_l_vseq.sv. This will
 * indicate that the testbench is ready to proceed with the
 * next phase of the test.
 */
```

File: sw/device/lib/testing/flash_ctrl_testutils.h (hunk 1 above)
Comment (engdoreis) [reply sw/device/lib/testing/flash_ctrl_testutils.h:293]: Fixed

File: sw/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c (hunk 2 above)
Comment (engdoreis) [reply sw/device/tests/sim_dv/sysrst_ctrl_ec_rst_l_test.c:143]: Done

**Comment by weicaiyang** [comment]
I didn't find we move the variable kTestPhase to the volatile scratch area. @ballifatih mentioned it can't be a const since we program it to clear the flash cache. Did I miss something?

**Comment by engdoreis** [comment]
> I didn't find we move the variable kTestPhase to the volatile scratch area. @ballifatih mentioned it can't be a const since we program it to clear the flash cache. Did I miss something?

This PR is implementing this suggestion [here](https://github.com/lowRISC/opentitan/issues/15679#issuecomment-1292390997).

**Comment by weicaiyang** [comment]
> > I didn't find we move the variable kTestPhase to the volatile scratch area. @ballifatih mentioned it can't be a const since we program it to clear the flash cache. Did I miss something?
> 
> This PR is implementing this suggestion [here](https://github.com/lowRISC/opentitan/issues/15679#issuecomment-1292390997).

Can this test pass? @ballifatih mentioned there could be an issue [here](https://github.com/lowRISC/opentitan/issues/15679#issuecomment-1295026325)

**Comment by ballifatih** [comment]
I might have cause some confusion with [my comment](https://github.com/lowRISC/opentitan/issues/15679#issuecomment-1295026325), where I was referring to what I tried locally as a straighforward solution and why it failed.

I am not very familiar with flash_ctrl, but this fix seems to go around my compilation issue, and my test works with this fix. Just wanted to clarify that we can consider [my previous](https://github.com/lowRISC/opentitan/issues/15679#issuecomment-1295026325) comment as obsolete.

**Review by ballifatih — APPROVED** [review]

**Review by weicaiyang — APPROVED** [review]
LGTM

**Comment by weicaiyang** [comment]
> @weicaiyang I might have cause some confusion with [my comment](https://github.com/lowRISC/opentitan/issues/15679#issuecomment-1295026325), where I was referring to what I tried locally as a straighforward solution and why it failed.
> 
> I am not very familiar with flash_ctrl, but this fix seems to go around my compilation issue, and my test works with this fix. Just wanted to clarify that we can consider [my previous](https://github.com/lowRISC/opentitan/issues/15679#issuecomment-1295026325) comment as obsolete.

sounds good, thanks for the clarification.
