### PR TITLE
[chip dv] Quiesce AON timer completely in chip simulations (only pwrmgr_smoketest in this PR)

### LINKED ISSUE #14581: [test, dv] `chip_sw_pwrmgr_smoketest` fails in DV
`chip_sw_pwrmgr_smoketest` fails in DV after the changes in #14243 with the following error:

```
* `UVM_ERROR @ * us: (prim_reg_cdc_arb.sv:241) [ASSERT FAILED] ReqTimeout_A` has 1 failures:
    * Test chip_sw_pwrmgr_smoketest has 1 failures.
        * 0.chip_sw_pwrmgr_smoketest.1\
          Line 297, in log /azp/agent/_work/1/s/scratch/HEAD/chip_earlgrey_asic-sim-vcs/0.chip_sw_pwrmgr_smoketest/latest/run.log

                UVM_ERROR @ 5563.306912 us: (prim_reg_cdc_arb.sv:241) [ASSERT FAILED] ReqTimeout_A
                UVM_INFO @ 5563.306912 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
```

[log](https://dev.azure.com/lowrisc/opentitan-private/_build/results?buildId=91730&view=logs&jobId=a108fe5f-1aa1-5d88-0e90-2681f9ae22bc&j=a108fe5f-1aa1-5d88-0e90-2681f9ae22bc&t=f333052b-f515-5055-643a-c60ecd916b18)

cc @dmcardle @timothytrippel

### PR DESCRIPTION
**Pull request by sriyerg**
Fixes #14581. 
See relevant issues #14585, #14599.

The first commit adds 2 methods to AON timer DIFs, to read out the current status of the timers respectively. The read helps ensure the previous write completes (the write needs to synchronize to the slow AON clock domain which takes a long time). 

The second commit adds a method to AON timer testutil to shutdown the peripheral. 

Finally, the third commit invokes the testutil to shut down the AON timer before exiting the simulation.

### CODE REVIEW

File: sw/device/lib/testing/aon_timer_testutils.c [hunk 1]
```diff
@@ -67,3 +68,17 @@ void aon_timer_testutils_watchdog_config(const dif_aon_timer_t *aon_timer,
...
 }
+
+void aon_timer_testutils_shutdown(const dif_aon_timer_t *aon_timer) {
+  CHECK_DIF_OK(dif_aon_timer_wakeup_stop(aon_timer));
+  CHECK_DIF_OK(dif_aon_timer_watchdog_stop(aon_timer));
+  CHECK_DIF_OK(dif_aon_timer_clear_wakeup_cause(aon_timer));
+  CHECK_DIF_OK(dif_aon_timer_irq_acknowledge_all(aon_timer));
+  // Read and verify both timers are actually disabled. This ensures the
+  // synchronization from the core clock to the AON clock domain completed.
+  bool enabled;
```
Comment (tjaychen) [inline sw/device/lib/testing/aon_timer_testutils.c:79]: i know there's a `DifToggleEnabled` type, not sure if the software folks have a preference for that here or if `bool` is okay.  I think this is fine.

**Review by tjaychen — APPROVED** [review]
lgtm.

File: sw/device/lib/testing/aon_timer_testutils.c (hunk 1 above)
Comment (sriyerg) [reply sw/device/lib/testing/aon_timer_testutils.c:79]: IMO `bool` is fine for non DIF code.

Comment (tjaychen) [reply sw/device/lib/testing/aon_timer_testutils.c:79]: yeah i think so too.

**Review by alphan — APPROVED** [review]
Thanks @sriyerg !
