### PR TITLE
[sram_ctrl,test] Enable sram_ctrl_execution_test in prod locked state

### LINKED ISSUE #19893: [chip-level,si-val] chip_sw_sram_execution
### Test point name

chip_sw_sram_execution

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

None

### Emulation Targets

- [ ] None
- [ ] CW310
- [ ] Hyperdebug + CW310

### Contact person

@rswarbrick

### Checklist

- [ ] Cut down the existing `sram_ctrl_execution_test.c` to work in silicon: we expect to be in life-cycle state PROD, where SRAM execution is not allowed.
- [ ] Do any host-side component work needed. We *expect* Ibex to die when it tries to execute something it's not allowed to execute. Check that we support testing that on the host side.
- [ ] Update hjson test plan with the test name (so it shows up in the dashboard)
- [ ] Get test running on relevant FPGA or silicon regression

> estimate 4

### PR DESCRIPTION
**Pull request by jwnrt**
This commit handles the case where SRAM execution cannot be enabled (because it's disabled through OTP, for example) by running the negative case again.

Resolves #19893

### CODE REVIEW

File: sw/device/tests/sram_ctrl_execution_test.c [hunk 1]
```diff
@@ -85,8 +85,18 @@ bool test_main(void) {
   // execution is unconditionally enabled for the main SRAM in the RMA life
   // cycle state.
   sram_ret_neg_test();
-  CHECK_DIF_OK(dif_sram_ctrl_exec_set_enabled(&sram_ctrl, kDifToggleEnabled));
-  sram_function_test();
+
+  // Try enable SRAM execution.
```
Comment (rswarbrick) [inline sw/device/tests/sram_ctrl_execution_test.c:89]: Nit: Maybe "Try **to** enable..." ?

**Review by rswarbrick — APPROVED** [review]
Looks sensible to me (modulo silly grammar nit!)

File: sw/device/tests/sram_ctrl_execution_test.c (hunk 1 above)
Comment (jwnrt) [reply sw/device/tests/sram_ctrl_execution_test.c]: Thank you :)

**Comment by jwnrt** [comment]
@rswarbrick By this comment (https://github.com/lowRISC/opentitan/issues/19893#issuecomment-1880176541) did you mean that we could instead check that the config bit changed rather than re-testing the negative case?

**Review by pamaury — APPROVED** [review]
I am not super familiar with the test but the change makes sense.

**Comment by rswarbrick** [comment]
@jwnrt: Yes, that's what I meant. But it looks like testing the negative case is pretty simple, so your proposed code looks even better :-)
