### PR TITLE
[rv_dm, sival] test WARL hartsel and anyhavereset

### LINKED ISSUE #22044: [chip-test] Extend RV_DM FPGA and DV tests
### Test point name

chip_rv_dm_ndm_reset_req

### Host side component

SystemVerilog+Rust

### OpenTitanTool infrastructure implemented

Unknown

### Silicon Validation (SiVal)

Unkown

### Emulation Targets

- [ ] None
- [X] CW310
- [X] Hyperdebug + CW310

### Contact person

@a-will @msfschaffner @andreaskurth

### Checklist

Extend existing DV and FPGA TLTs to cover the changes made in #22038.
The main change that should be tested is whether the NDM reset tracking and dmstatus.allhavereset / dmstatus.anyhavereset status indication works correctly.
Checking the WARL behavior of the hartsel register is good to do, but secondary. 

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

### PR DESCRIPTION
**Pull request by nbdd0121**
Fix #22044

For the WARL `hartsel`:
* The existing code already tests the WARL behaviour, update the testplan to match.
* The hartsel mask retrieval code is moved to a dedicated function for clarity.

For the anyhavereset:
* Replace OpenOCD reset command with explicit manipulation of `ndmreset` in dmcontrol
* Check `anyhavereset` stays low before releasing ndmreset
* Check that it goes have after releasing `ndmreset`
* Note that it's not feasible to observe the period between `ndmreset` release and `anyhavereset` going high, because JTAG is too slow compared to reset.

### CODE REVIEW

**Review by rswarbrick — APPROVED** [review]
This looks good to me. I'll leave it to someone who knows more rust than me to do a proper review before it gets merged.

File: sw/host/tests/chip/rv_dm/src/ndm_reset_req.rs [hunk 1]
```diff
@@ -23,6 +23,9 @@ struct Opts {
     timeout: Duration,
 }
 
+// Needs to match util/openocd/target
+const RISCV_IDCODE: u32 = 0x10001cdf;
```
Comment (pamaury) [inline sw/host/tests/chip/rv_dm/src/ndm_reset_req.rs:27]: I think the ICODE can depend on the part, so on the ES or on real chips it probably won't be this value. Ideally we should make this configurable?

**Review by pamaury — APPROVED** [review]
Looks good to me.

File: sw/host/tests/chip/rv_dm/src/ndm_reset_req.rs (hunk 1 above)
Comment (nbdd0121) [reply sw/host/tests/chip/rv_dm/src/ndm_reset_req.rs:27]: There are a few tests currently with this, I'll make the change in a follow-up PR.
