### PR TITLE
[dv,top-level,tests] Fix plic_all_irqs_test race

### LINKED ISSUE #17147: [dv,top-level,tests] Fix TODO in plic_all_irqs_test
### Description

The plic_all_irqs_test is racey, and has a TODO about it. The race seems to trigger more often when adding CDC instrumentation to the top-level. It is due to a small delay between when an interrupt is triggered via CSR and when the ISR starts executing.

### PR DESCRIPTION
**Pull request by matutem**
Fixes #17147

Signed-off-by: Guillermo Maturana <maturana@google.com>

### CODE REVIEW

**Review by sriyerg — APPROVED** [review]
LGTM, thanks!

File: util/topgen/templates/plic_all_irqs_test.c.tpl [hunk 1]
```diff
@@ -197,10 +198,9 @@ static void peripheral_irqs_trigger(void) {
   ${indent}  LOG_INFO("Triggering ${p.inst_name} IRQ %d.", irq);
   ${indent}  CHECK_DIF_OK(dif_${p.name}_irq_force(&${p.inst_name}, irq, true));
 
-  ${indent}  // TODO: Make race-condition free
-  ${indent}  CHECK(${p.name}_irq_serviced == irq,
-  ${indent}        "Incorrect ${p.inst_name} IRQ serviced: exp = %d, obs = %d", irq,
-  ${indent}        ${p.name}_irq_serviced);
+  ${indent}  // This avoids a race where *irq_serviced is read before
+  ${indent}  // entering the CSR.
+  ${indent}  IBEX_SPIN_FOR(${p.name}_irq_serviced == irq, 1);
```
Comment (msfschaffner) [inline util/topgen/templates/plic_all_irqs_test.c.tpl:203]: do you by chance mean ISR instead of CSR? maybe I misunderstood what CSR means in this context ;)...

**Review by msfschaffner — APPROVED** [review]
One question, otherwise LGTM

File: util/topgen/templates/plic_all_irqs_test.c.tpl (hunk 1 above)
Comment (cindychip) [reply util/topgen/templates/plic_all_irqs_test.c.tpl:203]: I will make another PR to fix that. Good catch MIchael.
