### PR TITLE
[top/dv] Move symbol to non-volatile scratch area

### LINKED ISSUE #15356: [test-triage] chip_sw_inject_scramble_seed
### Hierarchy of regression failure

Chip Level

### Failure Description

```
UVM_ERROR @ * us: (sw_logger_if.sv:522) [inject_scramble_seed_prog_sim_dv(sw/device/tests/sim_dv/inject_scramble_seed.c:80)] CHECK-fail: flash_ctrl_testutils_read(flash_ctrl, addr, *, read_data, kDifFlashCtrlPartitionTypeInfo, ARRAYSIZE(read_data), *) has 3 failures:

Test chip_sw_inject_scramble_seed has 3 failures.
0.chip_sw_inject_scramble_seed.1196693424
Line 493, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_inject_scramble_seed/latest/run.log

  UVM_ERROR @ 52768.713512 us: (sw_logger_if.sv:522) [inject_scramble_seed_prog_sim_dv(sw/device/tests/sim_dv/inject_scramble_seed.c:80)] CHECK-fail: flash_ctrl_testutils_read(flash_ctrl, addr, 0, read_data, kDifFlashCtrlPartitionTypeInfo, ARRAYSIZE(read_data), 0)
  UVM_INFO @ 52768.713512 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
  
  
1.chip_sw_inject_scramble_seed.3237918341
Line 492, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.chip_sw_inject_scramble_seed/latest/run.log

  UVM_ERROR @ 53426.193225 us: (sw_logger_if.sv:522) [inject_scramble_seed_prog_sim_dv(sw/device/tests/sim_dv/inject_scramble_seed.c:80)] CHECK-fail: flash_ctrl_testutils_read(flash_ctrl, addr, 0, read_data, kDifFlashCtrlPartitionTypeInfo, ARRAYSIZE(read_data), 0)
  UVM_INFO @ 53426.193225 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
  
```

### Steps to Reproduce

- Commit hash where failure was observed: 144e5112d
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_inject_scramble_seed --fixed-seed 1196693424 --build-seed 1505772856 --waves -v h

### Tests with similar or related failures

_No response_

### PR DESCRIPTION
**Pull request by tjaychen**
Move the iso partition expected data to a non-scrambled area.
fixes #15356 
Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

File: sw/device/tests/sim_dv/inject_scramble_seed.c [hunk 1]
```diff
@@ -40,7 +40,7 @@ OTTF_DEFINE_TEST_CONFIG();
 // test environment.  The data has to be backdoor loaded because the
 // life cycle state used in this test does not permit the isolated
 // partition to be written.
-static volatile const uint32_t kIsoPartExpData[16];
+OT_SECTION(".non_volatile_scratch") uint32_t kIsoPartExpData[16];
```
Comment (jdonjdon) [inline sw/device/tests/sim_dv/inject_scramble_seed.c:43]: Can you explain why 'static volatile const' didn't work?
I have non-flash test using 'static volatile const' wondering if 
I have to make the same update.

**Review by jdonjdon — APPROVED** [review]

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 1 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c:43]: ah this is because the test itself is kind of stupid. 
`kIsoPartExpData` is backdoor loaded by the test sequence in "unscrambled" form. 

So that means, wherever that data is, i need to set scramble_en to 0 in order to properly read that back.
The problem is, all other data loaded by the test itself is scrambled. So when I set scramble_en to 0, all the data except for `kIsoPartExpData` read back incorrectly. This caused the register program interface to program incorrect values and eventually break the test.

**Review by msfschaffner — APPROVED** [review]

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 1 above)
Comment (sriyerg) [reply sw/device/tests/sim_dv/inject_scramble_seed.c:43]: So, the alternative would be to backdoor write the unscrambled data in Iso partition of the flash, and the corresponding scrambled data in the `.data` section for the SW to be able to read back?
