### PR TITLE
Fix usb suspend reset

### LINKED ISSUE #28827: [chip-test] USB tests failing
### Test point name

//sw/device/tests:usbdev_aon_wake_disconnect_test_silicon_owner_gb_rom_ext //sw/device/tests:usbdev_deep_disconnect_test_silicon_owner_gb_rom_ext //sw/device/tests:usbdev_suspend_full_test_silicon_owner_gb_rom_ext //sw/device/tests:usbdev_suspend_resume_test_silicon_owner_gb_rom_ext

### Host side component

Rust

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [x] Hyperdebug + CW310

### Contact person

@pamaury 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [x] For SiVal test cases, test is running relevant FPGA or silicon regression

Several USB tests are failing in SiVal due to some differences between the FPGA and silicon testing environment. Furthermore several USB tests are flaky on the FPGA anyway.

### PR DESCRIPTION
**Pull request by pamaury**
This PR fixes many small issues with the USB tests in general. These are particularly problematic in SiVal where some USB tests are completely broken.

Review commit by commit, each is small.

Fixes #28827

### CODE REVIEW

File: sw/host/tests/chip/usb/usb.rs [hunk 1]
```diff
@@ -259,12 +259,24 @@ impl UsbHub {
         self.handle.device()
     }
 
+    // Report the status of a port (only returns the port status, not the port change).
+    fn port_status(&self, port: u8, timeout: Duration) -> Result<u16> {
```
Comment (engdoreis) [inline sw/host/tests/chip/usb/usb.rs:283]: maybe make the port a u16?

File: sw/host/tests/chip/usb/usb.rs [hunk 2]
```diff
@@ -41,7 +41,7 @@ pub struct UsbOpts {
     pub strapping: Vec<String>,
```
Comment (engdoreis) [inline sw/host/tests/chip/usb/usb.rs:41]: I would squash this commit, the line changed was intruduced by the previous commit.

File: sw/device/tests/usbdev_suspend.c [hunk 3]
```diff
@@ -1835,7 +1835,7 @@ bool usbdev_suspend_test(usbdev_suspend_phase_t init_phase,
 
       // Presently, the FPGA build is expected to be observed/monitored by a
       // developer, so verbose reporting is appropriate.
-      verbose = false;  // true;
+      verbose = true;  // true;
```
Comment (engdoreis) [inline sw/device/tests/usbdev_suspend.c:1838]: Should this change be committed? It feels that is ment for debbugging?

File: sw/device/tests/usbdev_suspend.c [hunk 4]
```diff
@@ -1816,7 +1816,7 @@ bool usbdev_suspend_test(usbdev_suspend_phase_t init_phase,
       host_resumes = true;
       host_resets = true;
       host_disconnects = true;
-      verbose = false;
+      verbose = true;
```
Comment (engdoreis) [inline sw/device/tests/usbdev_suspend.c:1819]: The same question as in my previous comment, if it should be committed, I would consider squasing with that commit?

File: sw/host/tests/chip/usb/README.md [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+```
+[2025-07-10T11:59:59.958Z INFO  usbdev_suspend] parent hub at bus=<BUS>, address=<ADDR>, port numbers=<PORTS>
+```
+From this, we now know the bus and address of the hub.
+
+### Setting the permissions
+
+Once you know the bus and address of the device, run as root:
+```bash
+chmod 0666 /dev/bus/usb/<BUS>/<ADDR>
```
Comment (engdoreis) [inline sw/host/tests/chip/usb/README.md:55]: I wonder if we should print this command as a hint with the error message.

**Review by engdoreis — APPROVED** [review]
I left some suggestions, Otherwise it LGTM.

File: sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json [hunk 6]
```diff
@@ -515,5 +521,17 @@
...
+    {
+      "name": "USB_VBUS_SENSE",
+      "pins": [
+        // The IOA2 is set to push-pull low by default to prevent entering SPI rescue mode
+        // But IOA2 is also connected to the USB VBUS SENSE buffer which prevents the OT
+        // device from sensing USB.
+        {
+          "name": "IOA2",
+          "mode": "Input",
+        }
```
Comment (cfrantz) [inline sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json:533]: Do we want to change the trigger input for the SPI-DFU tests to not be dual-use with VBUS sense?  The use of `Ioa2` for SPI-DFU was based on how the downstream customer has connected the chip in their integration, but we could choose a different IO for the generic tests.

File: sw/host/tests/chip/usb/usb.rs (hunk 1 above)
Comment (pamaury) [reply sw/host/tests/chip/usb/usb.rs:283]: I made this a `u8` because the hub specification defines the total number of ports in the hub descriptor as a `u8`, and in fact several hub requests put the port number in the lower byte of `wIndex` and something else in the high byte. For the `GetPortStatus` request, the spec is a bit ambiguous and for consistency, it seems to me that this should not be a 16-bit value.

File: sw/device/tests/usbdev_suspend.c (hunk 3 above)
Comment (pamaury) [reply sw/device/tests/usbdev_suspend.c:1838]: The issue when disabling verbose logging is that CI failures are essentially undiagnosable. I think we get more "value" out of CI testing by enabling this flag. Furthermore, logging changes the timing of the test and I personally think that we should ensure that this test is timing independent (as much as possible) so enaling logging in CI is a good way to ensure that this is the case.

File: sw/host/tests/chip/usb/README.md (hunk 5 above)
Comment (pamaury) [reply sw/host/tests/chip/usb/README.md:55]: Good suggestion, I will change the error message to suggest that.

File: sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json (hunk 6 above)
Comment (pamaury) [reply sw/host/opentitanlib/src/app/config/hyperdebug_teacup.json:533]: It's probably a good idea to change it to avoid some confusion but even if we change it, I would keep those pin definitions because it's useful to have a board-specific setup for VBUS sense potentially.
