### PR TITLE
[sival] Port sysrst_ctrl_ec_rst_l

### LINKED ISSUE #21177: [chip-test]  chip_sw_sysrst_ctrl_ec_rst_l
### Test point name

[chip_sw_sysrst_ctrl_ec_rst_l](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_sysrst_ctrl_testplan.hjson#L143C13-L143C41)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

@rswarbrick 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 1

### LINKED ISSUE #21178: chip-test] chip_sw_sysrst_ctrl_flash_wp_l
### Test point name

[chip_sw_sysrst_ctrl_flash_wp_l](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_sysrst_ctrl_testplan.hjson#L160C13-L160C43)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

@rswarbrick 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 1

### PR DESCRIPTION
**Pull request by pamaury**
The existing sim_dv test was too DV specific so I created a test from scratch. I intentionally avoid backdoor writes to make it simpler and instead leverage the GPIO monitor functionality. The test goes further than DV and does the optional part of the testplan: make sure the EC reset stretch functionality works.

Fixes #21177, fixes #21178

### CODE REVIEW

File: sw/device/lib/testing/sysrst_ctrl_testutils.h [hunk 1]
```diff
@@ -12,17 +12,41 @@
...
+ * @param release_ec Whether to release the EC reset pin.
+ * @param release_flash Whether to release the flast write protect pin.
+ */
+void sysrst_ctrl_testutils_release_dio(dif_sysrst_ctrl_t *sysrst_ctrl,
+                                       bool release_ec, bool release_flash);
+
+/**
+ * Set the EC reset pulse width.
+ *
+ * This function will panic if the pulse width does not fit into the regiter.
```
Comment (rswarbrick) [inline sw/device/lib/testing/sysrst_ctrl_testutils.h:42]: I guess there's a problem with units here. We need the pulse width, as measured in AON clock cycles, to fit in the 16 bit register.

Also nit: Missing "s" in "register".

Maybe something like this?

The supplied pulse width is converted into a count of AON clock ticks. If the width is not an exact multiple of the AON clock period, the conversion rounds down. The function will panic if the converted pulse width does not fit into the RST_CTL register.

File: sw/device/tests/sysrst_ctrl_ec_rst_l_test.c [hunk 2]
```diff
@@ -0,0 +1,138 @@
...
+static void pinmux_setup(void) {
+  for (int i = 0; i < kNumMioInputs; ++i) {
+    CHECK_DIF_OK(
+        dif_pinmux_input_select(&pinmux, kPeripheralInputs[i], kInputPads[i]));
+  }
+}
+
+static void configure_combo_reset(void) {
+  // FIXME (pamaury): if I set the ec reset pulse width to 0 or 1,
+  // then on reset the EC reset line pulled down, then up for a short time
```
Comment (rswarbrick) [inline sw/device/tests/sysrst_ctrl_ec_rst_l_test.c:65]: Nit: (I realise this is a FIXME comment, but...) I think you want to say the reset line *is* pulled down here.

(I had to read it a couple of times to understand what was going on)

File: sw/device/tests/sysrst_ctrl_ec_rst_l_test.c [hunk 3]
```diff
@@ -0,0 +1,138 @@
...
+  // and then down again. This seems contrary to the documentation and also
+  // contrary to what happens for values >1 when it is only pulled down.
```
Comment (rswarbrick) [inline sw/device/tests/sysrst_ctrl_ec_rst_l_test.c:67]: (Similar FIXME question, but...): I think it might be better to add a comma: "... values >1, when it ...".

I initially wondered whether you meant that something different happened if both of these things were true:
- Value > 1
- Something is only pulled down

File: sw/device/tests/sysrst_ctrl_ec_rst_l_test.c [hunk 4]
```diff
@@ -0,0 +1,138 @@
...
+  CHECK_DIF_OK(dif_sysrst_ctrl_key_combo_detect_configure(
+      &sysrst_ctrl, kDifSysrstCtrlKeyCombo0,
+      (dif_sysrst_ctrl_key_combo_config_t){
+          .actions = kDifSysrstCtrlKeyComboActionEcReset |
+                     kDifSysrstCtrlKeyComboActionSelfReset,
+          .detection_time_threshold = kDetectionTimeThreshold,
+          .embedded_controller_reset_duration = 2,  // See above.
+          .keys = kDifSysrstCtrlKey0 | kDifSysrstCtrlKey1}));
+  // Use testutils that computes the value using the actual aon clock frequency.
```
Comment (rswarbrick) [inline sw/device/tests/sysrst_ctrl_ec_rst_l_test.c:76]: Grammar nit: Maybe "Use testutils to compute ..."

(That way, we don't need an opinion about whether "testutils" is singular or plural!)

**Review by rswarbrick — COMMENTED** [review]
Some nitty questions, but this looks sensible to me, I think.

File: sw/device/lib/testing/sysrst_ctrl_testutils.h (hunk 1 above)
Comment (pamaury) [reply sw/device/lib/testing/sysrst_ctrl_testutils.h:42]: Thanks Rupert, that's indeed much clearer.

File: sw/device/tests/sysrst_ctrl_ec_rst_l_test.c [hunk 5]
```diff
@@ -0,0 +1,138 @@
...
+      mmio_region_from_addr(TOP_EARLGREY_PWRMGR_AON_BASE_ADDR), &pwrmgr));
+  CHECK_DIF_OK(dif_rstmgr_init(
+      mmio_region_from_addr(TOP_EARLGREY_RSTMGR_AON_BASE_ADDR), &rstmgr));
+
+  pinmux_setup();
+  sysrst_ctrl_testutils_setup_dio(&pinmux);
+  rstmgr_reset_info = rstmgr_testutils_reason_get();
+
+  // On a POR, start the test: prepare the sysrst_ctrl with a combo to reset
+  // the chip and wait for the host to reset the device using a combo.
```
[the remark this answers is not in the document]
Comment (pamaury) [reply sw/device/tests/sysrst_ctrl_ec_rst_l_test.c:109]: Yes that's the same combo, I will update the text.

File: sw/device/lib/testing/sysrst_ctrl_testutils.c [hunk 6]
```diff
@@ -39,30 +40,49 @@ void setup_dio_pins(dif_pinmux_t *pinmux, dif_sysrst_ctrl_t *sysrst_ctrl) {
...
+  }
+}
+
+void sysrst_ctrl_testutils_set_ec_rst_pulse_width(
+    dif_sysrst_ctrl_t *sysrst_ctrl, uint32_t pulse_us) {
+  // The register field counts in aon_clock ticks.
+  uint64_t ticks =
+      udiv64_slow((uint64_t)pulse_us * kClockFreqAonHz, 1000 * 1000, NULL);
+  // The register field is 16-bit wide.
+  CHECK(ticks <= 0xffff);
```
Comment (engdoreis) [inline sw/device/lib/testing/sysrst_ctrl_testutils.c:85]: UINT16_MAX?

File: sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ec_rst_l.rs [hunk 7]
```diff
@@ -0,0 +1,232 @@
...
+
+const COMBO_PINS_HIGH: u8 = 0x3;
+const COMBO_PINS_LOW: u8 = 0;
+const COMBO_PINS_KEY0_HIGH: u8 = 1;
+const EC_RST_FLASH_WP_HIGH: u8 = 0x3;
+const EC_RST_PIN_INDEX: u8 = 0;
+const FLASH_WP_PIN_INDEX: u8 = 1;
+const EC_RST_PIN: &str = "IOR8";
+
+const EC_RST_COMBO_PULSE_WIDTH_US: u64 = 100_000; // Set on the device.
```
Comment (engdoreis) [inline sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ec_rst_l.rs:62]: I've seemed `micros` rather than `us` as sufix in Opentitan tests.

File: sw/device/tests/BUILD [hunk 8]
```diff
@@ -4384,6 +4384,36 @@ opentitan_test(
...
+    srcs = ["sysrst_ctrl_ec_rst_l_test.c"],
+    cw310 = new_cw310_params(
+        test_cmd = """
+            --bitstream="{bitstream}"
+            --bootstrap="{firmware}"
+        """,
+        test_harness = "//sw/host/tests/chip/sysrst_ctrl:sysrst_ctrl_ec_rst_l",
+    ),
+    exec_env = {
+        "//hw/top_earlgrey:fpga_cw310_sival": None,
```
Comment (engdoreis) [inline sw/device/tests/BUILD:4398]: Should the silicon targets be added?

File: sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ec_rst_l.rs [hunk 9]
```diff
@@ -0,0 +1,232 @@
...
+
+    // We are going to set the combo pins to low and monitor the GPIO.
+    let gpio_monitoring = params.transport.gpio_monitoring()?;
+    let clock_nature = gpio_monitoring.get_clock_nature()?;
+    let ClockNature::Wallclock { resolution, .. } = clock_nature else {
+        bail!("Cannot measure EC reset pulse width: the transport GPIO monitor does not have reliable clock source");
+    };
+    log::info!("GPIO monitor clock resolution: {resolution}");
+    // Convert a timestamp in transport unit to something in nanoseconds.
+    let timestamp_to_ns = |timestamp: u64| -> u64 {
```
Comment (engdoreis) [inline sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ec_rst_l.rs:97]: Should this closure be defined closer to where it's  used?

**Review by engdoreis — APPROVED** [review]
LGTM, please check the comments I left.

File: sw/device/lib/testing/sysrst_ctrl_testutils.c (hunk 6 above)
Comment (pamaury) [reply sw/device/lib/testing/sysrst_ctrl_testutils.c:85]: I don't think this would be suitable since it's a field mask. I have replaced it with the mask from the autogenerated headers.

File: sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ec_rst_l.rs (hunk 7 above)
Comment (pamaury) [reply sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ec_rst_l.rs:62]: I looked at the code and it's a bit random. I will change it to `USEC` since it's used in another rust test and in several device tests.

File: sw/device/tests/BUILD (hunk 8 above)
Comment (pamaury) [reply sw/device/tests/BUILD:4398]: I will add the silicon targets after I am finished with all the sysrst_ctrl tests.

File: sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ec_rst_l.rs (hunk 9 above)
Comment (pamaury) [reply sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ec_rst_l.rs:97]: My intention was to define it next to where `resolution` is defined because it's meaning is not super clear. But I wil move it.

**Comment by pamaury** [comment]
Can I merge this @engdoreis ?

**Comment by pamaury** [comment]
I have updated the PR (rebased) and remove the FIXME now that the problem has been understood and the sysrst_ctrl documentation updated.
