### PR TITLE
Fix chip sw sram ctrl main scrambled access test

### LINKED ISSUE #14551: [test-triage] chip_sw_sram_ctrl_main_scrambled_access_jitter_en
### Hierarchy of regression failure

Chip Level

### Failure Description

  UVM_ERROR @ 4510.502520 us: (sw_logger_if.sv:521) [sram_ctrl_main_scrambled_access_test_prog_sim_dv(sw/device/tests/sim_dv/sram_ctrl_main_scrambled_access_test.c:251)] CHECK-fail: mmio_region_read32(mmio_region_from_addr( TOP_EARLGREY_SRAM_CTRL_RET_AON_RAM_BASE_ADDR), INTEGRITY_EXCEPTION_COUNT_OFFSET) == SRAM_CTRL_TESTUTILS_DATA_NUM_WORDS
  UVM_INFO @ 4510.502520 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]

### Steps to Reproduce

- https://github.com/lowrisc/opentitan/tree/51417ec839826e2ca585eac843f25bcbb7f8ec9f
- ./util/dvsim/dvsim.py -t vcs -w  fsdb hw/top_earlgrey/dv/chip_sim_cfg.hjson -i  -s 2199609583 -r 1 --build-seed 3859254937

### PR DESCRIPTION
**Pull request by engdoreis**
This PR:

-  Disable the integrity errors via testbench for scramble test, relying only in the data to be incorrect after the scrambling.
-  Change the test to tolerate a minimum of ECC errors in the scrambling test.

Fixes #14551

### CODE REVIEW

**Comment by tjaychen** [comment]
wow did this work? because even though we've disabled the scoreboard monitoring, internally the ibex should still be getting data exceptions, did that not happen..? or it did and we just don't care, and rely on data mismatch as you say?

**Comment by engdoreis** [comment]
> wow did this work? because even though we've disabled the scoreboard monitoring, internally the ibex should still be getting data exceptions, did that not happen..? or it did and we just don't care, and rely on data mismatch as you say?

The internal interruptions (execeptions) is happening most of the time and the test is capturing them to check the ECC error. This PR change the test to tolerate not getting an ECC error (internal interrupt) for all data every time the memory is scrumbled as it is statistically possible to happen.
Does that make sense?

File: sw/device/tests/sim_dv/sram_ctrl_main_scrambled_access_test.c [hunk 1]
```diff
@@ -240,23 +249,40 @@ bool test_main(void) {
...
         TOP_EARLGREY_SRAM_CTRL_RET_AON_RAM_BASE_ADDR, &kRamTestPattern1));
     CHECK(sram_ctrl_testutils_read_check_neq(
         TOP_EARLGREY_SRAM_CTRL_RET_AON_RAM_BASE_ADDR, &kRamTestPattern2));
 
-    CHECK(mmio_region_read32(mmio_region_from_addr(
-                                 TOP_EARLGREY_SRAM_CTRL_RET_AON_RAM_BASE_ADDR),
-                             INTEGRITY_EXCEPTION_COUNT_OFFSET) ==
-          SRAM_CTRL_TESTUTILS_DATA_NUM_WORDS);
+    // Statistically there is always a chance that after changing the scrambling
+    // the ECC bits are correct and no IRQ is not triggered. So we tolerate a
```
Comment (matutem) [inline sw/device/tests/sim_dv/sram_ctrl_main_scrambled_access_test.c:259]:
```suggestion
    // the ECC bits are correct and no IRQ is triggered. So we tolerate a
```

**Review by matutem — APPROVED** [review]
With a minor suggested change in a comment. LGTM.

**Comment by tjaychen** [comment]
> 

sounds good, thank you.

**Review by tjaychen — APPROVED** [review]

File: sw/device/tests/sim_dv/sram_ctrl_main_scrambled_access_test.c (hunk 1 above)
Comment (engdoreis) [reply sw/device/tests/sim_dv/sram_ctrl_main_scrambled_access_test.c]: Fixed
