### PR TITLE
[lint] Fix shellcheck errors across the repo

### LINKED ISSUE #13343: Shellcheck finds some warnings/errors in shell scripts
I noticed that Shellcheck[^0] is turning up some results[^1] on OpenTitan's shell scripts. AFAICT, most of the advice seems actionable and correct.

Picking on one script as an example, Shellcheck emits an error when it sees `$@` in a string because it has surprising semantics. There is a well-documented rationale at https://www.shellcheck.net/wiki/SC2145.

```
In ./ci/scripts/check-generated.sh line 37:
        echo "Auto-generated $thing not up-to-date. Regenerate with '$@'."
                                                                     ^-- SC2145 (error): Argument mixes string and array. Use * or separate argument.
```

Do any of these scripts process untrusted input? (Are there potential security implications for any of these errors?)

Regardless, I propose that we walk through each of the errors/warnings and address root causes and add suppressions[^2] for any false-positives.

Here's a handy command for generating a colorful report:

    $ find . \( -name '*.sh' -o -name '*.bash' \) -print -exec shellcheck --severity=warning --color=always {} \; | less

[^0]: https://github.com/koalaman/shellcheck
[^1]: https://gist.github.com/dmcardle/e4a388b6b7106a2804ebf0655b1cde82
[^2]: https://www.shellcheck.net/wiki/Ignore

### PR DESCRIPTION
**Pull request by milesdai**
This PR adds shellcheck to CI and fixes all the warnings it throws. Note that we are only checking issues with severity "warning" or higher.

Addresses #13343.

### CODE REVIEW

**Comment by msfschaffner** [comment]
Sorry I should backtrack - I was under the impression that the shellcheck errors block CI as well, which does not seem to be the case. Let me make a separate fix for the Clang issues.

File: ci/scripts/run-fpga-cw310-tests.sh [hunk 1]
```diff
@@ -23,6 +24,9 @@ export BITSTREAM="--offline --list ${SHA}"
 # in case we've crashed the UART handler on the CW310's SAM3U
 trap 'python3 ./util/fpga/cw310_reboot.py' EXIT
 
+readarray -t test_rom_tests < <(./bazelisk.sh query 'rdeps(//...,@bitstreams//:bitstream_test_rom)')
```
Comment (dmcardle) [inline ci/scripts/run-fpga-cw310-tests.sh:27]: The two `<` symbols threw me — this is subtle! Could you maybe add an explanatory comment above this line?

I guess `<(./bazelisk.sh query 'rdeps(//...,@bitstreams//:bitstream_test_rom)')` is process substitution, so that part is equivalent to a file descriptor. The first `<` redirects the file to `readarray`'s stdin?

File: ci/scripts/run-shellcheck.sh [hunk 2]
```diff
@@ -0,0 +1,13 @@
...
+# Licensed under the Apache License, Version 2.0, see LICENSE for details.
+# SPDX-License-Identifier: Apache-2.0
+
+set -e
+
+EXCLUDED_DIRS="-name third_party -o -name vendor -o -name lowrisc_misc-linters"
+
+# Get an array of all shell scripts to check
+readarray -t shell_scripts < \
+    <(find . \( $EXCLUDED_DIRS \) -prune -o -name '*.sh' -print)
```
Comment (dmcardle) [inline ci/scripts/run-shellcheck.sh:12]: Should we be searching `.` or `"$(dirname "$(readlink -e "${BASH_SOURCE[0]}")")"`?

File: util/prep-bazel-airgapped-build.sh [hunk 3]
```diff
@@ -154,9 +154,9 @@ if [[ ${AIRGAPPED_DIR_CONTENTS} == "ALL" || \
     @rust_linux_aarch64_toolchains//... \
     @rust_linux_x86_64_toolchains//... \
     @rust_windows_x86_64_toolchains//...
-  cp -R $(${BAZELISK} info output_base)/external/${BAZEL_PYTHON_WHEEL_REPO} \
+  cp -R "$(${BAZELISK} info output_base)"/external/${BAZEL_PYTHON_WHEEL_REPO} \
```
Comment (dmcardle) [inline util/prep-bazel-airgapped-build.sh:157]: Does `${BAZEL_PYTHON_WHEEL_REPO}` not need quoting?

**Review by dmcardle — COMMENTED** [review]
Awesome work! Thanks, Miles! Left a handful of comments, mostly trying to wrap my head around bashisms.

File: azure-pipelines.yml [hunk 4]
```diff
@@ -87,6 +87,26 @@ jobs:
   - bash: ci/scripts/rust-format.sh $SYSTEM_PULLREQUEST_TARGETBRANCH
     condition: eq(variables['Build.Reason'], 'PullRequest')
     displayName: rustfmt
+  - bash: |
+      set -e
+      # Azure-specific installation
+      # The latest version of shellcheck available to Azure Pipelines is 0.4.6-1.
```
[the remark this answers is not in the document]
Comment (milesdai) [reply azure-pipelines.yml:93]: Yup - I've clarified the comment here.

File: yum-requirements.txt [hunk 5]
```diff
@@ -39,6 +39,7 @@ python3
 python3-pip
 python3-setuptools
 python3-wheel
+shellcheck
```
[the remark this answers is not in the document]
Comment (milesdai) [reply yum-requirements.txt:42]: Oops this should be `ShellCheck`. Thanks for catching that!

File: bazelisk.sh [hunk 6]
```diff
@@ -31,20 +31,23 @@ declare -A architectures=(
...
-    local file="$1"
-    local target="$(os_arch)"
-    local value="$(sha256sum "${file}" | cut -f1 -d' ')"
+    local file target value
+    file="$1"
+    target="$(os_arch)"
+    value="$(sha256sum "${file}" | cut -f1 -d' ')"
     local expect="${hashes[$target]}"
-    return $(test "$value" == "$expect")
+    test "$value" == "$expect"
```
[the remark this answers is not in the document]
Comment (milesdai) [reply bazelisk.sh:45]: > Separately, did shellcheck want you to pre-declare variables as `local`? If so, did you miss the `expect` variable?

This is [SC2155](https://github.com/koalaman/shellcheck/wiki/SC2155) which is concerned that doing something like `local var=$(...)` will mask any errors in the command substitution. In this case, it's just a variable substitution which will not error out.

File: ci/bazelisk.sh [hunk 7]
```diff
@@ -8,15 +8,15 @@
...
+    cd "$PWD_OVERRIDE" || exit
 fi
 
 echo "Running bazelisk in $(pwd)."
 
 # An additional bazelrc must be synthesized to specify precisely how to use the
 # GCP bazel cache.
 GCP_BAZELRC="$(mktemp /tmp/XXXXXX.bazelrc)"
-trap "rm $GCP_BAZELRC" EXIT
+trap 'rm $GCP_BAZELRC' EXIT
```
[the remark this answers is not in the document]
Comment (milesdai) [reply ci/bazelisk.sh:19]: Yes -- I thought about if either case would cause more surprising behavior if new code was added but ended up deciding that they're about the same. This is just to appease shellcheck.

File: bazelisk.sh (hunk 6 above)
[the remark this answers is not in the document]
Comment (dmcardle) [reply bazelisk.sh:45]: Wow, SC2155 is new to me. I agree with your reasoning :) And I assume shellcheck agrees as well, or else you'd have to write a suppression line.

[the remark this answers is not in the document]
Comment (dmcardle) [reply bazelisk.sh:45]: Did you have thoughts on synthesizing the input line for `sha256sum --check` (first comment)? Totally fine if that's out of scope, just thought it would make it a little cleaner.

File: ci/scripts/make_distribution.sh [hunk 8]
```diff
@@ -37,6 +37,10 @@ cp LICENSE "$DIST_DIR"
 for pat in "${DIST_ARTIFACTS[@]}"; do
   echo "Searching for $pat." >&2
   found_file=false
+  # Looping over find output is a problem if our file paths have glob
+  # characters or spaces.  However, we do not have filenames like that, and the
```
[the remark this answers is not in the document]
Comment (milesdai) [reply ci/scripts/make_distribution.sh:41]: Yes - I've clarified my comment to say that we don't have file paths like that in CI. There should be no reason to run this script outside of CI in any normal debugging scenario.

File: util/prep-bazel-airgapped-build.sh (hunk 3 above)
Comment (milesdai) [reply util/prep-bazel-airgapped-build.sh:157]: Not according to shellcheck since this is a variable expansion rather than command substitution.

File: ci/scripts/run-fpga-cw310-tests.sh (hunk 1 above)
Comment (milesdai) [reply ci/scripts/run-fpga-cw310-tests.sh:27]: I added a comment to explain how we're using input redirection and process substitution and why this is necessary.

File: ci/scripts/run-shellcheck.sh (hunk 2 above)
Comment (milesdai) [reply ci/scripts/run-shellcheck.sh:12]: Yes - you're right. This would assume that the script is run from $REPO_TOP. I've modified this to `cd` into `${BASH_SOURCE[0]}/../..` which would be $REPO_TOP before running `find`.

File: bazelisk.sh (hunk 6 above)
[the remark this answers is not in the document]
Comment (milesdai) [reply bazelisk.sh:45]: I've added a commit to implement your suggestion.

File: util/prep-bazel-airgapped-build.sh (hunk 3 above)
Comment (dmcardle) [reply util/prep-bazel-airgapped-build.sh:157]: I guess shellcheck is confident that the variable doesn't contain spaces?

```console
% cat /tmp/script.sh
#!/bin/bash
my_var="foobar"
echo "hello"${my_var}
%
% shellcheck /tmp/script.sh
%
% cat /tmp/script.sh
#!/bin/bash
my_var="foo bar"
echo "hello"${my_var}
%
% shellcheck /tmp/script.sh

In /tmp/script.sh line 3:
echo "hello"${my_var}
            ^-------^ SC2086 (info): Double quote to prevent globbing and word splitting.

Did you mean:
echo "hello""${my_var}"

For more information:
  https://www.shellcheck.net/wiki/SC2086 -- Double quote to prevent globbing ...
```

Comment (milesdai) [reply util/prep-bazel-airgapped-build.sh:157]: Actually, I think the reason it's not complaining is that the entire line is already quoted, so there's no need to quote this expansion in particular. See [SC2086](https://www.shellcheck.net/wiki/SC2086).

Comment (milesdai) [reply util/prep-bazel-airgapped-build.sh:157]: Oh shellcheck does flag it but just as an info-level message rather than a warning.

**Review by dmcardle — APPROVED** [review]
LGTM! Thanks for cleaning up all of these scripts!

File: util/prep-bazel-airgapped-build.sh (hunk 3 above)
Comment (dmcardle) [reply util/prep-bazel-airgapped-build.sh:157]: Gotcha. I'm fine with leaving it if it's explicitly below the threshold we care about.

**Review by timothytrippel — APPROVED** [review]

File: apt-requirements.txt [hunk 9]
```diff
@@ -44,6 +44,7 @@ python3-pip
 python3-setuptools
 python3-urllib3
 python3-wheel
+shellcheck
```
Comment (timothytrippel) [inline apt-requirements.txt:47]: This added requirement may warrant an email / slack announcement since it looks like its run in CI now?

**Comment by dmcardle** [comment]
> It is quite hard to install shellcheck on Google Airgapped environment. It needs Haskell compiler and libraries.. That means, whenever we decide to block the CI for shellcheck, Turn-around Time will be longer.

Are you saying that installing shellcheck is slow because it pulls in the Haskell platform? AFAICT, this is not true on my Debian machine.

```console
% apt-cache show shellcheck | grep Depends
Depends: libc6 (>= 2.29), libffi8 (>= 3.4), libgmp10 (>= 2:6.2.1+dfsg)
```

I think the trick is that the Haskell compiler bakes the runtime into the binary, so the package doesn't even need to install the compiler.

**Comment by timothytrippel** [comment]
I think @eunchan is talking about the fact that if the shellcheck doesn't run on the airgapped setup it will be a little more of a hassle to make changes on an airgapped setup and then test them on the non-airgapped setup as opposed to just having the necessary tools on both. Needless to say, we have solved this issue on our airgapped setup.
