### PR TITLE
[meson] Put Toolchain Config into build-out

### LINKED ISSUE #2428: [sw,meson] Infinite ninja build loop
I quite commonly encounter a situation where a `ninja -C ./built-out` causes some kind of infinite loop. This seems to occur when I run `ninja -C ./build-out` having had a successful build previously, changed some file and then run again. Here is an example of the output:

```Found ninja-1.8.2 at /usr/bin/ninja
WARNING: Cross file does not specify strip binary, result will not be stripped.
WARNING: Cross file does not specify strip binary, result will not be stripped.
[0/1] Regenerating build files.
The Meson build system
Version: 0.53.2
Source dir: /home/greg/work/opentitan_area/opentitan
Build dir: /home/greg/work/opentitan_area/opentitan/build-out
Build type: cross build
Project name: opentitan
Project version: 0.1
C compiler for the build machine: cc (gcc 7.5.0 "cc (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C linker for the build machine: cc ld.bfd 2.30
C++ compiler for the build machine: c++ (gcc 7.5.0 "c++ (Ubuntu 7.5.0-3ubuntu1~18.04) 7.5.0")
C++ linker for the build machine: c++ ld.bfd 2.30
C compiler for the host machine: /tools/riscv/bin/riscv32-unknown-elf-gcc (gcc 9.2.0 "riscv32-unknown-elf-gcc (GCC) 9.2.0")
C linker for the host machine: /tools/riscv/bin/riscv32-unknown-elf-gcc ld.bfd 2.32
C++ compiler for the host machine: /tools/riscv/bin/riscv32-unknown-elf-g++ (gcc 9.2.0 "riscv32-unknown-elf-g++ (GCC) 9.2.0")
C++ linker for the host machine: /tools/riscv/bin/riscv32-unknown-elf-g++ ld.bfd 2.32
Build machine cpu family: x86_64
Build machine cpu: x86_64
Host machine cpu family: x86_64
Host machine cpu: x86_64
Target machine cpu family: x86_64
Target machine cpu: x86_64
Compiler for C supports arguments -Wa,--no-pad-sections: YES
meson.build:74: WARNING: Consider using the built-in optimization level instead of using "-Os".
meson.build:78: WARNING: Consider using the built-in optimization level instead of using "-Os".
Program python3 found: YES (/usr/bin/python3)
Program objdump found: YES (/usr/bin/objdump)
Program objcopy found: YES (/usr/bin/objcopy)
Program srec_cat found: YES (/usr/bin/srec_cat)
Program git found: YES (/usr/bin/git)
Dependency threads found: YES unknown (cached)
Program cargo found: YES (/home/greg/.cargo/bin/cargo)
Dependency libftdi1 found: YES 1.4 (cached)
Dependency libusb-1.0 found: YES 1.0.21 (cached)
Dependency libcrypto found: YES 1.1.1 (cached)
Build targets in project: 158
```
This repeats over and over

A `meson_init.sh -f` is required to fix it (the `-f` is needed a plain `meson_init.sh` doesn't fix it). I'll see if I can get some steps to reproduce but I think it generally occurs when I've left the build for a while (i.e. yesterday it built successfully as the last thing I did, today I alter a file, run the build and you get the loop) so potentially somehow time dependent indicating something to do with timestamps?

Thought I'd open the issue to see if anyone else has seen similar behaviour or has an idea what may cause it.

### PR DESCRIPTION
**Pull request by lenary**
This commit moves the toolchain configuration file (which is created if
you use an old or non-standard toolchain) into `build-out` rather than
putting it into `/tmp`. This should prevent meson build loops, as noted
in #2428.

---

Closes #2428 (Hopefully).

### CODE REVIEW

**Comment by imphil** [comment]
This only makes the problem less likely, but doesn't solve it: if you remove the toolchain.txt file from build-out/* you still get the loop.

**Comment by imphil** [comment]
A `cp -a` might do the trick, I didn't try that.

**Comment by lenary** [comment]
Why would you be removing toolchain.txt from `build-out` manually? I can see an OS doing it to your `/tmp` file, but the same shouldn't happen to your build directories.

**Comment by lenary** [comment]
I can add a `touch -r toolchain.txt "$cross_file"` if you think that would help (which has to come after the perl line, of course…)

**Comment by imphil** [comment]
Having a broken/incomplete `build-out` directory isn't a completely artificial scenario; it could be leftover from a previous change (or a future change which adds/removes files in unexpected ways), or an aborted build halfway through. Ninja/meson deal with that just fine by regenerating files which aren't up-to-date. I'd expect the same behavior for the toolchain.txt file.

**Comment by lenary** [comment]
The real problem is we should probably not be generating `toolchain.txt` at all - it's a configuration file for meson so meson can certainly not regenerate it.

This is a big reason why the new toolchains ship a meson toolchain configuration file.

File: meson_init.sh [hunk 1]
```diff
@@ -135,9 +135,10 @@ else
     echo "Unable to find meson toolchain file at $ARG_toolchain_file. Aborting." >&2
     exit 1
   else
-    cross_file=$(mktemp /tmp/toolchain.XXXXXX.txt)
+    cross_file="${OBJ_DIR}/toolchain-configured.txt"
```
Comment (imphil) [inline meson_init.sh:138]:
```suggestion
    cross_file="$OBJ_DIR/toolchain-configured.txt"
```

And you need to create the OBJ_DIR first by moving the lines below this block above it (run `./meson_init.sh -f` to check)

**Review by imphil — APPROVED** [review]
Does the `touch` work for you? It doesn't on my side, doing the following still gives a build loop:

```
./meson_init.sh -f
rm build-out/toolchain-configured.txt
ninja -C build-out
# see the build loop
```

If you don't see benefits from the touch either, let's remove it. The current PR continues to decrease the likelihood of build loops, so let's get it in.

**Comment by lenary** [comment]
The reason you still get a build loop on your sequence is because `ninja` never calls `./meson_init.sh`. If `ninja` finds the ninja configuration is out of date (because the files used to as inputs when it was generated have a more recent mtime), it re-runs meson with the options from the original `meson` invocation (at the end of `./meson_init.sh`). We are unable to configure meson to instead call `./meson_init.sh` when it finds the ninja configuration is out of date (and I don't think we want to run more perl over the generated `build.ninja`). (I also believe that if we add a rule to generate a `toolchain-configured.txt` within meson, that would definitely lead to build loops).

I don't understand why we think people will be `rm`-ing the `toolchain-configured.txt` file *inside the build dir*. When this file was in a tmp dir, your OS can purge that (e.g. at restart) - which was causing the original issue. Yes, users *might* delete files from inside the build dir, but at least they'd know they'd done so (unlike when the OS purges temporary files), and yes they should know they're playing with fire.

More to the point, your build is also broken if you `./meson_init.sh -f; rm build-out/build.ninja; ninja -C build-out` - yes there are special files in the build dir that if you delete, you have to entirely re-init meson using our shell script. 

I do think this PR will help, but I don't think we should block it on hypotheticals of "I deleted a configuration file from inside my build directory and now my build doesn't work".

(This entirely sidesteps the point that this wouldn't be any kind of problem if we had just said "if you're bringing your own toolchain, write your own toolchain.txt and put it somewhere associated with the toolchain itself", which is effectively what the lowrisc toolchains do.)

**Comment by imphil** [comment]
> I do think this PR will help, but I don't think we should block it on hypotheticals

I agree, and approved it for this reason.
