### PR TITLE
[sysrst_ctrl,sival] Port sysrst_ctrl_reset to sival

### LINKED ISSUE #19858: [chip-test] chip_sw_sysrst_ctrl_combo_reset
### Test point name

[chip_sw_sysrst_ctrl_combo_reset](https://github.com/lowRISC/opentitan/blob/cf8ffa811189c6c17285abae7eef19081213f739/hw/top_earlgrey/data/ip/chip_sysrst_ctrl_testplan.hjson#L8C13-L8C44)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [x] Hyperdebug + CW310

### Contact person

crteja

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
   - [x]  chip_sw_sysrst_ctrl_reset and chip_sw_pwrmgr_sysrst_ctrl_reset cover the test scenario
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 2

### LINKED ISSUE #21396: [chip-test, sysrst_ctrl] chip_sw_sysrst_ctrl_reset
### Test point name

chip_sw_sysrst_ctrl_reset

### Host side component
Rust?

### Opentitantool infrastructure implemented
Yes

### Silicon Validation (SiVal)

Yes

### Emulation targets
- [ ] None
- [ ] CW310
- [ ] Hyperdebug + CW310

### Checklist
Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

### LINKED ISSUE #21399: [chip-test, sysrst_ctrl] chip_sw_sysrst_ctrl_sleep_wakeup
### Test point name

chip_sw_sysrst_ctrl_sleep_wakeup

### Host side component
Rust?

### Opentitantool infrastructure implemented
Yes

### Silicon Validation (SiVal)

Yes

### Emulation targets
- [ ] None
- [ ] CW310
- [ ] Hyperdebug + CW310

### Checklist
Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

### LINKED ISSUE #21400: [chip-test, sysrst_ctrl] chip_sw_sysrst_ctrl_sleep_reset
### Test point name

chip_sw_sysrst_ctrl_sleep_reset

### Host side component
Rust?

### Opentitantool infrastructure implemented
Yes

### Silicon Validation (SiVal)

Yes

### Emulation targets
- [ ] None
- [ ] CW310
- [ ] Hyperdebug + CW310

### Checklist
Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

### PR DESCRIPTION
**Pull request by pamaury**
The first 3 commits are backports from #21560 .

This PR also introduces two aliases for the two dedicated sysrst_ctrl pins: ec_rst_l and flash_wp_l. Those are always IOR8 and IOR9, per the pin out table.

Fixes #21400
Fixes #21399
Fixes #21396
Fixes #19858

### CODE REVIEW

**Review by rswarbrick — APPROVED** [review]
Looks sensible to me.

**Comment by pamaury** [comment]
The failure is odd, it's related but I haven't been able to reproduce by running the test 50 times and I am not sure why it happens.

File: sw/device/tests/sysrst_ctrl_reset_test.c [hunk 1]
```diff
@@ -131,35 +164,46 @@ bool test_main(void) {
...
+        &pinmux, kTopEarlgreyPinmuxPeripheralInGpioGpio1,
+        kTopEarlgreyPinmuxInselIob1));
+  }
 
   CHECK_DIF_OK(dif_sysrst_ctrl_output_pin_override_set_enabled(
       &sysrst_ctrl, kDifSysrstCtrlPinEcResetInOut, kDifToggleDisabled));
 
+  // On real device, we cannot do backdoor writes the flash so we read the
+  // test phase from GPIOs.
+  uint8_t kTestPhase = kTestPhaseDV;
```
Comment (nbdd0121) [inline sw/device/tests/sysrst_ctrl_reset_test.c:199]: Why GPIO instead of console?

File: sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_reset.rs [hunk 2]
```diff
@@ -0,0 +1,181 @@
...
+    let mut val = phase as u8;
+    for pin in PHASE_PINS {
+        transport.gpio_pin(pin)?.write((val & 1) == 1)?;
+        val >>= 1;
+    }
+    ensure!(val == 0, "test phase value does not fit on the phase pins");
+    Ok(())
+}
+
+fn check_flash_wp_value(transport: &TransportWrapper, val: bool) -> Result<()> {
```
Comment (nbdd0121) [inline sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_reset.rs:90]: Instead of a function, probably it's better to do
```rust
let flash_wp_pin = transport.gpio_pin("SYSRST_CTRL_FLASH_WP_L")?;
...
ensure!(flash_wp_pin().read()?, ...);
```

**Review by jwnrt — APPROVED** [review]
LGTM, thanks especially for naming those POR pins on the host side.

File: sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_reset.rs [hunk 3]
```diff
@@ -0,0 +1,181 @@
...
+const PADS_VALUE_INIT: u8 = 0b111111;
+// Trigger reset in CheckComboReset: key0 and key1 low.
+// Also prepare for next phase: ac present low, power button high, lid open low.
+const PADS_VALUE_COMBO_RESET: u8 = 0b001100;
+// Trigger wakeup in CheckDeepSleepWakeup: lid open high.
+const PADS_VALUE_WAKEUP: u8 = 0b101100;
+// Trigger sleep reset in CheckDeepSleepReset: key2 and power button low.
+const PADS_VALUE_SLEEP_RESET: u8 = 0b100000;
+// Combo action detection time: set to around 5ms on the device.
+const COMBO_DETECTION_TIME_MICROS: u64 = 10_000;
```
Comment (nbdd0121) [inline sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_reset.rs:71]:
```suggestion
const COMBO_DETECTION_TIME: Duration = Duration::from_micros(10_000);
```
This is a const fn.

**Review by nbdd0121 — APPROVED** [review]
LGTM, but please run `//quality:rustfmt_fix` before merging

**Comment by pamaury** [comment]
> LGTM, but please run `//quality:rustfmt_fix` before merging

rustfmt does not complain about the code, is there anything in particular that looks wrong to you?

**Comment by nbdd0121** [comment]
`rustfmt --check sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_reset.rs` returns error
