### PR TITLE
[dv,top_level] Fix chip_sw_power_idle_load

### LINKED ISSUE #23570: [test-triage] chip_sw_power_idle_load failed with fatal alert
### Hierarchy of regression failure

Chip Level

### Failure Description

UVM_ERROR @ * us: (cip_base_vseq.sv:554) [chip_sw_power_idle_load_vseq] Check failed * == cfg.m_alert_agent_cfgs[alert_name].vif.get_alert() (* [*] vs * [*]) Alert rstmgr_aon_fatal_fault fired unexpectedly! has 1 failures:

    Test chip_sw_power_idle_load has 1 failures.

        2.chip_sw_power_idle_load.40326753829872626062541896155188040217937571527926133285726558347536373990204
        Line 795, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/2.chip_sw_power_idle_load/latest/run.log

          UVM_ERROR @ 4083.715549 us: (cip_base_vseq.sv:554) [uvm_test_top.env.virtual_sequencer.chip_sw_power_idle_load_vseq] Check failed 0 == cfg.m_alert_agent_cfgs[alert_name].vif.get_alert() (0 [0x0] vs 1 [0x1]) Alert rstmgr_aon_fatal_fault fired unexpectedly!
          UVM_INFO @ 4083.715549 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
          --- UVM Report catcher Summary ---

### Steps to Reproduce

- GitHub Revision: 32d52b8d416a0465b2f440dc273af0492fa07763
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_power_idle_load --build-seed 59908589074363629542901507660786833114562191729708937078847065421241135561861 --fixed-seed 40326753829872626062541896155188040217937571527926133285726558347536373990204

### Tests with similar or related failures

_No response_

### PR DESCRIPTION
**Pull request by matutem**
Disables alert_handler outgoing alert pings, since they cause the ping response to be confused for an outgoing alert. This workaround can be removed when #23644 is fixed.

Fixes #23570

### CODE REVIEW

File: sw/device/tests/chip_power_idle_load.c [hunk 1]
```diff
@@ -195,15 +195,17 @@ bool test_main(void) {
       .ping_timeout = UINT16_MAX,
   };
 
-  // 5. Configure Alerts
-  CHECK_STATUS_OK(alert_handler_testutils_configure_all(&alert_handler, config,
-                                                        kDifToggleEnabled));
+  // 5. Configure Alerts as unlocked so pings are disabled.
+  // TODO(lowrisc/opentitan#23644) enable locked when fixed to enable pings.
+  CHECK_STATUS_OK(
+      alert_handler_testutils_configure_all(&alert_handler, config,
```
Comment (moidx) [inline sw/device/tests/chip_power_idle_load.c:201]: We still want to lock the configuration but avoid setting the ping mechanism. Unfortunately, this function doesn't support this. 

You will probably have to create a local implementation of the function to achieve the expected behavior. 

The other option is to refactor the function, but that is a bigger task.

Comment (matutem) [reply sw/device/tests/chip_power_idle_load.c:201]: I think it is not strictly necessary to lock them for this test, since locking disabled only blocks outgoing pings. In any case, https://github.com/lowRISC/opentitan/issues/23644 is an M5 bug, and I intend to fix it.

Comment (moidx) [reply sw/device/tests/chip_power_idle_load.c:201]: SG. Not locking the alert means that the config is not applied. I agree that this change makes sense since you intend to adress #23644.

**Review by moidx — APPROVED** [review]

**Comment by matutem** [comment]
Re. CI failures: The test failure is unrelated, and the countermeasure failure for englishbreakfast is unrelated, and there is a pending fix for it in https://github.com/lowRISC/opentitan/pull/23650. Merging this.
