### PR TITLE
[test] Add rom_e2e_static_critical test

### LINKED ISSUE #14502: [rom-e2e] rom_e2e_static_critical
### Test point name

[rom_e2e_static_critical](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/data/rom_testplan.hjson?q=rom_e2e_static_critical)

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Contact person

@alphan

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [ ] ~Bazel build rules developed~
- [ ] ~Host-side component developed~
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)

### Verify that ROM initializes the data structures in the `.static_critical` section properly.

- Verify that `boot_measurements` holds the digest of the next stage.
  - Don't specify any usage constraints to be able to compute the actual hash in the second stage.
- Verify that `sec_mmio_ctx` is valid using `sec_mmio_check_values()` and
  `sec_mmio_check_counters()`.
- Verify that a failed sec_mmio check triggers an illegal instruction exception.

### PR DESCRIPTION
**Pull request by alphan**
This PR
* Adds the `rom_e2e_static_critical` test,
* Updates the `rom_e2e_static_critical` test in the test plan to include a negative sec_mmio test.
* Adds the `.static_critical` section to OTTF, 
* Updates `dif_hmac` to read the digest in reverse to preserve its numerical value and also to match output of commands like `sha256sum`,
* Updates `dif_hmac` key word order,
* Fixes global pointer initialization in `ottf_start.S`, and
* Fixes log format strings for array check failures.

Fixes #14502

Signed-off-by: Alphan Ulusoy <alphan@google.com>

### CODE REVIEW

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c [hunk 1]
```diff
@@ -0,0 +1,140 @@
...
+#include "sw/device/lib/testing/test_framework/ottf_main.h"
+#include "sw/device/silicon_creator/lib/base/boot_measurements.h"
+#include "sw/device/silicon_creator/lib/base/sec_mmio.h"
+#include "sw/device/silicon_creator/lib/manifest_def.h"
+
+#include "hw/top_earlgrey/sw/autogen/top_earlgrey.h"
+
+OTTF_DEFINE_TEST_CONFIG();
+
+#define RUN_TEST(test_)                    \
```
Comment (dmcardle) [inline sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:22]: Nit: Make this a function? `void run_and_log_test(void (*) test_func);`

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c [hunk 2]
```diff
@@ -0,0 +1,140 @@
...
+  LOG_INFO("Starting test " #test_ "..."); \
+  test_();                                 \
+  LOG_INFO("Finished test " #test_ ": ok.");
+
+#define CHECK_WORD_ALIGNED(addr_)                 \
+  CHECK((uintptr_t)addr_ % sizeof(uint32_t) == 0, \
```
Comment (dmcardle) [inline sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:28]: Where does the requirement for `manifest_start` and friends to be aligned come from? If they're meant to be arrays of `uint32_t`, I think we should use `alignof` here (and if that's the case, we could use `misalignment32_of()` from memory.h).

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c (hunk 1 above)
Comment (alphan) [reply sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:22]: I think I want to keep this as a macro since I don't want to duplicate the log messages.

As a side note, this will be replaced when we refactor and start using `EXECUTE_TEST` for all on-target tests.

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c [hunk 3]
```diff
@@ -0,0 +1,140 @@
...
+      dif_hmac_init(mmio_region_from_addr(TOP_EARLGREY_HMAC_BASE_ADDR), &hmac));
+  CHECK_DIF_OK(dif_hmac_mode_sha256_start(
+      &hmac, (dif_hmac_transaction_t){
+                 .digest_endianness = kDifHmacEndiannessLittle,
+                 .message_endianness = kDifHmacEndiannessLittle,
+             }));
+
+  // Copy the part of the manifest that's in the signed region to
+  // memory before pushing to hmac since it's volatile.
+  char manifest_signed_region[manifest_signed_region_size];
```
Comment (dmcardle) [inline sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:64]: I think VLA is not guaranteed in C11. Pedantically, maybe we should statically assert that `__STDC_NO_VLA__ != 1`?

**Review by dmcardle — COMMENTED** [review]
Just flushing comments from a very cursory review — I'll try to take another look today.

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c (hunk 2 above)
Comment (alphan) [reply sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:28]: It comes from the flash layout [here](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/lib/base/chip.h) and [here](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom/boot_policy_ptrs.h): flash is divided into two slots. Each slot, starts with a ROM_EXT image followed by a BL0 image. Both images are word aligned and manifest is at the start of these images (see [here](https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/rom_ext/rom_ext_common.ld;drc=2c3bfae3e7ab3491aacffafc7e2dd2cdc6af4e0f;l=62)).

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c (hunk 3 above)
Comment (alphan) [reply sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:64]: Thanks for pointing this out, TIL :) I'll just use `sizeof(manifest_t)` for the sake for simpicity.

File: sw/device/lib/dif/dif_hmac.c [hunk 4]
```diff
@@ -246,11 +246,12 @@ dif_result_t dif_hmac_finish(const dif_hmac_t *hmac,
...
-  // Read the digest.
-  // TODO Static assert register layout.
-  mmio_region_memcpy_from_mmio32(hmac->base_addr, HMAC_DIGEST_0_REG_OFFSET,
-                                 digest->digest,
-                                 HMAC_PARAM_NUM_WORDS * sizeof(uint32_t));
+  // Read the digest in reverse to preserve the numerical value.
+  // The least significant word is at HMAC_DIGEST_7_REG_OFFSET.
+  for (size_t i = 0; i < ARRAYSIZE(digest->digest); ++i) {
+    digest->digest[i] = mmio_region_read32(
+        hmac->base_addr, HMAC_DIGEST_7_REG_OFFSET - i * sizeof(uint32_t));
```
Comment (moidx) [inline sw/device/lib/dif/dif_hmac.c:253]: Does this change require `kRefExpectedShaDigest` in [hmac_utils](https://github.com/lowRISC/opentitan/blob/fe8a53a299d244d254b4a80eb83d8747d4c046a4/sw/device/lib/testing/hmac_testutils.c#L28-L38) to be updated as well?

File: sw/device/lib/testing/test_framework/BUILD [hunk 5]
```diff
@@ -140,6 +143,8 @@ cc_library(
         "//sw/device/lib/runtime:hart",
         "//sw/device/lib/runtime:ibex",
         "//sw/device/lib/runtime:log",
+        "//sw/device/silicon_creator/lib/base:static_critical_boot_measurements",
```
Comment (moidx) [inline sw/device/lib/testing/test_framework/BUILD:146]: nit: Can you update the comment above `ottf_start` to include details on how the target is used in E2E tests?

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c [hunk 6]
```diff
@@ -0,0 +1,142 @@
...
+  hmac_testutils_push_message(&hmac, manifest_end,
+                              signed_region_size - manifest_signed_region_size);
+
+  CHECK_DIF_OK(dif_hmac_process(&hmac));
+  dif_hmac_digest_t act_digest;
+  hmac_testutils_finish_polled(&hmac, &act_digest);
+
+  LOG_INFO("SHA256(static_critical.boot_measurements): 0x%!x",
+           sizeof(boot_measurements), &boot_measurements);
+  LOG_INFO("SHA256(actual digest): 0x%!x", sizeof(act_digest), &act_digest);
```
Comment (moidx) [inline sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:83]: nit: I'd remove these two as `CHECK_ARRAYS_EQ` will print the diff in there is a mismatch. It is not much but, it will improve performance in simulation a little bit.

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c [hunk 7]
```diff
@@ -0,0 +1,142 @@
...
+             }));
+
+  // Copy the part of the manifest that's in the signed region to
+  // memory before pushing to hmac since it's volatile.
+  // Note: this array is larger than `manifest_signed_region_size` since VLAs
+  // are optional in C11.
+  char manifest_signed_region[sizeof(manifest_t)];
+  for (size_t i = 0; i < manifest_signed_region_size; ++i) {
+    manifest_signed_region[i] =
+        *((const volatile char *)signed_region_start + i);
```
Comment (moidx) [inline sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:69]: Question: I didn't follow the comment above. Is this needed because of the way we are setting permissions in ePMP?

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c [hunk 8]
```diff
@@ -0,0 +1,142 @@
...
+    kRndOffset = 13,
+    kRomCheckValue = 6,
+  };
+
+  sec_mmio_check_values(kRndOffset);
+  sec_mmio_check_counters(kRomCheckValue + 1);
+}
+
+static bool exception_expected = false;
+static bool exception_observed = false;
```
Comment (moidx) [inline sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:99]: nit: just these be volatile because `ottr_exeception_handler` is accessing them? Or is that now old school :)

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c [hunk 9]
```diff
@@ -0,0 +1,142 @@
...
+      abort();
+  }
+}
+
+void sec_mmio_neg_test(void) {
+  exception_expected = true;
+  sec_mmio_check_counters(0);
+  CHECK(false, "Should not be here");
+
+  OT_ADDRESSABLE_LABEL(kSecMmioNegTestReturn);
```
Comment (moidx) [inline sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:133]: very neat.

**Review by moidx — APPROVED** [review]

File: sw/device/lib/dif/dif_hmac.c (hunk 4 above)
Comment (alphan) [reply sw/device/lib/dif/dif_hmac.c:253]: Thanks for catching this. It looks like we don't run the tests that use `kRefExpectedShaDigest` and `kRefExpectedHmacDigest` in the CI. I'll verify my changes in verilator because the test_rom bitstream seems to be broken because of the `gp` issue.

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c (hunk 6 above)
Comment (alphan) [reply sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:83]: I agree, done. I added those to diagnose the flipped read order in `dif_hmac`.

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c (hunk 7 above)
Comment (alphan) [reply sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:69]: This is needed because the manifest is declared as `volatile` in `manifest_def.c`. We need it because the rest of the fields are filled by the tooling but this means we can't use `memcpy` or our utility functions because none of them expect `volatile` pointers. Resolving this thread but PLMK if this is not clear and I can work on the wording.

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c (hunk 8 above)
Comment (alphan) [reply sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:99]: Thanks for catching this, yes these should be `volatile`.

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c (hunk 9 above)
Comment (alphan) [reply sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:133]: Thanks!

File: sw/device/lib/dif/dif_hmac.c (hunk 4 above)
Comment (alphan) [reply sw/device/lib/dif/dif_hmac.c:261]: I fixed the key word order as well and verified that `hmac_enc_test` and `hmac_enc_idle_test` pass locally.

File: sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c [hunk 10]
```diff
@@ -0,0 +1,136 @@
...
+
+  CHECK_DIF_OK(
+      dif_hmac_init(mmio_region_from_addr(TOP_EARLGREY_HMAC_BASE_ADDR), &hmac));
+  CHECK_DIF_OK(dif_hmac_mode_sha256_start(
+      &hmac, (dif_hmac_transaction_t){
+                 .digest_endianness = kDifHmacEndiannessLittle,
+                 .message_endianness = kDifHmacEndiannessLittle,
+             }));
+
+  // Copy the part of the manifest that's in the signed region to
```
Comment (alphan) [inline sw/device/silicon_creator/rom/e2e/rom_e2e_static_critical_test.c:59]: @luismarques

**Comment by alphan** [comment]
The error in SW build is fixed in #14682
