### PR TITLE
[top/dv] Adjust setup for floating pin.

### LINKED ISSUE #15536: [test-triage] chip_sw_rv_plic_smoketest
### Hierarchy of regression failure

Chip Level

### Failure Description

      Offending '(!$isunknown(depth_o))'
  UVM_ERROR @ 3155.528394 us: (prim_fifo_sync.sv:194) [ASSERT FAILED] DepthKnown_A
  UVM_INFO @ 3155.528394 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---

### Steps to Reproduce

- Commit hash:  https://github.com/lowrisc/opentitan/tree/84fdd3bf374f168367ba7ffcb07cfa4d79c54875
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_rv_plic_smoketest --fixed-seed 2400358183 --build-seed 2438508852 --waves -v h

### Tests with similar or related failures

_No response_

### PR DESCRIPTION
**Pull request by tjaychen**
- Previously, the test would enable the UART RX pins without a pull-up.  This meant that until the test bench environment actively drove, the pin was left floating and cause x propagation.

- This update just sets the pull-up at the same time as enabling the pin to ensure this situation does not come up.

fixes #15536 

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

File: sw/device/lib/testing/pinmux_testutils.c [hunk 1]
```diff
@@ -42,6 +42,21 @@ void pinmux_testutils_init(dif_pinmux_t *pinmux) {
   CHECK_DIF_OK(dif_pinmux_output_select(pinmux, kTopEarlgreyPinmuxMioOutIoc4,
                                         kTopEarlgreyPinmuxOutselUart0Tx));
 
+  // Enable pull-ups on UART0 TX/RX
+  dif_pinmux_pad_attr_t out_attr;
```
Comment (tjaychen) [inline sw/device/lib/testing/pinmux_testutils.c:46]: i need to double check the DIFs, but its feels like we should be able to pass NULL pointers for outputs hehe..if we don't care about it.

Comment (a-will) [reply sw/device/lib/testing/pinmux_testutils.c:46]: Either way is fine, but the DIFs generally want the callers to do something with all outputs. In this case, the output explains which attributes were actually accepted, so it's still kind of at the validation level.

However, it's arguable that this validation mechanism really doesn't need to be done at run time, that it ought to be a data sheet exercise only.

**Review by a-will — APPROVED** [review]

File: sw/device/lib/testing/pinmux_testutils.c [hunk 2]
```diff
@@ -42,6 +42,21 @@ void pinmux_testutils_init(dif_pinmux_t *pinmux) {
...
+  dif_pinmux_pad_attr_t in_attr = {
+      .slew_rate = 0,
+      .drive_strength = 0,
+      .flags = kDifPinmuxPadAttrPullResistorEnable |
+               kDifPinmuxPadAttrPullResistorUp};
+
+  CHECK_DIF_OK(dif_pinmux_pad_write_attrs(pinmux, kTopEarlgreyMuxedPadsIoc3,
```
Comment (a-will) [inline sw/device/lib/testing/pinmux_testutils.c:53]: FYI: It looks like top_englishbreakfast is missing these pad constants.

Comment (tjaychen) [reply sw/device/lib/testing/pinmux_testutils.c:53]: yeah this is super annoying.
I'm going to file an issue about the OTTF thing, but for now I'll probably need to lump it into the ifdef.

File: sw/device/lib/dif/dif_pinmux.c [hunk 3]
```diff
@@ -282,9 +282,9 @@ dif_result_t dif_pinmux_pad_write_attrs(const dif_pinmux_t *pinmux,
 
   uint32_t read_value = mmio_region_read32(pinmux->base_addr, reg_offset);
   *attrs_out = dif_pinmux_reg_to_pad_attr(read_value);
-  if (reg_value != read_value) {
-    return kDifError;
-  }
+  // if (reg_value != read_value) {
```
Comment (tjaychen) [inline sw/device/lib/dif/dif_pinmux.c:285]: @a-will / @timothytrippel i think removing this check altogether is probably the right thing to do.
The pads each have "allowable" attributes, so if you try to enable an attribute that does not belong to a particular pad, it just won't show up.

In fpga, there are actually no pull-ups, so when I try to enable it the readback fails and that's what causes the `sram_ctrl_execution_test` to eventually die.

Let me know if you agree, if yes I can just remove this. If not, I can file an issue to track a better fix in the future and temporarily remove it.

Comment (a-will) [reply sw/device/lib/dif/dif_pinmux.c:285]: Hm... this "quick fix" ended up being more hacky than we thought, haha. From a certain perspective, we actually want to check that impossible requests are caught, as they may be critical to the test's function.

Originally, this was a little workaround for an assertion in DV, right? Shall we just check that we are on the DV "device" and only apply it there? Then I can follow up later with removing the pull-up here and disabling RX by default in the UART.

Let me know what you both think!

Comment (tjaychen) [reply sw/device/lib/dif/dif_pinmux.c:285]: hmmm... i see your point about knowing we tried to set something that wasn't possible.
okay let me make this part only for DV.  I guess longer term, when we have these things come up, we'll want to make them platform specific anyways.

Comment (tjaychen) [reply sw/device/lib/dif/dif_pinmux.c:285]: i actually had another PR pending that removed RX from test_rom and over to ottf, but that encountered some other kind of failure that i had not looked into, i'll table that for another PR.

Comment (tjaychen) [reply sw/device/lib/dif/dif_pinmux.c]: alright! updated and tests are (hopefully) passing.

Comment (a-will) [reply sw/device/lib/dif/dif_pinmux.c]: > Just to make sure, do you mean enable pull-up only on DV? But eventually we will probably have other portable code that enables pull-ups right? Ie, code that runs on both asic and fpga platforms. How would we want to handle those?

Yup, enable in DV only. Keep in mind that code that requires us to turn on internal pull-ups is _not_ portable across the ASIC and FPGA platforms. The FPGA does not support them.
 
> My original thinking was to move the attribute check out of the DIF and into the DIF caller, and have the DIF caller be responsible for the differences.

My thoughts there:
Because we must be enabling the pull-ups for a reason, it's best for us to ensure the lack of support is checked. It's easier to make that guarantee if the check is in the DIFs. If there is a reason the ASIC needs them enabled that is specific to the ASIC, then we can check against the device type and act accordingly.

**Review by a-will — APPROVED** [review]
I think we'll change this to not actually map an RX pin for UART later (in addition to disabling the RX function in UART by default), but as a workaround for now, this LGTM.

**Comment by tjaychen** [comment]
thanks! i'm going to merge for now. The kokoro failure is a bit..out of left field, but there's no change here that would actually impact lint results.

**Review by alphan — APPROVED** [review]
