### PR TITLE
[sival, rv_dm] add sival test for testing RV_DM JTAG

### LINKED ISSUE #19884: [chip-level,si-val] chip_sw_rv_dm_jtag_tap_sel
### Test point name

[chip_sw_rv_dm_jtag_tap_sel](https://github.com/lowRISC/opentitan/blob/cf8ffa811189c6c17285abae7eef19081213f739/hw/top_earlgrey/data/chip_testplan.hjson#L499)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

@GregAC 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] update test name link when ##19749 is merged
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
   - [ ] existing test `chip_tap_straps_rma` is DV-only and only covers RMA
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 1

### LINKED ISSUE #19886: chip-level,si-val] chip_rv_dm_jtag
### Test point name

chip_rv_dm_jtag

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

@GregAC 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] update test name link when ##19749 is merged
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 2

### PR DESCRIPTION
**Pull request by nbdd0121**
Fix #19884
Fix #19886

### CODE REVIEW

File: sw/device/tests/BUILD [hunk 1]
```diff
@@ -3033,6 +3033,167 @@ opentitan_test(
...
+)
+
+[
+    opentitan_test(
+        name = "rv_dm_jtag_{}".format(lc_state),
+        srcs = ["example_test_from_flash.c"],
+        cw310 = cw310_jtag_params(
+            otp = "//hw/ip/otp_ctrl/data:img_{}".format(lc_state),
+            tags = [
+                "fpga_cw310_sival",
```
Comment (a-will) [inline sw/device/tests/BUILD:3049]: Hm... It looks like none of these tests are actually running in CI. "fpga_cw310_sival" is not one of the tags the jobs look for, and these tests have none of the ones they do:

- Test ROM tests: "cw310_test_rom"
- ROM tests: "cw310_rom_with_fake_keys", "cw310_rom_with_real_keys"
- Manufacturing tests: "manuf"

We probably need to figure out how we want these tests to work with CI and tag filtering. Should this get any tag other than "cw310_rom_with_fake_keys"?

Comment (a-will) [reply sw/device/tests/BUILD:3049]: @cfrantz @moidx @timothytrippel ^ (for some possibly interested parties)

File: sw/host/tests/chip/rv_dm/src/jtag_tap_sel.rs [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+                .unwrap()
+                .as_str(),
+            16,
+        )?)
+    };
+
+    if let Some(idcode) = idcode {
+        assert_ne!(idcode, RISCV_IDCODE);
+        assert_ne!(idcode, LC_IDCODE);
+    }
```
[the remark this answers is not in the document]
Comment (a-will) [reply sw/host/tests/chip/rv_dm/src/jtag_tap_sel.rs:95]: I feel like this might be a little too loose for real silicon (and unexpectedly not trigger failure on getting no response from any TAP). It seems fine for the FPGA, though! There's no TAP there, so anything that isn't the known IDCODE values seems fine. Technically, it should really be a case of all ones if we're properly pulling up on TDO, but I'm not sure whether the Olimex adapter is doing so.

Would it make sense to you to add an optional argument that, when set (to a DFT IDCODE), would check that the received `idcode` actually matches? Then for the later build with real silicon, we could fill it in for that target.

[the remark this answers is not in the document]
Comment (nbdd0121) [reply sw/host/tests/chip/rv_dm/src/jtag_tap_sel.rs:95]: > case of all ones

OpenOCD handles all one case specially and gives you "JTAG scan chain interrogation failed"

File: sw/device/tests/BUILD (hunk 1 above)
Comment (nbdd0121) [reply sw/device/tests/BUILD:3049]: I followed #20402. Should we update the CI to include the fpga_cw310_sival tag?

File: sw/host/tests/chip/rv_dm/src/jtag_tap_sel.rs (hunk 2 above)
[the remark this answers is not in the document]
Comment (nbdd0121) [reply sw/host/tests/chip/rv_dm/src/jtag_tap_sel.rs]: I've updated the test to accept an optional `--dft-idcode=0x<IDCODE>`. If not specified, then it checks for non-existence of DFT TAP.

File: sw/host/tests/chip/rv_dm/src/jtag_tap_sel.rs [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+    transport.pin_strapping("PINMUX_TAP_DFT")?.apply()?;
+    transport.reset_target(opts.init.bootstrap.options.reset_delay, true)?;
+
+    // For DFT test we need to do raw OpenOCD command.
+    let mut openocd = opts.init.jtag_params.create(transport)?.into_raw()?;
+    // Perform JTAG initialisation and capture the result.
+    let init_result = openocd.execute("capture \"jtag init\"")?;
+
+    static ID_REGEX: Lazy<Regex> =
+        Lazy::new(|| Regex::new(r"tap/device found: 0x([0-9A-Fa-f]+) \(").unwrap());
```
Comment (engdoreis) [inline sw/host/tests/chip/rv_dm/src/jtag_tap_sel.rs:78]: Maybe:
```suggestion
        Lazy::new(|| Regex::new(r"tap/device found: 0x([0-9A-Fa-f]{1,8}) \(").unwrap());
```

File: sw/host/tests/chip/rv_dm/src/jtag.rs [hunk 4]
```diff
@@ -0,0 +1,92 @@
...
+fn test_jtag(opts: &Opts, transport: &TransportWrapper) -> Result<()> {
+    // Avoid watchdog timeout by entering bootstrap mode.
+    transport.pin_strapping("ROM_BOOTSTRAP")?.apply()?;
+
+    transport.pin_strapping("PINMUX_TAP_RISCV")?.apply()?;
+    transport.reset_target(opts.init.bootstrap.options.reset_delay, true)?;
+
+    let mut openocd = opts.init.jtag_params.create(transport)?.into_raw()?;
+
+    assert_eq!(
```
Comment (engdoreis) [inline sw/host/tests/chip/rv_dm/src/jtag.rs:30]: Can you add a comment explaining what the command below does?

**Review by engdoreis — APPROVED** [review]
I'm not very familiar with RV_DM, but the code LGTM.

**Review by pamaury — APPROVED** [review]
