### PR TITLE
[sw/silicon_creator] Fix OTBN sec_mmio regression

### LINKED ISSUE #16916: [e2e] Test regression: sigverify_mod_exp_rma_otbn_fpga_cw310_rom
Steps to reproduce:
```
git checkout 3894081bc2102de8ec467075d8532de985e9c0c8
./bazelisk.sh test //sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom
```

Bisect command:
```
/bazelisk.sh run //util/fpga:bitstream_bisect -- --good 09bd12891a50bca984e7cd8f4c2aadc99e6eb93e --bad 2f112c50d9ed8d9e25c9876b26eb57a76651e96e --fast-command './bazelisk.sh test //sw/device/silicon_creator/
rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom'
```

Relevant output from bisecting: 
```
The first bad commit could be any of:
24053071ebf8a7f3c8971b4d7f6b6a7089cb3181
1fb7299bb6266a44eb48d86ed7cd75c37faa9546
256bf762af20c9f612891362e34e46b76336bf76
2f112c50d9ed8d9e25c9876b26eb57a76651e96e
We cannot bisect more!
```

I'm pretty sure we can exonerate all but one: 

* ~~24053071ebf8a7f3c8971b4d7f6b6a7089cb3181~~ only touches doc/
* ~~1fb7299bb6266a44eb48d86ed7cd75c37faa9546~~ only touches util/dvsim/
* ~~256bf762af20c9f612891362e34e46b76336bf76 touches hw/ip/i2c/{data,dv}~~ (**Edit**: per discussion with @jdonjdon, this commit is now exonerated, too.)
* ~~2f112c50d9ed8d9e25c9876b26eb57a76651e96e~~ only touches ci/azure-pipelines-nightly.yml

@jdonjdon Is it plausible that 256bf762af20c9f612891362e34e46b76336bf76 caused this test regression? It doesn't really make sense to me since it looks like the commit only changes dv-related code and the regression is a functest.

FYI @alphan, since I think you're the author of the test.

### PR DESCRIPTION
**Pull request by alphan**
This commit corrects the value of the `kOtbnSecMmioExecute` constant and adds a missing `SEC_MMIO_WRITE_INCREMENT()` after the `otbn_execute()` call in `mod_exp_otbn.c`.

Fixes #16916

Signed-off-by: Alphan Ulusoy <alphan@google.com>

### CODE REVIEW

**Comment by alphan** [comment]
```
$ bazel test -t- --define bitstream=gcp_splice //sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom
INFO: Invocation ID: 4c3efc42-4420-4fef-a8dd-ab94c5594379
INFO: Analyzed target //sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom (0 packages loaded, 186 targets configured).
INFO: Found 1 test target...
Aspect @rules_rust//rust/private:clippy.bzl%rust_clippy_aspect of //sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom up-to-date (nothing to build)
INFO: Elapsed time: 2.133s, Critical Path: 1.75s
INFO: 2 processes: 2 local.
INFO: Build completed successfully, 2 total actions
//sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom PASSED in 1.7s

INFO: Build completed successfully, 2 total actions
```

**Review by timothytrippel — APPROVED** [review]

File: sw/device/silicon_creator/lib/drivers/otbn.h [hunk 1]
```diff
@@ -33,11 +33,11 @@ enum {
  * Example:
  * ```
  *  otbn_execute();
- *  SEC_MMIO_WRITE_INCREMENT(kOtbnSecMMioExecute);
+ *  SEC_MMIO_WRITE_INCREMENT(kOtbnSecMmioExecute);
  * ```
  */
 enum {
-  kOtbnSecMmioExecute = 2,
+  kOtbnSecMmioExecute = 1,
```
Comment (dmcardle) [inline sw/device/silicon_creator/lib/drivers/otbn.h:40]: For my understanding, this now matches the singular sec_mmio write in otbn_execute()'s implementation, right?

https://cs.opensource.google/opentitan/opentitan/+/master:sw/device/silicon_creator/lib/drivers/otbn.c;l=170;drc=b9d0fb5c3cbaaf848c10f06c870a5cd0cb304599

**Review by dmcardle — APPROVED** [review]
LGTM! Thanks for figuring this out, @alphan!

File: sw/device/silicon_creator/lib/drivers/otbn.h (hunk 1 above)
Comment (alphan) [reply sw/device/silicon_creator/lib/drivers/otbn.h:40]: Correct!

**Comment by alphan** [comment]
I was curious if this would happen, CI fails with the fix. It seems like it's lagging and is not properly splicing ROM for the current run.

**Comment by alphan** [comment]
I'll go ahead and merge this because it looks like there is a problem in the CI and I cannot reproduce the failure locally:
```
$ bazel run //sw/host/opentitantool -- fpga clear-bitstream
INFO: Invocation ID: 9d5fa25a-e249-4383-9b07-2d9a34472e7a
INFO: Analyzed target //sw/host/opentitantool:opentitantool (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
Aspect @rules_rust//rust/private:clippy.bzl%rust_clippy_aspect of //sw/host/opentitantool:opentitantool up-to-date (nothing to build)
INFO: Elapsed time: 0.301s, Critical Path: 0.03s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action

$ bazel test -t- --define bitstream=gcp_splice //sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom
INFO: Invocation ID: 302b3b55-e871-4f17-bcd1-460c372ea3cc
INFO: Build option --define has changed, discarding analysis cache.
INFO: Analyzed target //sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom (0 packages loaded, 14529 targets configured).
INFO: Found 1 test target...
Aspect @rules_rust//rust/private:clippy.bzl%rust_clippy_aspect of //sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom up-to-date (nothing to build)
INFO: Elapsed time: 20.255s, Critical Path: 19.28s
INFO: 2 processes: 2 local.
INFO: Build completed successfully, 2 total actions
//sw/device/silicon_creator/rom/e2e:sigverify_mod_exp_rma_otbn_fpga_cw310_rom PASSED in 19.2s

INFO: Build completed successfully, 2 total actions
```
