### PR TITLE
[sival, rv_dm] implement rv_dm_csr_rw and rv_dm_mem_access

### LINKED ISSUE #19877: [chip-test,si-val] chip_jtag_csr_rw
### Test point name

[chip_jtag_csr_rw](https://github.com/lowRISC/opentitan/blob/cf8ffa811189c6c17285abae7eef19081213f739/hw/top_earlgrey/data/chip_testplan.hjson#L389)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

@GregAC 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] update test name link when ##19749 is merged
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
   - [ ] existing tests `chip_jtag_csr_rw` is DV-only
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate X

### LINKED ISSUE #19878: [chip-test,si-val] chip_jtag_mem_access
### Test point name

[chip_jtag_mem_access](https://github.com/lowRISC/opentitan/blob/cf8ffa811189c6c17285abae7eef19081213f739/hw/top_earlgrey/data/chip_testplan.hjson#L404C13-L404C33)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

@GregAC 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] update test name link when ##19749 is merged
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
   - [ ] existing tests `chip_jtag_mem_access` is DV-only
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 1

### PR DESCRIPTION
**Pull request by nbdd0121**
Fix #19877
Fix #19878

### CODE REVIEW

File: sw/device/tests/BUILD [hunk 1]
```diff
@@ -4101,6 +4101,37 @@ _RV_DM_JTAG_LC_STATES = get_lc_items(
...
 )
 
+[
+    opentitan_test(
+        name = "rv_dm_csr_rw_{}".format(lc_state),
+        srcs = ["example_test_from_flash.c"],
+        cw310 = hyper310_jtag_params(
+            otp = _SIVAL_OTP_IMAGE[lc_state],
+            tags = [
+                "lc_{}".format(lc_state),
```
Comment (pamaury) [inline sw/device/tests/BUILD:4111]: is this tag used? I don't think we consistently tag lc states

**Review by pamaury — APPROVED** [review]

File: sw/device/tests/BUILD (hunk 1 above)
Comment (nbdd0121) [reply sw/device/tests/BUILD:4111]: I was following flash_ctrl_rma_test which I think was the example sival test in Miguel's PR. But apparently nobody else has added the tag to their tests. Do you want me to remove the tag?

Comment (pamaury) [reply sw/device/tests/BUILD:4111]: I think the tags are just used to inconsistently to be useful I guess it does not hurt to have them

File: sw/host/tests/chip/rv_dm/src/mem_access.rs [hunk 2]
```diff
@@ -0,0 +1,129 @@
...
+        ),
+        (
+            "otbn_dmem",
+            top_earlgrey::OTBN_BASE_ADDR as u32 + dif::OTBN_DMEM_REG_OFFSET,
+            dif::OTBN_DMEM_SIZE_BYTES,
+        ),
+    ];
+
+    // Randomly generate accesses.
+    let mut rng = thread_rng();
```
Comment (engdoreis) [inline sw/host/tests/chip/rv_dm/src/mem_access.rs:71]: Can you use a seed and print it every run so that we can reproduce CI failures locally? 
We can also add an optional argument for the seed and then generated a randon seed only if not provided.

**Review by engdoreis — COMMENTED** [review]
LGTM, but I left a comment below.

File: sw/host/tests/chip/rv_dm/src/mem_access.rs (hunk 2 above)
Comment (pamaury) [reply sw/host/tests/chip/rv_dm/src/mem_access.rs:71]: Printing the seed sounds like a good idea, otherwise it's hard to reproduce failures

**Review by engdoreis — APPROVED** [review]

**Comment by jwnrt** [comment]
The `spi_device_flash_smoketest` failure is unrelated.

**Comment by a-will** [comment]
But the verilated english breakfast failure _does_ seem to be related.

**Comment by jwnrt** [comment]
Sorry, I missed that verilated build error. Is it caused by this PR? Do we need to revert?

**Comment by nbdd0121** [comment]
Sorry, I wasn't aware that we build English breakfast software by patching the earlgrey. I'll look into it to see if I can produce a forward fix today.
