### PR TITLE
Many cw310 tests

### LINKED ISSUE #13044: [ci] Restore CW310 test coverage after the FPGA tests are made reliable
The communication with the CW310 board in CI fails intermittently. To mitigate this problem, I've configured CI to run a subset of tests (the original subset run by systemtest before it was replaced by Bazel). After these tests are made reliable, the full suite of CW310 tests should be restored and the `--notest_keep_going` and `--nokeep_going` flags should be removed.

### PR DESCRIPTION
**Pull request by drewmacrae**
Now that the cw310 can reboot after failing tests we can run a lot more tests. This also cleans up the test rom identification so tests take ~2s instead of ~20s.

Fixes #13044

### CODE REVIEW

**Comment by drewmacrae** [comment]
The log for this shows the reboot script acting after a failure when some of these tests fail (due to known issues that haven't yet been marked in BUILD files)
```2022-06-11T04:19:24.2033627Z //sw/device/tests:clkmgr_off_hmac_trans_test_fpga_cw310                  FAILED in 2.4s
2022-06-11T04:19:24.2035018Z   /root/.cache/bazel/_bazel_root/5e4f8c833cf3a422fdf6ca333dd151d7/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/testlogs/sw/device/tests/clkmgr_off_hmac_trans_test_fpga_cw310/test.log
2022-06-11T04:19:24.2035709Z 
2022-06-11T04:19:24.2036222Z Executed 19 out of 142 tests: 18 tests pass, 1 fails locally and 123 were skipped.
2022-06-11T04:19:24.2037301Z There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
2022-06-11T04:19:24.2195105Z 
2022-06-11T04:19:24.2196303Z (04:19:24) INFO: Build completed, 1 test FAILED, 2123 total actions
2022-06-11T04:19:24.2285298Z + python3 ./util/fpga/cw310_reboot.py
2022-06-11T04:19:24.3903803Z Found CW310 with FW Version: 0.40.1
2022-06-11T04:19:24.4089083Z ##[error]Bash exited with code '3'.```

**Comment by drewmacrae** [comment]
Subsequent run succeeded before jake was reset at 5 AM I think

**Comment by drewmacrae** [comment]
The important part of the rust changes is that we wait longer before looking at the reported test rom. It looks like the message was getting truncated by reading before it had been communicated (This was made worse by the slower bazel built test-rom.)

File: sw/host/opentitanlib/src/transport/cw310/mod.rs [hunk 1]
```diff
@@ -200,18 +200,21 @@ impl Transport for CW310 {
                 let reset_pin = self.gpio_pin(Self::PIN_SRST)?;
                 // Reset is active low, sleep, then drive high.
                 reset_pin.write(false)?;
+                let uart = self.uart("0")?;
                 std::thread::sleep(fpga_program.rom_reset_pulse);
                 reset_pin.write(true)?;
-
+                std::thread::sleep(fpga_program.rom_reset_pulse);
```
[the remark this answers is not in the document]
Comment (drewmacrae) [reply sw/host/opentitanlib/src/transport/cw310/mod.rs:206]: I think the change to the detection timeout is insufficient and may be irrelevant. I think the detection is ending prematurely, not timing out. Changing the timeout didn't have an effect.

[the remark this answers is not in the document]
Comment (drewmacrae) [reply sw/host/opentitanlib/src/transport/cw310/mod.rs:206]: I don't like that the timing of this is arbitrary, but I couldn't figure out where it was intended to wait until the Test ROM ID was available to check and correct the logic.

File: sw/host/opentitanlib/src/transport/cw310/mod.rs [hunk 2]
```diff
@@ -184,8 +184,8 @@ impl Transport for CW310 {
         if let Some(fpga_program) = action.downcast_ref::<FpgaProgram>() {
             // Open the console UART.  We do this first so we get the receiver
             // started and the uart buffering data for us.
-            let uart = self.uart("0")?;
             if fpga_program.bitstream.starts_with(b"__skip__") {
+                let uart = self.uart("0")?;
```
[the remark this answers is not in the document]
Comment (drewmacrae) [reply sw/host/opentitanlib/src/transport/cw310/mod.rs:188]: Afraid to say, I'm not fluent enough in rust to find it. I don't know if this part of this PR is necessary so I can see if the issue is fixed by #13127 and then if not if it's fixed by rebasing this PR onto it, and finally if I can drop this without reintroducing the problem.

File: sw/host/opentitantool/src/command/load_bitstream.rs [hunk 3]
```diff
@@ -30,7 +30,7 @@ pub struct LoadBitstream {
     pub rom_kind: Option<RomKind>,
     #[structopt(long, parse(try_from_str=humantime::parse_duration), default_value="50ms", help = "Duration of the reset pulse.")]
     pub rom_reset_pulse: Duration,
-    #[structopt(long, parse(try_from_str=humantime::parse_duration), default_value="1s", help = "Duration of ROM detection timeout")]
+    #[structopt(long, parse(try_from_str=humantime::parse_duration), default_value="2s", help = "Duration of ROM detection timeout")]
```
Comment (drewmacrae) [inline sw/host/opentitantool/src/command/load_bitstream.rs:33]: The timeout here appears to be necessary and insufficient to fix the issue on it's own, Without an increased timeout threshold We can see tests fail as I make these other changes.

Comment (drewmacrae) [reply sw/host/opentitantool/src/command/load_bitstream.rs:33]: Without a 2s timeout:
```
//sw/device/tests:clkmgr_smoketest_fpga_cw310                            FAILED in 3.8s
  /usr/local/google/home/drewmacrae/.cache/bazel/_bazel_drewmacrae/eb3e804793dbbd45e50210cd3a3f84f1/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/testlogs/sw/device/tests/clkmgr_smoketest_fpga_cw310/test.log
//sw/device/tests:rstmgr_sw_req_test_fpga_cw310                          FAILED in 3.7s
  /usr/local/google/home/drewmacrae/.cache/bazel/_bazel_drewmacrae/eb3e804793dbbd45e50210cd3a3f84f1/execroot/lowrisc_opentitan/bazel-out/k8-fastbuild/testlogs/sw/device/tests/rstmgr_sw_req_test_fpga_cw310/test.log

Executed 137 out of 137 tests: 135 tests pass and 2 fail locally.
```

Comment (drewmacrae) [reply sw/host/opentitantool/src/command/load_bitstream.rs:33]: I've created https://github.com/lowRISC/opentitan/issues/13195 to track that issue, because I'm not sure if it represents a way for our CI to get stuck on a bad bitstream.

Comment (drewmacrae) [reply sw/host/opentitantool/src/command/load_bitstream.rs:33]: I can still hit it with bazel test --test_tag_filters=cw310,-broken --build_tests_only //... --runs_per_test=2 --runs_per_test_detects_flakes if I set the timeout to 1s

File: sw/host/opentitanlib/src/transport/cw310/mod.rs (hunk 1 above)
[the remark this answers is not in the document]
Comment (drewmacrae) [reply sw/host/opentitanlib/src/transport/cw310/mod.rs:206]: With the delay: 
```
[2022-06-13T22:14:53Z INFO  opentitanlib::util::rom_detect] detect exit=ExitSuccess, duration=22.740625ms
[2022-06-13T22:14:53Z INFO  opentitanlib::util::rom_detect] Current bitstream: "TestROM:6b2d2402"
```
Without the delay we see:
```
[2022-06-13T22:18:01Z INFO  opentitanlib::util::rom_detect] detect exit=ExitSuccess, duration=33.536449ms
[2022-06-13T22:18:01Z INFO  opentitanlib::util::rom_detect] Current bitstream: "TestROM:6b2d24"
```
It looks like the end of the message just hasn't made it to the buffer yet and it's being read and then the truncated version is mismatching. The read should either wait for all 32 bytes of the testROM, some kind of termination or shouldn't be run until the result is ready.

**Review by milesdai — APPROVED** [review]
LGTM wrt to the FPGA tests

File: ci/scripts/run-fpga-cw310-tests.sh [hunk 4]
```diff
@@ -23,50 +23,12 @@ export BITSTREAM="--offline --list ${SHA}"
 # in case we've crashed the UART handler on the CW310's SAM3U
 trap 'python3 ./util/fpga/cw310_reboot.py' EXIT
 
-# TODO: remove the --notest_keep_going and --nokeep_going flag after the CW310
-# tests are reliable (#13044)
 ci/bazelisk.sh test \
     --define DISABLE_VERILATOR_BUILD=true \
-    --notest_keep_going \
     --nokeep_going \
```
Comment (alphan) [inline ci/scripts/run-fpga-cw310-tests.sh:28]: nit: the comment also mentions this flag, should this be removed too?

**Review by alphan — APPROVED** [review]

**Review by cfrantz — APPROVED** [review]
