### PR TITLE
[chip dv] Fix plic_all_irqs_test for Verilator

### LINKED ISSUE #8656: [sw,plic irq test] Enable the autogen'ed PLIC IRQ test on Verilator and FPGA
This test is auto-generated by `topgen`. It resides here: `sw/device/tests/autogen/plic_all_irqs_test.c`. It is already enabled and passing in DV. Since it touches (almost) all blocks, it will serve as a pretty good smoke test to run in CI.

I tried running it locally but it unfortunately fails on Verilator. 
```
IE00000 plic_all_irqs_test.c:154] CHECK-fail: Interrupt from incorrect peripheral: exp = 16, obs = 1
I00001 test_status.c:34] FAIL!
```

This basically means on the the Verilator build, some IP is generating a spurious interrupt that the test does not expect. 

Hoping someone with spare cycles can debug this and get it working on Verilator. 

```bash
$ cd $REPO_TOP
$ fusesoc --cores-root . run --flag=fileset_top --target=sim --setup --build lowrisc:dv:chip_verilator_sim
$ ./meson_init.sh
$ ninja -C build-out/ all
$ ./build/lowrisc_dv_chip_verilator_sim_0.1/sim-verilator/Vchip_sim_tb -meminit=rom,build-bin/sw/device/boot_rom/boot_rom_sim_verilator.scr.39.vmem --meminit=otp,build-bin/sw/device/otp_img/otp_img_sim_verilator.vmem --meminit=flash,build-bin/sw/device/tests/plic_all_irqs_test_sim_verilator
```

### PR DESCRIPTION
**Pull request by sriyerg**
...and FPGA.

The logging mechanism which uses UART0 in Verilator and FPGA setups
messes up this test, which is meant to enable and test ALL interrupts
from all peripherals in the device, including UART0. The fix is to skip
testing UART0 interrupts for Verilator and FPGA.

Fixes #8656.

Signed-off-by: Srikrishna Iyer <sriyer@google.com>

### CODE REVIEW

File: util/topgen/templates/plic_all_irqs_test.c.tpl [hunk 1]
```diff
@@ -146,8 +146,20 @@ static void peripheral_irqs_enable(void) {
...
-  CHECK_DIF_OK(
-      dif_${p.name}_irq_restore_all(${args(p)}, &${p.name}_irqs));
+<%
+  indent = ""
+%>\
+  % if p.inst_name == "uart0":
+<%
+  indent = "  "
+%>\
+  if (kDeviceType == kDeviceSimDV) {
```
Comment (mundaym) [inline util/topgen/templates/plic_all_irqs_test.c.tpl:156]: Can you add a brief comment to the templates saying something like 'skip UART0 tests on Verilator and FPGA platforms since they interfere with test output'?

**Review by mundaym — APPROVED** [review]

File: util/topgen/templates/plic_all_irqs_test.c.tpl (hunk 1 above)
Comment (sriyerg) [reply util/topgen/templates/plic_all_irqs_test.c.tpl:158]: Done, thanks.
