### PR TITLE
[top/dv] Slightly restructure clkmgr_escalate_reset_test

### LINKED ISSUE #15533: [test-triage] chip_sw_clkmgr_escalation_reset
### Hierarchy of regression failure

Chip Level

### Failure Description

  UVM_ERROR @ 3383.073776 us: (cip_base_scoreboard.sv:436) [uvm_test_top.env.scoreboard] Check failed item.d_error == exp_d_error (1 [0x1] vs 0 [0x0]) On interface chip_reg_block, TL item: req: (cip_tl_seq_item@140559) { a_addr: 'h1001fe7c  a_data: 'h0  a_mask: 'hf  a_size: 'h2  a_param: 'h0  a_source: 'h1  a_opcode: 'h4  a_user: 'h272aa  d_param: 'h0  d_source: 'h1  d_data: 'hffffffff  d_size: 'h2  d_opcode: 'h1  d_error: 'h1  d_sink: 'h0  d_user: 'heaa  a_source_is_overridden: 'h0  a_valid_delay: 'h0  d_valid_delay: 'h0  a_valid_len: 'h0  d_valid_len: 'h0  req_abort_after_a_valid_len: 'h0  rsp_abort_after_d_valid_len: 'h0  req_completed: 'h0  rsp_completed: 'h0  tl_intg_err_type: TlIntgErrNone  max_ecc_errors: 'h3  }
  , unmapped_err: 0, mem_access_err: 0, bus_intg_err: 0, byte_wr_err: 0, csr_size_err: 0, tl_item_err: 0, write_w_instr_type_err: 0, cfg.tl_mem_access_gated: 0 ecc_err: 0
  UVM_INFO @ 3383.073776 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---

### Steps to Reproduce

- Commit hash: https://github.com/lowrisc/opentitan/tree/84fdd3bf374f168367ba7ffcb07cfa4d79c54875
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_clkmgr_escalation_reset --fixed-seed 4097340474 --build-seed 2438508852 --waves -v h

### Tests with similar or related failures

_No response_

### PR DESCRIPTION
**Pull request by tjaychen**
- Previously, the test would inject a fatal alert and wait
  for the alert to happen. However, the injected alert
  would cause an escalation and as a result accesses to
  the sram and flash would begin to error.
- The processor would create these errors because it used a
  busy loop to wait out the expected time for escalation to
  trigger.

- In this test, drop the busy loop altogether since the watchdog
  already serves the same function.
- Also disable the classA interrupt after seeing it for the first time,
  since the fatal alert effectively causes an interrupt storm that
  triggers again and again.

fixes #15533

### CODE REVIEW

**Comment by tjaychen** [comment]
@matutem pointed out we could just remove the busy loop altogether, since it's function is duplicated.
Let me do that.

File: sw/device/tests/sim_dv/clkmgr_escalation_reset_test.c [hunk 1]
```diff
@@ -204,6 +210,8 @@ static void execute_test(dif_aon_timer_t *aon_timer) {
       aon_timer_testutils_get_aon_cycles_from_us(kWdogBarkMicros);
   uint32_t bite_cycles =
       aon_timer_testutils_get_aon_cycles_from_us(kWdogBiteMicros);
+  uint32_t wake_cycles =
```
Comment (matutem) [inline sw/device/tests/sim_dv/clkmgr_escalation_reset_test.c:213]: This variable seems to be unused.

File: sw/device/tests/sim_dv/clkmgr_escalation_reset_test.c [hunk 2]
```diff
@@ -216,11 +224,7 @@ static void execute_test(dif_aon_timer_t *aon_timer) {
 
   // Trigger the clkmgr fatal error to start escalation.
   LOG_INFO("Ready for error injection");
-
-  busy_spin_micros(kEscalationPhase0MicrosCpu);
-
-  // This should never run since escalation turns the CPU off.
-  CHECK(false, "The alert handler failed to escalate");
+  abort();
```
[the remark this answers is not in the document]
Comment (tjaychen) [reply sw/device/tests/sim_dv/clkmgr_escalation_reset_test.c:227]: o yeah i know. But if you look at it, it's actually just a while loop with wait for interrupt. It was recommended by Sri in a different PR.

File: sw/device/tests/sim_dv/clkmgr_escalation_reset_test.c (hunk 1 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/clkmgr_escalation_reset_test.c:213]: ah yes i forgot to remove this.

Comment (tjaychen) [reply sw/device/tests/sim_dv/clkmgr_escalation_reset_test.c]: removed

**Review by cindychip — APPROVED** [review]

**Comment by tjaychen** [comment]
@matutem , @cindychip and I clarified the interrupt disable issue in #15629 , so this test should be good to go in now.
Thanks everyone for the review.
