### PR TITLE
[chip-test/sival] Add EDN auto mode test

### LINKED ISSUE #20048: [chip-test,si-val ] chip_sw_edn_auto_mode
### Test point name

[chip_sw_edn_auto_mode](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_edn_testplan.hjson)

### Host side component

None Required

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [ ] Hyperdebug + CW310

### Contact person

@vogelpi @h-filali

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [x] Host-side component developed: *none required*
- [x] HJSON test plan updated with test name (so it shows up in the dashboard): *testpoint exists in test plan*
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

### PR DESCRIPTION
**Pull request by h-filali**
This PR adds the EDN auto mode test for chip level sival.
For further details, see the commit messages.
This PR resolves #20048.

### CODE REVIEW

**Comment by h-filali** [comment]
I ran the test on Verilator and it completes after around 6400 seconds.
We may play around with the parameters OTBN_ROUNDS, OTBN_RANDOMNESS_ITERATIONS, and TEST_PROCEDURE_REPETITIONS to shorten this time, but I don't know how much we could gain there (probably not a lot).

Also please only consider the last few commits when reviewing. The others already have been covered in  [#20022](https://github.com/lowRISC/opentitan/pull/20022).

FYI: @andreaskurth @vogelpi

File: sw/device/lib/crypto/drivers/entropy_test.c [hunk 1]
```diff
@@ -28,7 +28,7 @@ static status_t entropy_complex_init_test(void) {
   dif_otbn_t otbn;
   TRY_CHECK(dif_otbn_init(mmio_region_from_addr(TOP_EARLGREY_OTBN_BASE_ADDR),
                           &otbn) == kDifOk);
-  otbn_randomness_test_start(&otbn);
+  otbn_randomness_test_start(&otbn, 0);
```
Comment (moidx) [inline sw/device/lib/crypto/drivers/entropy_test.c:31]: nit to follow style guide:

```c
otbn_randomness_test_start(&otbn, /*iters=*/0);
```

File: sw/device/tests/csrng_edn_concurrency_test.c [hunk 2]
```diff
@@ -157,7 +157,7 @@ static void otbn_task(void *task_parameters) {
     }
     LOG_INFO("OTBN:START");
     for (size_t i = 0; i < task_iter_count_max[kTestTaskIdOtbn]; ++i) {
-      otbn_randomness_test_start(&otbn);
+      otbn_randomness_test_start(&otbn, 0);
```
Comment (moidx) [inline sw/device/tests/csrng_edn_concurrency_test.c:160]: nit to follow style guide:

```c
otbn_randomness_test_start(&otbn, /*iters=*/0);
```

File: sw/device/tests/edn_auto_mode.c [hunk 3]
```diff
@@ -0,0 +1,141 @@
...
+#include "sw/device/lib/testing/test_framework/ottf_main.h"
+#include "sw/device/tests/otbn_randomness_impl.h"
+
+#include "edn_regs.h"  // Generated
+#include "hw/top_earlgrey/sw/autogen/top_earlgrey.h"
+
+#define TIMEOUT (10 * 1000 * 1000)
+#define OTBN_ROUNDS 1
+#define OTBN_RANDOMNESS_ITERATIONS 10
+#define TEST_PROCEDURE_REPETITIONS 2
```
Comment (moidx) [inline sw/device/tests/edn_auto_mode.c:30]: To follow the style guide, all these constants should be defined as enums:

```c
enum {
  kTimeout = (10 * 1000 * 1000),
  kOtbnRounds = 1, 
  ...
};
```

The rationale for this is documented in the c/c++ style guide.

File: sw/device/tests/edn_auto_mode.c [hunk 4]
```diff
@@ -0,0 +1,141 @@
...
+    CHECK_DIF_OK(dif_otbn_get_status(&otbn, &otbn_status));
+    if (otbn_status == kDifOtbnStatusIdle) {
+      configure_otbn();
+      otbn_execute_rounds--;
+    }
+    if (aes_testutils_get_status(&aes, kDifAesStatusOutputValid))
+      CHECK_STATUS_OK(aes_testutils_setup_encryption(transaction, &aes));
+
+    CHECK_DIF_OK(
+        dif_rv_core_ibex_get_rnd_status(&rv_core_ibex, &ibex_rnd_status));
```
Comment (moidx) [inline sw/device/tests/edn_auto_mode.c:108]: The build in CI was not able to find this symbol.

**Review by moidx — COMMENTED** [review]
Hi @h-filali, looks good so far! 

I added some comments to flag some c/c++ style guidelines. Please re-request a review from me once you push changes so that I get a notification to take a look at the PR later. Thanks!

File: sw/device/lib/crypto/drivers/entropy_test.c (hunk 1 above)
Comment (h-filali) [reply sw/device/lib/crypto/drivers/entropy_test.c:31]: Thanks! I'll fix it in my next commit.

File: sw/device/tests/edn_auto_mode.c (hunk 3 above)
Comment (h-filali) [reply sw/device/tests/edn_auto_mode.c:30]: Thanks for letting me know. This will be fixed in my next commit.

File: sw/device/tests/edn_auto_mode.c (hunk 4 above)
Comment (h-filali) [reply sw/device/tests/edn_auto_mode.c:108]: Thanks, I'll have a look.

**Comment by h-filali** [comment]
I managed to get the duration of the test down to around 50 minutes worst case with DVSim. The feedback should also be implemented along with some small additional changes.

File: sw/otbn/code-snippets/randomness.s [hunk 5]
```diff
@@ -117,13 +118,32 @@ test_urnd:
   jal x1, error_checking
   ret
 
+/**
+ * Subroutine thats consumes entropy (RND & URND)
```
Comment (vogelpi) [inline sw/otbn/code-snippets/randomness.s:122]: Nit: it just consumes entropy from RND which is fine (as discussed). So the comment should be updated.

File: sw/device/lib/testing/aes_testutils.c [hunk 6]
```diff
@@ -19,7 +19,7 @@
 #include "hw/top_earlgrey/sw/autogen/top_earlgrey.h"
 #endif
 
-#define TIMEOUT (1000 * 1000)
+#define TIMEOUT (10 * 1000 * 1000)
```
Comment (vogelpi) [inline sw/device/lib/testing/aes_testutils.c:22]: Can you please define an enum for this constant as well? Just like you did for the other cases.

**Review by vogelpi — APPROVED** [review]
Thanks @h-filali for implementing and tuning this test, this was a lot of work! The results looks nice and does what it should do, well done!

I have two minor nits to address.

File: sw/device/lib/testing/aes_testutils.c (hunk 6 above)
Comment (h-filali) [reply sw/device/lib/testing/aes_testutils.c:22]: Sure!

File: sw/otbn/code-snippets/randomness.s (hunk 5 above)
Comment (h-filali) [reply sw/otbn/code-snippets/randomness.s:122]: Thanks, will do!

**Comment by vogelpi** [comment]
Note that CI currently fails with this message:
```
ERROR: /home/vsts/work/1/s/sw/device/lib/testing/BUILD:44:11: Compiling sw/device/lib/testing/aes_testutils.c failed: (Exit 1): clang failed: error executing command (from target //sw/device/lib/testing:aes_testutils) external/crt/toolchains/lowrisc_rv32imcb/wrappers/clang -MD -MF bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/_objs/aes_testutils/aes_testutils.d ... (remaining 53 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
sw/device/lib/testing/aes_testutils.c:233:33: error: use of undeclared identifier 'kAesTestutilsTimeout'
                                kAesTestutilsTimeout);
                                ^
sw/device/lib/testing/aes_testutils.c:242:33: error: use of undeclared identifier 'kAesTestutilsTimeout'
                                kAesTestutilsTimeout);
                                ^
sw/device/lib/testing/aes_testutils.c:244:33: error: use of undeclared identifier 'kAesTestutilsTimeout'
                                kAesTestutilsTimeout);
                                ^
sw/device/lib/testing/aes_testutils.c:267:33: error: use of undeclared identifier 'kAesTestutilsTimeout'
                                kAesTestutilsTimeout);
                                ^
sw/device/lib/testing/aes_testutils.c:272:33: error: use of undeclared identifier 'kAesTestutilsTimeout'
                                kAesTestutilsTimeout);
                                ^

```
It seems that on English Breakfast `kAesTestutilsTimeout` isn't available. It's probably easiest if we have a look at this together on THU.

**Comment by h-filali** [comment]
> Note that CI currently fails with this message:
> 
> ```
> ERROR: /home/vsts/work/1/s/sw/device/lib/testing/BUILD:44:11: Compiling sw/device/lib/testing/aes_testutils.c failed: (Exit 1): clang failed: error executing command (from target //sw/device/lib/testing:aes_testutils) external/crt/toolchains/lowrisc_rv32imcb/wrappers/clang -MD -MF bazel-out/k8-fastbuild-ST-2cc462681f62/bin/sw/device/lib/testing/_objs/aes_testutils/aes_testutils.d ... (remaining 53 arguments skipped)
> 
> Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
> sw/device/lib/testing/aes_testutils.c:233:33: error: use of undeclared identifier 'kAesTestutilsTimeout'
>                                 kAesTestutilsTimeout);
>                                 ^
> sw/device/lib/testing/aes_testutils.c:242:33: error: use of undeclared identifier 'kAesTestutilsTimeout'
>                                 kAesTestutilsTimeout);
>                                 ^
> sw/device/lib/testing/aes_testutils.c:244:33: error: use of undeclared identifier 'kAesTestutilsTimeout'
>                                 kAesTestutilsTimeout);
>                                 ^
> sw/device/lib/testing/aes_testutils.c:267:33: error: use of undeclared identifier 'kAesTestutilsTimeout'
>                                 kAesTestutilsTimeout);
>                                 ^
> sw/device/lib/testing/aes_testutils.c:272:33: error: use of undeclared identifier 'kAesTestutilsTimeout'
>                                 kAesTestutilsTimeout);
>                                 ^
> ```
> 
> It seems that on English Breakfast `kAesTestutilsTimeout` isn't available. It's probably easiest if we have a look at this together on THU.

Thanks for noticing, I fixed it. It was an ifdef that I missed on accident.

**Review by moidx — APPROVED** [review]
