### PR TITLE
[sival, rv_dm] implement rv_dm_access_after_hw_reset test and port rv_dm_access_after_wakeup

### LINKED ISSUE #19882: [chip-level,si-val] chip_rv_dm_access_after_wakeup
### Test point name

[chip_rv_dm_access_after_wakeup](https://github.com/lowRISC/opentitan/blob/cf8ffa811189c6c17285abae7eef19081213f739/hw/top_earlgrey/data/chip_testplan.hjson#L477)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

@GregAC 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] update test name link when ##19749 is merged
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
   - [ ] existing test `chip_sw_rv_dm_access_after_wakeup` is DV-only
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 2

### LINKED ISSUE #19883: [chip-level,si-val] chip_sw_rv_dm_access_after_hw_reset
### Test point name

[chip_sw_rv_dm_access_after_hw_reset](https://github.com/lowRISC/opentitan/blob/cf8ffa811189c6c17285abae7eef19081213f739/hw/top_earlgrey/data/chip_testplan.hjson#L477)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

@GregAC 

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] update test name link when ##19749 is merged
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
   - [ ] existing test `chip_sw_rv_dm_access_after_wakeup` is DV-only
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 1

### PR DESCRIPTION
**Pull request by nbdd0121**
First 5 commits are from #21152

Fix #19882
Fix #19883

### CODE REVIEW

File: sw/host/tests/chip/rv_dm/src/access_after_hw_reset.rs [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+        .init
+        .jtag_params
+        .create(transport)?
+        .connect(JtagTap::RiscvTap)?;
+    assert_eq!(
+        jtag.as_raw()?.execute("$_TARGETNAME.0 curstate")?,
+        "running"
+    );
+    jtag.disconnect()?;
+
```
Comment (pamaury) [inline sw/host/tests/chip/rv_dm/src/access_after_hw_reset.rs:58]: The testplan for `chip_sw_rv_dm_access_after_hw_reset` says `An activation would be required, and the tap strap would also be sampled again`. I assume this means that the test should verify that the tap straps are sampled again. Could this be added to the test? You could run the test twice: the first time you connect to the RISC-V (before the SW reset) and the second time to the LC_TAP but switch the straps to RISC-V before the SW reset and verify that the SW reset causes the straps to be re-sampled.

File: sw/host/tests/chip/rv_dm/src/access_after_wakeup.rs [hunk 2]
```diff
@@ -0,0 +1,168 @@
...
+    assert_eq!(random_value, readback);
+
+    // Allow the software to continue execution.
+    log::info!("SoftwareBarrier = 1");
+    MemWriteReq::execute(uart, software_barrier_addr, &[1])?;
+
+    // Wait for the software to fall asleep.
+    let _ = UartConsole::wait_for(uart, r"Entering normal sleep", opts.timeout)?;
+
+    std::thread::sleep(Duration::from_secs(1));
```
Comment (pamaury) [inline sw/host/tests/chip/rv_dm/src/access_after_wakeup.rs:79]: That seems like a very long delay. You could simply wait to see `Entering normal sleep.` on the UART?

File: sw/host/tests/chip/rv_dm/src/access_after_hw_reset.rs (hunk 1 above)
Comment (nbdd0121) [reply sw/host/tests/chip/rv_dm/src/access_after_hw_reset.rs:58]: The existing DV test doesn't test this, it just straps RV_DM tap and never changes it.

File: sw/host/tests/chip/rv_dm/src/access_after_wakeup.rs [hunk 3]
```diff
@@ -0,0 +1,168 @@
...
+
+    // Press the power button to wake up the device.
+    let power_button = transport.gpio_pin("Ior13")?;
+    log::info!("Pushing power button.");
+    power_button.write(false)?; // pressing power button
+
+    // Wait for the software to wake up.
+    let _ = UartConsole::wait_for(uart, r"Waking up from normal sleep.", opts.timeout)?;
+
```
Comment (pamaury) [inline sw/host/tests/chip/rv_dm/src/access_after_wakeup.rs:88]: here wait for `Entering deep sleep.` ?

**Review by pamaury — APPROVED** [review]
Looks good to me overall except for a couple of details. I think the first test might not fulfill the testplan entirely

File: sw/host/tests/chip/rv_dm/src/access_after_hw_reset.rs (hunk 1 above)
Comment (pamaury) [reply sw/host/tests/chip/rv_dm/src/access_after_hw_reset.rs:58]: I know that some DV tests are not complete unfortunately but I think I would favor writing a more complete SiVal test if possible instead of just doing what the DV tests does (if that does not require a device code change). Maybe @GregAC can let us know what he thinks since he is the testplan owner.

File: sw/host/tests/chip/rv_dm/src/access_after_wakeup.rs (hunk 2 above)
Comment (nbdd0121) [reply sw/host/tests/chip/rv_dm/src/access_after_wakeup.rs:79]: I was trying to make sure that core actually enters the sleep, but I suppose if I wait for the full message (`"Entering normal sleep.\n"`) then it should be fine.

File: sw/host/tests/chip/rv_dm/src/access_after_hw_reset.rs (hunk 1 above)
Comment (nbdd0121) [reply sw/host/tests/chip/rv_dm/src/access_after_hw_reset.rs:58]: I asked Greg for clarification and he thinks replicating what DV test does is good enough. We have a rv_dm_jtag_tap_sel test which tests that tap will be resampled on reset.

**Comment by jwnrt** [comment]
`spi_device_flash_smoketest` failures are unrelated.
