### PR TITLE
[util,test] fix bug in flash scrambling script and add flash scrambling smoketest

### LINKED ISSUE #9322: [flash_ctrl] Backdoor loading enhancements
The flash backdoor load function is at the moment incomplete. As a result, we are not able to enable scrambling in the boot rom because it would work for FPGA but break for verilator / DV.

We need to enhance [this script](https://github.com/lowRISC/opentitan/blob/master/util/design/gen-flash-img.py) to match [this picture](https://docs.opentitan.org/hw/ip/flash_ctrl/doc/#overall-ecc-application).

The main thing that is missing now is a call to `pyfinite` for the field multiply, and then another invocation to `prince` to complete the XEX scrambling scheme.  One additional complication is that the flash scramble key is dependent on collateral stored inside the `otp`.  So the script enhancement needs to take `gen-otp` into account as well.

### PR DESCRIPTION
**Pull request by timothytrippel**
This PR:
1. fixes a bug in the flash scrambling script that resulted in an incorrect computation of the XEX scrambling mask,
2. enables flash scrambling and ECC in the power virus test,
3. consolidates all flash_ctrl configurations in the test ROM (made debugging easier and better aligns with ROM),
4. adds a simple flash scrambling smoke test as a presubmit check in private-CI

This completes all tasks, and fixes #9322.

This also partially addresses #14814.

### CODE REVIEW

File: sw/device/lib/testing/test_rom/test_rom.c [hunk 1]
```diff
@@ -113,6 +113,25 @@ bool rom_test_main(void) {
       mmio_region_from_addr(TOP_EARLGREY_FLASH_CTRL_CORE_BASE_ADDR)));
   CHECK_DIF_OK(dif_flash_ctrl_start_controller_init(&flash_ctrl));
   flash_ctrl_testutils_wait_for_init(&flash_ctrl);
+#if !OT_IS_ENGLISH_BREAKFAST
```
Comment (jdonjdon) [inline sw/device/lib/testing/test_rom/test_rom.c:116]: Just curious, is test_rom share among all top profiles?

File: sw/device/tests/BUILD [hunk 2]
```diff
@@ -2100,10 +2100,8 @@ otp_json(
         otp_partition(
             name = "CREATOR_SW_CFG",
             items = {
-                "CREATOR_SW_CFG_FLASH_DATA_DEFAULT_CFG": "0000090909",
-                # TODO(#14814): enable flash scrambling / ECC by replacing above
-                # with below.
-                #"CREATOR_SW_CFG_FLASH_DATA_DEFAULT_CFG": "0000090606",
+                # Enable flash scrambling / ECC by replacing above with below.
```
Comment (jdonjdon) [inline sw/device/tests/BUILD:2103]: Do you want to update this comment? Looks like "above" is gone.

**Review by jdonjdon — APPROVED** [review]
LGTM with some nits.

File: sw/device/tests/BUILD (hunk 2 above)
Comment (timothytrippel) [reply sw/device/tests/BUILD]: oh yeah, good catch. fixed.

File: sw/device/lib/testing/test_rom/test_rom.c (hunk 1 above)
Comment (timothytrippel) [reply sw/device/lib/testing/test_rom/test_rom.c:116]: currently yes. The whole multi-top strategy has yet to be implemented.
