### PR TITLE
[top-test] entropy_src_csrng_test

### LINKED ISSUE #13227: [chip-test] - chip_sw_entropy_src_csrng
### Test point name

[chip_sw_entropy_src_csrng](https://cs.opensource.google/opentitan/opentitan/+/master:hw/top_earlgrey/data/chip_testplan.hjson?q=chip_sw_entropy_src_csrng)

### Host side component

N/A

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

martin-lueker

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)

### PR DESCRIPTION
**Pull request by moidx**
Adds entropy_src_csrng_test, which tests the CSRNG interrupt request interrupt
whenever a seed or reseed operation is triggered by the CSRNG software
interface, or by EDN0/EDN1.

Fixes #13227

### CODE REVIEW

File: sw/device/lib/testing/entropy_testutils.c [hunk 1]
```diff
@@ -108,3 +105,19 @@ void entropy_testutils_wait_for_state(const dif_entropy_src_t *entropy_src,
     CHECK_DIF_OK(dif_entropy_src_get_main_fsm_state(entropy_src, &cur_state));
   } while (cur_state != state);
 }
+
+void entropy_testutils_stop_all(void) {
+  const dif_entropy_src_t entropy_src = {
```
Comment (engdoreis) [inline sw/device/lib/testing/entropy_testutils.c:110]: Just out of curiosity, would this `const` have the same effect of a `static` and prevent the `entropy_src` from being initialized every time this function is executed?

File: sw/device/tests/entropy_src_csrng_test.c [hunk 2]
```diff
@@ -0,0 +1,223 @@
...
+  csrng_entropy_req_irq_enable();
+  CHECK_DIF_OK(dif_edn_reseed(&edn1, &kEntropyInput));
+  csrng_entropy_req_irq_block_wait();
+  CHECK_DIF_OK(dif_edn_uninstantiate(&edn1));
+
+  csrng_testutils_recoverable_alerts_check(&csrng);
+}
+
+void ottf_external_isr(void) {
+  CHECK_DIF_OK(dif_rv_plic_irq_claim(&plic, kTopEarlgreyPlicTargetIbex0,
```
Comment (engdoreis) [inline sw/device/tests/entropy_src_csrng_test.c:195]: I would use `isr_testutils_csrng_isr` here.

**Review by engdoreis — APPROVED** [review]
LGTM, thanks @moidx for the PR.

**Comment by tjaychen** [comment]
sorry i'm behind on reviews, will have a look today.

File: hw/top_earlgrey/dv/chip_sim_cfg.hjson [hunk 3]
```diff
@@ -882,6 +882,13 @@
       en_run_modes: ["sw_test_mode_test_rom"]
       run_opts: ["+sw_test_timeout_ns=15_000_000"]
     }
+    {
+      name: chip_sw_entropy_src_csrng
+      uvm_test_seq: chip_sw_base_vseq
+      sw_images: ["//sw/device/tests:entropy_src_csrng_test:1"]
+      en_run_modes: ["sw_test_mode_test_rom"]
+      run_opts: ["+sw_test_timeout_ns=15_000_000"]
```
Comment (tjaychen) [inline hw/top_earlgrey/dv/chip_sim_cfg.hjson:890]: you can add some of the run time arguments here to speed up the test.
https://github.com/lowRISC/opentitan/blob/f771a932306664b63e473321040d27abf11343b8/hw/top_earlgrey/dv/chip_sim_cfg.hjson#L897

It helps quite a bit honestly.

File: sw/device/lib/testing/entropy_testutils.c [hunk 4]
```diff
@@ -11,15 +12,18 @@
...
+
+dif_entropy_src_config_t entropy_testutils_config_default(void) {
+  return (dif_entropy_src_config_t){
       .fips_enable = true,
       .route_to_firmware = false,
       .single_bit_mode = kDifEntropySrcSingleBitModeDisabled,
-      .health_test_window_size = 0x0200, /*default*/
-      .alert_threshold = 2,              /*default*/
+      .health_test_window_size = 0x0200,
+      .alert_threshold = 2,
```
Comment (tjaychen) [inline sw/device/lib/testing/entropy_testutils.c:25]: ah good idea...we keep on getting bitten by the non-default values..

File: sw/device/tests/entropy_src_csrng_test.c [hunk 5]
```diff
@@ -0,0 +1,223 @@
...
+  irq_external_ctrl(true);
+}
+
+/**
+ * Blocks until a CSRNG entropy request interrupt is received.
+ */
+static void csrng_entropy_req_irq_block_wait(void) {
+  // The interrupt can come before we enter sleep, so we check beforehand.
+  while (true) {
+    irq_global_ctrl(false);
```
Comment (tjaychen) [inline sw/device/tests/entropy_src_csrng_test.c:95]: this is a little bit confusing to me. Does `irq_global_ctrl(false)` not disable the interrupt completely? or does it just disabling jumping into the ISR routine?

**Review by tjaychen — APPROVED** [review]
couple of questions, lgtm otherwise.

File: sw/device/tests/entropy_src_csrng_test.c (hunk 2 above)
Comment (moidx) [reply sw/device/tests/entropy_src_csrng_test.c]: Done

File: sw/device/tests/entropy_src_csrng_test.c (hunk 5 above)
Comment (moidx) [reply sw/device/tests/entropy_src_csrng_test.c]: It seems `wfi` is able to return on an interrupt even if interrupts are globally disabled, so I guess this means this only disables jumping into the ISR routine. I am not sure if this is the expected behavior though. I refactored the code to simplify this.
