### PR TITLE
[bazel,ci] add CI check to test airgapped bazel builds

### LINKED ISSUE #15136: [bazel,ci] add blocking CI step that tests bazel builds in an airgapped environment
We support airgapped Bazel builds for various reasons. However, this keeps breaking due to various changes made to our Bazel workspace (e.g., #15044). To prevent regressions it makes sense to create a blocking CI step that:

1. executes the `util/prep-bazel-airgapped-build.sh` script to prefetch all Bazel deps (this is already run but is not a blocking step as it was previously flaky), and
2. runs a test Bazel build in an [empty network namespace](https://unix.stackexchange.com/questions/68956/block-network-access-of-a-process) to simulate an airgapped environment

### PR DESCRIPTION
**Pull request by timothytrippel**
This reconfigures the CI job that previously just prefetched the external Bazel dependencies to also run an airgapped Bazel build (using network namespace isolation).

This fixes #15136.

### CODE REVIEW

**Comment by timothytrippel** [comment]
CC: @tjaychen @eunchan

File: ci/scripts/test-airgapped-build.sh [hunk 1]
```diff
@@ -0,0 +1,31 @@
+#!/bin/bash
+# Copyright lowRISC contributors.
+# Licensed under the Apache License, Version 2.0, see LICENSE for details.
+# SPDX-License-Identifier: Apache-2.0
+
+set -ex
+
+# Prefetch bazel airgapped dependencies.
+util/prep-bazel-airgapped-build.sh -f
```
Comment (milesdai) [inline ci/scripts/test-airgapped-build.sh:9]: Just a heads up that this step can be flaky. We never determined the root cause for it, but now that we're making this blocking, we may want to keep an eye out for PRs failing this step.

File: azure-pipelines.yml [hunk 2]
```diff
@@ -140,27 +140,16 @@ jobs:
...
-        exit 1;
-      }
-      rm -rf bazel-airgapped/bitstreams-cache
-      tar -cf bazel-airgapped.tar.gz bazel-airgapped
-    displayName: Pre-fetch and package Bazel dependencies
-    continueOnError: True # This step is flaky on the ubuntu-18.04 image
-  - publish: $(System.DefaultWorkingDirectory)/bazel-airgapped.tar.gz
-    artifact: bazel-dependencies
-    condition: eq(variables['Agent.JobStatus'], 'Succeeded')
+  - template: ci/install-package-dependencies.yml
```
Comment (milesdai) [inline azure-pipelines.yml:151]: Do you need to install the usual package dependencies for this step?

**Review by milesdai — APPROVED** [review]

**Review by cfrantz — APPROVED** [review]

File: azure-pipelines.yml (hunk 2 above)
Comment (timothytrippel) [reply azure-pipelines.yml:151]: Yes, for example, the `libudev` package needs to be installed on the system to build opentitantool.

File: ci/scripts/test-airgapped-build.sh (hunk 1 above)
Comment (timothytrippel) [reply ci/scripts/test-airgapped-build.sh:9]: #15176 attempts to fix this. I will wait to merge this until after #15176 is merged.
