### PR TITLE
[top/dv] shorten sensor_ctrl_alert_test

### LINKED ISSUE #14844: [test-triage] chip_sw_sensor_ctrl_alert
### Hierarchy of regression failure

Chip Level

### Failure Description

Job chip_earlgrey_asic-sim-vcs_run_default killed due to: Exit reason: User job exceeded runlimit: User job timed out has 2 failures:
Test chip_sw_sensor_ctrl_alert has 1 failures.

1.chip_sw_sensor_ctrl_alert.3693031979
Log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.chip_sw_sensor_ctrl_alert/latest/run.log

  Job ID: smart:12097c52-e02d-4117-9e84-5eb923a7ef32

The test times out after one hour. It needs to run 12 resets, so it consumes a lot of time. It may be better to randomize the alerts and run it multiple times, or use "fast_sim" build mode.

### Steps to Reproduce

- Commit hash: https://github.com/lowrisc/opentitan/tree/b73727cd502c1a66545c7f84d7861a1474342963
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_sensor_ctrl_alert --fixed-seed 3693031979 --build-seed 2341666946 --waves -v h

### Tests with similar or related failures

_No response_

### PR DESCRIPTION
**Pull request by tjaychen**
fixes #14844

randomize the events tested each time and increase the number of reseeds

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

File: sw/device/tests/sensor_ctrl_alerts.c [hunk 1]
```diff
@@ -182,6 +169,26 @@ bool test_main(void) {
                                              /*ecc_en*/ false,
                                              /*he_en*/ false);
 
+  // If all bits are set, then this must be the first iteration
+  uint32_t max = (1 << SENSOR_CTRL_PARAM_NUM_ALERT_EVENTS) - 1;
+  uint32_t new_val;
+  if (events_vector == -1) {
```
Comment (moidx) [inline sw/device/tests/sensor_ctrl_alerts.c:175]: nit: s/`-1`/`UINT32_MAX`/

File: sw/device/tests/sensor_ctrl_alerts.c [hunk 2]
```diff
@@ -182,6 +169,26 @@ bool test_main(void) {
...
+    // Do not allow testing of all events at the same time
+    new_val = rand_testutils_gen32_range(1, max - 1);
```
Comment (moidx) [inline sw/device/tests/sensor_ctrl_alerts.c:177]: nit: Can you add small comment to describe why we are doing `max - 1` again here? It seems that the initial value of `max` already has a bound built into it.

**Review by moidx — APPROVED** [review]

File: sw/device/tests/sensor_ctrl_alerts.c (hunk 1 above)
Comment (matutem) [inline sw/device/tests/sensor_ctrl_alerts.c:175]: I think events_vector will always be -1 after each reset, so it seems you need to read the value from flash, or else you will be randomizing it on each reset, and will end up testing only the lowest bit set, so perhaps hardly testing the higher alerts.

File: sw/device/tests/sensor_ctrl_alerts.c [hunk 3]
```diff
@@ -182,6 +169,26 @@ bool test_main(void) {
                                              /*ecc_en*/ false,
                                              /*he_en*/ false);
 
+  // If all bits are set, then this must be the first iteration
+  uint32_t max = (1 << SENSOR_CTRL_PARAM_NUM_ALERT_EVENTS) - 1;
+  uint32_t new_val;
```
Comment (matutem) [inline sw/device/tests/sensor_ctrl_alerts.c:174]: These two variables seem only used on the first iteration, so move their declaration inside the if below.

File: sw/device/tests/sensor_ctrl_alerts.c [hunk 4]
```diff
@@ -182,6 +169,26 @@ bool test_main(void) {
                                              /*ecc_en*/ false,
                                              /*he_en*/ false);
 
+  // If all bits are set, then this must be the first iteration
```
Comment (matutem) [inline sw/device/tests/sensor_ctrl_alerts.c:172]: Extend  the comment to indicate on the first iteration you set events_vector to a random number, with the bits set becoming the alerts to be tested, and then you progressively clear them when incrementing.

**Review by matutem — CHANGES_REQUESTED** [review]
Could you look into the suggested changes?

File: sw/device/tests/sensor_ctrl_alerts.c (hunk 1 above)
Comment (tjaychen) [reply sw/device/tests/sensor_ctrl_alerts.c:175]: o no that's not the case. Because this is flash, it actually is only -1 on the "first" iteration. 
I've actually confirmed this on both fpga / sims.

Comment (tjaychen) [reply sw/device/tests/sensor_ctrl_alerts.c:175]: o i should also clarify. The events vector is directly mapped. Meaning you don't need the flash read routines to actually get the value. The processor can just directly read the address.

File: sw/device/tests/sensor_ctrl_alerts.c (hunk 2 above)
Comment (tjaychen) [reply sw/device/tests/sensor_ctrl_alerts.c]: i updated this more to directly use a population count, this better matches my original intent.
Let me know if it makes sense.

File: sw/device/tests/sensor_ctrl_alerts.c (hunk 3 above)
Comment (tjaychen) [reply sw/device/tests/sensor_ctrl_alerts.c]: updated

File: sw/device/tests/sensor_ctrl_alerts.c [hunk 5]
```diff
@@ -71,6 +72,31 @@ static uint32_t get_events(dif_toggle_t fatal) {
   return events;
 }
 
+/**
+ *  Count the nubmer of 1's in a given vector.
+ *  Not attempting to be smart, just do something that is straightforward.
+ *  See https://en.wikipedia.org/wiki/Hamming_weight
+ */
+static uint32_t pop_count32(uint32_t x) {
```
Comment (moidx) [inline sw/device/tests/sensor_ctrl_alerts.c:80]: You may be able to use `bitfield_popcount32 ` from sw/device/lib/base/bitfield.h

File: sw/device/tests/sensor_ctrl_alerts.c [hunk 6]
```diff
@@ -47,7 +48,7 @@ static dif_alert_handler_t alert_handler;
  * so we go from 0xFFFF_FFFF -> 0xFFFF_FFFE -> 0xFFFF_FFFC
  */
 __attribute__((section(".non_volatile_scratch")))
-const volatile uint32_t events_vector = -1;
+const volatile uint32_t events_vector = UINT32_MAX;
```
Comment (moidx) [inline sw/device/tests/sensor_ctrl_alerts.c:51]: nit: Can this be non-`const`?

**Review by moidx — APPROVED** [review]

File: sw/device/tests/sensor_ctrl_alerts.c (hunk 2 above)
Comment (moidx) [reply sw/device/tests/sensor_ctrl_alerts.c]: Makes sense to me. Thanks for updating.

File: sw/device/lib/testing/flash_ctrl_testutils.c [hunk 7]
```diff
@@ -303,9 +303,27 @@ void flash_ctrl_testutils_increment_counter(dif_flash_ctrl_state_t *flash_state,
...
+                                      uint32_t *strike_counter,
+                                      uint32_t new_val) {
+  uint32_t addr = (uint32_t)strike_counter;
+  uint32_t val = abs_mmio_read32(addr);
+
+  // Determine which bits are changing value and whether they are allowed
+  // 0 -> 1 is not okay
+  // 1 -> 0 is okay
+  CHECK(((val ^ new_val) & new_val) == 0);
+  CHECK(new_val != 0);
```
Comment (matutem) [inline sw/device/lib/testing/flash_ctrl_testutils.c:325]: In the use you have for set_counter this CHECK will pass, but not in general. Move this assertion to the caller?

File: sw/device/lib/testing/flash_ctrl_testutils.c [hunk 8]
```diff
@@ -303,9 +303,27 @@ void flash_ctrl_testutils_increment_counter(dif_flash_ctrl_state_t *flash_state,
...
+  CHECK(flash_ctrl_testutils_write(flash_state, addr, 0, &new_val,
+                                   kDifFlashCtrlPartitionTypeData, 1),
+        "Error incrementing strike counter");
```
Comment (matutem) [inline sw/device/lib/testing/flash_ctrl_testutils.c:328]:
```suggestion
        "Error setting strike counter");
```

File: sw/device/tests/sensor_ctrl_alerts.c (hunk 5 above)
Comment (tjaychen) [reply sw/device/tests/sensor_ctrl_alerts.c:80]: ?! i did not know this existed. let me have a look.

File: sw/device/tests/sensor_ctrl_alerts.c (hunk 6 above)
Comment (tjaychen) [reply sw/device/tests/sensor_ctrl_alerts.c:51]: hmmm....actually why is const there.. that doesn't seem right.

File: sw/device/lib/testing/flash_ctrl_testutils.h [hunk 9]
```diff
@@ -246,4 +246,19 @@ void flash_ctrl_testutils_increment_counter(dif_flash_ctrl_state_t *flash_state,
                                             uint32_t *strike_counter,
                                             uint32_t index);
 
+/**
+ * Sets a strike counter to an arbitrary value.
+ *
+ * If the arbitrary value is 0 or is impossible (attempts to flip a bit
```
Comment (matutem) [inline sw/device/lib/testing/flash_ctrl_testutils.h:252]: I think it should be perfectly fine to clear the counter.

File: sw/device/lib/testing/flash_ctrl_testutils.h [hunk 10]
```diff
@@ -246,4 +246,19 @@ void flash_ctrl_testutils_increment_counter(dif_flash_ctrl_state_t *flash_state,
...
+ * from 0 to 1 without an erase), an error is created.
+ *
+ *
```
Comment (matutem) [inline sw/device/lib/testing/flash_ctrl_testutils.h:255]: Delete extra line.

**Review by matutem — APPROVED** [review]
With some optional suggestions, LGTM.

File: sw/device/lib/testing/flash_ctrl_testutils.c (hunk 7 above)
Comment (tjaychen) [reply sw/device/lib/testing/flash_ctrl_testutils.c:325]: o yeah good point, that should not be there.

File: sw/device/lib/testing/flash_ctrl_testutils.h (hunk 9 above)
Comment (tjaychen) [reply sw/device/lib/testing/flash_ctrl_testutils.h:252]: yeah you're right, 0 should be allowed, similar to comment above.

File: sw/device/lib/testing/flash_ctrl_testutils.c (hunk 8 above)
Comment (tjaychen) [reply sw/device/lib/testing/flash_ctrl_testutils.c]: fixed

File: sw/device/lib/testing/flash_ctrl_testutils.h (hunk 10 above)
Comment (tjaychen) [reply sw/device/lib/testing/flash_ctrl_testutils.h]: fixed
