### PR TITLE
[i2c] flop i2c scl and sda outputs

### LINKED ISSUE #15003: [i2c] Output clocks unflopped
The i2c output clocks `scl` right now mostly depends on what the current state is with [one exception](https://github.com/lowRISC/opentitan/blob/b2267c8b3b30662107ce189ce6455973fe766034/hw/ip/i2c/rtl/i2c_fsm.sv#L577-L578).

Overall this means the value of the clock is dependent on logic decode and can result in momentary glitches. 

This sometimes leads to failures in the `i2c_host_rx_tx` test since the receiving device can directly trigger on the clock edge. This causes the device to inadvertently to advance counts when it should not, leading to unexpected NACKs.

For safety, we should probably flop the clock output to make sure we cannot encounter these kinds of glitches.

### PR DESCRIPTION
**Pull request by tjaychen**
- fixes #15003

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

**Comment by tjaychen** [comment]
@a-will let me know if you think this works.
@martin-lueker we added this fix since we actually noticed some DV failures related to potential glitches on the clock.

**Review by martin-lueker — APPROVED** [review]
Looks reasonable to me.  

@igk8 do you have any feedback on this?

**Review by a-will — COMMENTED** [review]
I think ~`event_scl_interference`~ and `event_sda_interference` may need to be updated, else they can trigger due to the delayed output.

Edit: Looks like only `event_sda_interference` depends on the immediate `sda_temp` vs `sda_i`, though.

**Comment by tjaychen** [comment]
> I think ~`event_scl_interference`~ and `event_sda_interference` may need to be updated, else they can trigger due to the delayed output.
> 
> Edit: Looks like only `event_sda_interference` depends on the immediate `sda_temp` vs `sda_i`, though.

yeah i was looking at that..and i more or less reasoned that by the time we start driving sda_temp (even from the pre-flop perspective), we've already passed the state where the other end should have let go of the bus. So even though our `1` is not on the bus yet, the incoming bus still should not be 0.

**Comment by tjaychen** [comment]
> > I think ~`event_scl_interference`~ and `event_sda_interference` may need to be updated, else they can trigger due to the delayed output.
> > Edit: Looks like only `event_sda_interference` depends on the immediate `sda_temp` vs `sda_i`, though.
> 
> yeah i was looking at that..and i more or less reasoned that by the time we start driving sda_temp (even from the pre-flop perspective), we've already passed the state where the other end should have let go of the bus. So even though our `1` is not on the bus yet, the incoming bus still should not be 0.

i don't THINK it hurs to change the references of `sda_temp` to `sda_o` though.

**Comment by a-will** [comment]
> > > I think ~`event_scl_interference`~ and `event_sda_interference` may need to be updated, else they can trigger due to the delayed output.
> > > Edit: Looks like only `event_sda_interference` depends on the immediate `sda_temp` vs `sda_i`, though.
> > 
> > 
> > yeah i was looking at that..and i more or less reasoned that by the time we start driving sda_temp (even from the pre-flop perspective), we've already passed the state where the other end should have let go of the bus. So even though our `1` is not on the bus yet, the incoming bus still should not be 0.
> 
> i don't THINK it hurs to change the references of `sda_temp` to `sda_o` though.

But it's actually there to look for cases where things aren't going to plan. We want to know when some other device is yanking on the data line, so we can possibly do something about it.

_However_, I'm not sure the overall calculation makes sense for timing. The rise time of SDA could be quite long (max 1 _microsecond_) compared to `clk_i`, so one cycle may be insufficient for detection. This looks like a bug.

**Comment by tjaychen** [comment]
> > > > I think ~`event_scl_interference`~ and `event_sda_interference` may need to be updated, else they can trigger due to the delayed output.
> > > > Edit: Looks like only `event_sda_interference` depends on the immediate `sda_temp` vs `sda_i`, though.
> > > 
> > > 
> > > yeah i was looking at that..and i more or less reasoned that by the time we start driving sda_temp (even from the pre-flop perspective), we've already passed the state where the other end should have let go of the bus. So even though our `1` is not on the bus yet, the incoming bus still should not be 0.
> > 
> > 
> > i don't THINK it hurs to change the references of `sda_temp` to `sda_o` though.
> 
> But it's actually there to look for cases where things aren't going to plan. We want to know when some other device is yanking on the data line, so we can possibly do something about it.
> 
> _However_, I'm not sure the overall calculation makes sense for timing. The rise time of SDA could be quite long (max 1 _microsecond_) compared to `clk_i`, so one cycle may be insufficient for detection. This looks like a bug.

yeah, so i think sda_temp going high would be our "intent" right? So if it doesn't match the incoming value at a particular state, i think it would be reasonable to say "something has gone wrong". However, like you pointed out and we discussed offline, the way this is done right now doesn't work. Even if what i were saying is true, the `sda_i` is synchronzied, so when `sda_temp` has a 0 -> 1 transition, it will never match and just always be seen as unstable. I'll file an issue on this.

**Comment by tjaychen** [comment]
i'm holding off on this one until i investigate the sda_interference issue.
That one seems more fundamental, since it will completely explode with the added delay here.

**Comment by tjaychen** [comment]
alright, i'm finally pushing this one again. 
The sda_interference stuff has been addressed in a separate PR.

The scl_interference is failing all over the place at block level, but that's because of #15066, which i hope to fix separately.

File: sw/device/tests/sim_dv/i2c_host_tx_rx_test.c [hunk 1]
```diff
@@ -147,12 +147,12 @@ bool test_main(void) {
...
+  for (uint32_t i = kDifI2cIrqFmtWatermark; i <= kDifI2cIrqTransComplete; ++i) {
+    CHECK_DIF_OK(dif_i2c_irq_set_enabled(&i2c, i, kDifToggleEnabled));
+  }
   CHECK_DIF_OK(
-      dif_i2c_irq_set_enabled(&i2c, kDifI2cIrqFmtWatermark, kDifToggleEnabled));
-  CHECK_DIF_OK(
-      dif_i2c_irq_set_enabled(&i2c, kDifI2cIrqRxWatermark, kDifToggleEnabled));
-  CHECK_DIF_OK(dif_i2c_irq_set_enabled(&i2c, kDifI2cIrqTransComplete,
-                                       kDifToggleEnabled));
+      dif_i2c_irq_set_enabled(&i2c, kDifI2cIrqSdaUnstable, kDifToggleDisabled));
```
Comment (a-will) [inline sw/device/tests/sim_dv/i2c_host_tx_rx_test.c:155]: Looks like you could just reuse the array down here too.

File: sw/device/tests/sim_dv/i2c_host_tx_rx_test.c [hunk 2]
```diff
@@ -101,21 +101,21 @@ bool test_main(void) {
   CHECK_DIF_OK(dif_rv_plic_init(
       mmio_region_from_addr(TOP_EARLGREY_RV_PLIC_BASE_ADDR), &plic));
 
+  // Enable functional interrupts as well as error interrupts to make sure
+  // everything is behaving as expected.
+  for (uint32_t i = kTopEarlgreyPlicIrqIdI2c0FmtWatermark;
+       i <= kTopEarlgreyPlicIrqIdI2c0TransComplete; ++i) {
```
[the remark this answers is not in the document]
Comment (tjaychen) [reply sw/device/tests/sim_dv/i2c_host_tx_rx_test.c:107]: sure i can do that.

File: sw/device/tests/sim_dv/i2c_host_tx_rx_test.c (hunk 1 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/i2c_host_tx_rx_test.c:155]: ? aren't the indices different here?

Comment (a-will) [reply sw/device/tests/sim_dv/i2c_host_tx_rx_test.c:155]: Ah, I guess I didn't pay close enough attention. Also... <insert complaint about having wide IP-specific interrupt vectors and CSRs in the PLIC _and_ the IP> ;)

Comment (tjaychen) [reply sw/device/tests/sim_dv/i2c_host_tx_rx_test.c:155]: no worries, i can create two separate arrays as you say.

File: hw/ip/i2c/doc/_index.md [hunk 3]
```diff
@@ -117,6 +117,18 @@ In this state the output drivers `scl_tx_o` and `sda_tx_o` are controlled direct
...
+
+While in host mode, SCL and SDA are generated through the internal state machine.
+Since SCL is directly decoded from the states, it can have short glitches during transition which the external target may be sensitive to if it is not using an over-sampling scheme.
+To counter this, the SCL and SDA outputs from the internal state machine are flopped before they are emitted.
+
+This adds a one cycle module clock delay to both signals.
+If the module clock is sufficiently faster than I2C line speeds (for example 20MHz), this is not an issue.
+However if the line speeds and the module clock speeds become very close (2x), the 1 cycle delay may have an impact, as the internal state machine may mistakenly think it has sampled an SDA that has not yet been updated.
+
+It it thus recommended to run clock ratios such that the internal module clock is at least 5x-10x the line speeds.
```
[the remark this answers is not in the document]
Comment (tjaychen) [reply hw/ip/i2c/doc/_index.md:130]: i think it still is, but i haven't looked super closely or tried it out.  For one thing I think the synchronization delay being greater than the line speed / clock speed ratio is already going to cause problems.  Since by the time you actually see the input you're already into a different clock phase.

File: sw/device/tests/sim_dv/i2c_host_tx_rx_test.c [hunk 4]
```diff
@@ -88,7 +88,7 @@ void ottf_external_isr(void) {
       i2c_irq = kDifI2cIrqTransComplete;
       break;
     default:
-      LOG_ERROR("Unexpected interrupt (at I2C): %d", i2c_irq);
+      LOG_ERROR("Unexpected interrupt (at Ip2C): %d", i2c_irq);
```
[the remark this answers is not in the document]
Comment (tjaychen) [reply sw/device/tests/sim_dv/i2c_host_tx_rx_test.c:91]: oops, let me fix that.

File: sw/device/tests/sim_dv/i2c_host_tx_rx_test.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (tjaychen) [reply sw/device/tests/sim_dv/i2c_host_tx_rx_test.c]: updated

File: sw/device/tests/sim_dv/i2c_host_tx_rx_test.c (hunk 1 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/i2c_host_tx_rx_test.c]: updated

**Review by a-will — APPROVED** [review]
