### PR TITLE
[top/dv] Add inject_scramble_seed test

### LINKED ISSUE #15035: [chip-test] chip_sw_inject_scramble_seed
### Test point name

[chip_sw_inject_scramble_seed](https://github.com/lowRISC/opentitan/blob/1f3a24718d33c975f12f902994c39d2497b8623e/hw/top_earlgrey/data/chip_testplan.hjson#L3220)

### Host side component

SystemVerilog

### OpenTitanTool infrastructure implemented

Unknown

### Contact person

@tjaychen, @moidx, @jdonjdon

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [x] Test added to dvsim nightly regression (and passing at time of checking)

### PR DESCRIPTION
**Pull request by tjaychen**
- fixes #15035
- This test begins in production state and burns scrambling keys into the OTP.  It then reboots to bootstrap and flashes in the same image with scramble turned on.
- The image is then run, proving that we are able to load a scrambling key.

Signed-off-by: Timothy Chen <timothytim@google.com>

### CODE REVIEW

File: sw/device/silicon_creator/rom/bootstrap.c [hunk 1]
```diff
@@ -261,15 +261,15 @@ static rom_error_t bootstrap_handle_erase(bootstrap_state_t *state) {
 static rom_error_t bootstrap_handle_erase_verify(bootstrap_state_t *state) {
   HARDENED_CHECK_EQ(*state, kBootstrapStateEraseVerify);
 
-  rom_error_t err_0 = flash_ctrl_data_erase_verify(0, kFlashCtrlEraseTypeBank);
-  rom_error_t err_1 = flash_ctrl_data_erase_verify(
-      FLASH_CTRL_PARAM_BYTES_PER_BANK, kFlashCtrlEraseTypeBank);
-  HARDENED_RETURN_IF_ERROR(err_0);
-  HARDENED_RETURN_IF_ERROR(err_1);
+  // rom_error_t err_0 = flash_ctrl_data_erase_verify(0,
```
Comment (tjaychen) [inline sw/device/silicon_creator/rom/bootstrap.c:264]: @alphan can you think of a good way where we can let DV bypass the erase verification stage?
These checks below take up basically most of the test time.

I wouldn't be opposed to using an OTP bit.. :)

Comment (tjaychen) [reply sw/device/silicon_creator/rom/bootstrap.c:264]: this change is currently causing unittest to fail.

File: hw/top_earlgrey/dv/env/seq_lib/chip_sw_inject_scramble_seed_vseq.sv [hunk 2]
```diff
@@ -0,0 +1,69 @@
...
+    // setup triggers to bootstrap during the second run
+    cfg.chip_vif.sw_straps_if.drive({3{1'b1}});
+
+    `DV_SPINWAIT(wait(cfg.sw_logger_vif.printed_log == "boot strap requested!");,
+             "timeout waiting for C side acknowledgement",
+             cfg.sw_test_timeout_ns)
+
+    `uvm_info(`gfn, "Received boot strap acknowledgement", UVM_LOW)
+
+    spi_device_load_bootstrap({cfg.sw_images[SwTypeTest], ".64.vmem"});
```
Comment (moidx) [inline hw/top_earlgrey/dv/env/seq_lib/chip_sw_inject_scramble_seed_vseq.sv:59]: Wow, this is nice.

File: sw/device/lib/testing/test_rom/test_rom.c [hunk 3]
```diff
@@ -122,7 +128,33 @@ bool rom_test_main(void) {
...
+  // Check the otp to see if flash scramble should be enabled.
+  CHECK_DIF_OK(dif_otp_ctrl_init(
+      mmio_region_from_addr(TOP_EARLGREY_OTP_CTRL_CORE_BASE_ADDR), &otp_ctrl));
+
+  uint32_t otp_val;
+  otp_val = abs_mmio_read32(
+      TOP_EARLGREY_OTP_CTRL_CORE_BASE_ADDR + OTP_CTRL_SW_CFG_WINDOW_REG_OFFSET +
+      OTP_CTRL_PARAM_CREATOR_SW_CFG_FLASH_DATA_DEFAULT_CFG_OFFSET);
+
+  // very stupid, just set the entire first bank to scrambled right now
```
Comment (moidx) [inline sw/device/lib/testing/test_rom/test_rom.c:141]: Should this comment be tagged with a TODO? I believe @alphan is going to make some updates in the ROM as well.

File: sw/device/silicon_creator/rom/bootstrap.c (hunk 1 above)
Comment (moidx) [reply sw/device/silicon_creator/rom/bootstrap.c:264]: What if we add a `#define OT_TEST_ROM` or something similar so that this is removed at compile time?

File: sw/device/tests/sim_dv/inject_scramble_seed.c [hunk 4]
```diff
@@ -0,0 +1,121 @@
...
+#include "sw/device/lib/testing/test_framework/status.h"
+
+#include "flash_ctrl_regs.h"
+#include "hw/top_earlgrey/sw/autogen/top_earlgrey.h"
+#include "otp_ctrl_regs.h"
+
+static dif_rstmgr_t rstmgr;
+static dif_otp_ctrl_t otp_ctrl;
+
+#define WORD_SIZE sizeof(uint64_t)
```
Comment (moidx) [inline sw/device/tests/sim_dv/inject_scramble_seed.c:28]: nit: Use enums to define constants to improve debug references.

```c
enum {
  kFlashWordSize = sizeof(uint64_t),
}
```

File: sw/device/tests/sim_dv/inject_scramble_seed.c [hunk 5]
```diff
@@ -0,0 +1,121 @@
...
+
+bool test_main(void) {
+  dif_rstmgr_reset_info_bitfield_t info;
+  CHECK_DIF_OK(dif_rstmgr_init(
+      mmio_region_from_addr(TOP_EARLGREY_RSTMGR_AON_BASE_ADDR), &rstmgr));
+
+  CHECK_DIF_OK(dif_otp_ctrl_init(
+      mmio_region_from_addr(TOP_EARLGREY_OTP_CTRL_CORE_BASE_ADDR), &otp_ctrl));
+
+  info = rstmgr_testutils_reason_get();
```
Comment (moidx) [inline sw/device/tests/sim_dv/inject_scramble_seed.c:40]: nit: The declaration should be inline here:

```c
dif_rstmgr_reset_info_bitfield_t info = rstmgr_testutils_reason_get();
```

File: sw/device/tests/sim_dv/inject_scramble_seed.c [hunk 6]
```diff
@@ -0,0 +1,121 @@
...
+                      i * WORD_SIZE;
+      CHECK_DIF_OK(dif_otp_ctrl_dai_program64(
+          &otp_ctrl, kDifOtpCtrlPartitionSecret1, addr, val));
+      otp_ctrl_testutils_wait_for_dai(&otp_ctrl);
+    };
+
+    // lock the secret1 partition
+    CHECK_DIF_OK(
+        dif_otp_ctrl_dai_digest(&otp_ctrl, kDifOtpCtrlPartitionSecret1, 0));
+    otp_ctrl_testutils_wait_for_dai(&otp_ctrl);
```
Comment (moidx) [inline sw/device/tests/sim_dv/inject_scramble_seed.c:93]: nit: You may be able to use the following testutil:

```c
otp_ctrl_testutils_lock_partition(&otp_ctrl, kDifOtpCtrlPartitionSecret1, /*digest=*/0);
```

File: sw/device/silicon_creator/rom/bootstrap.c (hunk 1 above)
Comment (alphan) [reply sw/device/silicon_creator/rom/bootstrap.c:264]: Unfortunately not at the moment. We have one more use-case and this will require some thought.

@moidx, I think this should be DV/simulation specific, not test_rom since we would want to perform this check on the FPGA to keep the bootstrap as close to the actual thing as possible.

File: sw/device/lib/testing/test_rom/test_rom.c [hunk 7]
```diff
@@ -122,7 +128,33 @@ bool rom_test_main(void) {
...
+        &flash_ctrl, &default_properties));
+    default_properties.scramble_en = bitfield_field32_read(
+        otp_val, FLASH_CTRL_DEFAULT_REGION_SCRAMBLE_EN_FIELD);
+    CHECK_DIF_OK(dif_flash_ctrl_set_default_region_properties(
+        &flash_ctrl, default_properties));
+  }
+#endif
+
   if (bootstrap_requested() == kHardenedBoolTrue) {
+    LOG_INFO("boot strap requested!");
```
Comment (alphan) [inline sw/device/lib/testing/test_rom/test_rom.c:157]:
```suggestion
    LOG_INFO("bootstrap requested!");
```

File: sw/device/lib/testing/test_rom/test_rom.c (hunk 3 above)
Comment (alphan) [reply sw/device/lib/testing/test_rom/test_rom.c:141]: Yeah, but that change might take some time because @cfrantz pointed out that the next owner should be able to control it and we should consider putting these in the info pages. I think we will also have OTP values for bootstrapping this configuration when we don't have anything in the info pages.

@tjaychen I didn't read the rest of the PR but I'm curious: why just the first bank? Can you set the flash_data_default_cfg in the OTP images to scramble everything and just apply that setting here?

File: sw/device/tests/sim_dv/inject_scramble_seed.c [hunk 8]
```diff
@@ -0,0 +1,121 @@
...
+        &otp_ctrl, kDifOtpCtrlPartitionCreatorSwCfg,
+        (OTP_CTRL_PARAM_CREATOR_SW_CFG_FLASH_DATA_DEFAULT_CFG_OFFSET -
+         OTP_CTRL_PARAM_CREATOR_SW_CFG_OFFSET),
+        otp_val));
+    otp_ctrl_testutils_wait_for_dai(&otp_ctrl);
+
+    // reset the device
+    LOG_INFO("Completed first phase, reboot");
+    CHECK_DIF_OK(dif_rstmgr_software_device_reset(&rstmgr));
+    wait_for_interrupt();
```
Comment (alphan) [inline sw/device/tests/sim_dv/inject_scramble_seed.c:110]:
```suggestion
    wait_for_interrupt();
    return false;
```

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 4 above)
Comment (alphan) [reply sw/device/tests/sim_dv/inject_scramble_seed.c:28]: Actually, doesn't `flash_ctrl_regs.h` already publish this constant?

File: sw/device/tests/sim_dv/inject_scramble_seed.c [hunk 9]
```diff
@@ -0,0 +1,121 @@
...
+  CHECK_DIF_OK(dif_otp_ctrl_init(
+      mmio_region_from_addr(TOP_EARLGREY_OTP_CTRL_CORE_BASE_ADDR), &otp_ctrl));
+
+  info = rstmgr_testutils_reason_get();
+
+  bool secret1_locked = false;
+  CHECK_DIF_OK(dif_otp_ctrl_is_digest_computed(
+      &otp_ctrl, kDifOtpCtrlPartitionSecret1, &secret1_locked));
+
+  if (!secret1_locked && (info & kDifRstmgrResetInfoPor)) {
```
Comment (alphan) [inline sw/device/tests/sim_dv/inject_scramble_seed.c:46]: nit: just to keep the control flow simple:
```suggestion
  if (!secret1_locked) {
```

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 5 above)
Comment (alphan) [inline sw/device/tests/sim_dv/inject_scramble_seed.c:40]: nit: unless I missed something this test only expects `kDifRstmgrResetInfoPor`, right?
```suggestion
  CHECK(rstmgr_testutils_reason_get() == kDifRstmgrResetInfoPor);
  rstmgr_testutils_reason_clear();
```

File: sw/device/tests/sim_dv/inject_scramble_seed.c [hunk 10]
```diff
@@ -0,0 +1,121 @@
...
+         i < OTP_CTRL_PARAM_FLASH_ADDR_KEY_SEED_SIZE / WORD_SIZE; ++i) {
+      uint64_t val =
+          (uint64_t)rand_testutils_gen32() << 32 | rand_testutils_gen32();
+      uint32_t addr = (OTP_CTRL_PARAM_FLASH_ADDR_KEY_SEED_OFFSET -
+                       OTP_CTRL_PARAM_SECRET1_OFFSET) +
+                      i * WORD_SIZE;
+      CHECK_DIF_OK(dif_otp_ctrl_dai_program64(
+          &otp_ctrl, kDifOtpCtrlPartitionSecret1, addr, val));
+      otp_ctrl_testutils_wait_for_dai(&otp_ctrl);
+    };
```
Comment (alphan) [inline sw/device/tests/sim_dv/inject_scramble_seed.c:63]:
```suggestion
    enum {
        kFlashAddrKeyOffset = OTP_CTRL_PARAM_FLASH_ADDR_KEY_SEED_OFFSET -
                             OTP_CTRL_PARAM_SECRET1_OFFSET,
    };
    for (size_t i = 0; i < OTP_CTRL_PARAM_FLASH_ADDR_KEY_SEED_SIZE; i += WORD_SIZE) {
      uint64_t val =
          (uint64_t)rand_testutils_gen32() << 32 | rand_testutils_gen32();
      CHECK_DIF_OK(dif_otp_ctrl_dai_program64(
          &otp_ctrl, kDifOtpCtrlPartitionSecret1, kFlashAddrKeyOffset + i, val));
      otp_ctrl_testutils_wait_for_dai(&otp_ctrl);
    };
```

File: sw/device/tests/sim_dv/inject_scramble_seed.c [hunk 11]
```diff
@@ -0,0 +1,121 @@
...
+
+    for (uint32_t i = 0;
```
Comment (alphan) [inline sw/device/tests/sim_dv/inject_scramble_seed.c:65]: nit: same comment as the above loop, can add a `kFlashDataKeyOffset` and slightly simplify the rest

File: sw/device/tests/sim_dv/inject_scramble_seed.c [hunk 12]
```diff
@@ -0,0 +1,121 @@
...
+      uint32_t addr = (OTP_CTRL_PARAM_FLASH_DATA_KEY_SEED_OFFSET -
+                       OTP_CTRL_PARAM_SECRET1_OFFSET) +
+                      i * WORD_SIZE;
+
+      CHECK_DIF_OK(dif_otp_ctrl_dai_program64(
+          &otp_ctrl, kDifOtpCtrlPartitionSecret1, addr, val));
+      otp_ctrl_testutils_wait_for_dai(&otp_ctrl);
+    };
+
+    for (uint32_t i = 0; i < OTP_CTRL_PARAM_SRAM_DATA_KEY_SEED_SIZE / WORD_SIZE;
```
Comment (alphan) [inline sw/device/tests/sim_dv/inject_scramble_seed.c:78]: nit: same comment as the above loop, can add a `kSramDataKeyOffset` and slightly simplify the rest

File: sw/device/tests/sim_dv/inject_scramble_seed.c [hunk 13]
```diff
@@ -0,0 +1,121 @@
...
+        otp_val));
+    otp_ctrl_testutils_wait_for_dai(&otp_ctrl);
+
+    // reset the device
+    LOG_INFO("Completed first phase, reboot");
+    CHECK_DIF_OK(dif_rstmgr_software_device_reset(&rstmgr));
+    wait_for_interrupt();
+  } else if (secret1_locked && (info & kDifRstmgrResetInfoPor)) {
+    LOG_INFO("Hello World");
+    return true;
```
Comment (alphan) [inline sw/device/tests/sim_dv/inject_scramble_seed.c:113]:
```suggestion
  } else if (secret1_locked) {
    return true;
```

File: sw/device/tests/sim_dv/inject_scramble_seed.c [hunk 14]
```diff
@@ -0,0 +1,121 @@
...
+  } else {
+    LOG_ERROR(
+        "The test should never have reached here, serect1 lock: %d, info: 0x%x",
+        secret1_locked, info);
+  }
```
Comment (alphan) [inline sw/device/tests/sim_dv/inject_scramble_seed.c:118]:
```suggestion
  }
```

**Review by alphan — COMMENTED** [review]
Thanks @tjaychen, just some nits.

File: sw/device/silicon_creator/rom/bootstrap.c (hunk 1 above)
Comment (tjaychen) [reply sw/device/silicon_creator/rom/bootstrap.c:264]: yes DV / simulation specific is fine. The problem is that there is no DV specific test rom, but even if there were, everyone right now invokes the actuaul rom's "bootstrap", so we all end up in the same place.

That's why i think having an OTP bit would be better.  A zero value of the otp should always do the verified read, whereas a hardened non-zero value would skip it.  This would make it harder for an attacker to arbitrarily glitch into that state.

File: sw/device/lib/testing/test_rom/test_rom.c (hunk 3 above)
Comment (tjaychen) [reply sw/device/lib/testing/test_rom/test_rom.c:141]: wait...isn't that what i did? 
o crap sorry, originally i did something else and applied to only the 1st bank.  But I forgot to update the comment afterwards, i'll fix that.

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 4 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c:28]: o you're right, i think it does, i'll update that.

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 5 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c:40]: ah okay got it.

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 6 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c:93]: ah good call, let me switch.

File: sw/device/lib/testing/test_rom/test_rom.c (hunk 7 above)
Comment (tjaychen) [reply sw/device/lib/testing/test_rom/test_rom.c:157]: will fix! i'm not actually sure I need this anymore. I originally added it to synchronize with DV, but i forgot Alex's bootstrap already applies a reset. Let me remove this altogether.

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 5 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c:40]: that's right, see my point above. I don't actually need the sw reset anymore because the bootstrap protocol from the host side issues a reset.  I will get rid of this.

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 13 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c:113]: ah i actually wanted the hello world so the DV side can explicitly check this. 
Technically this doesn't add a ton, but i still want the DV side to wait on a check. I'll add a comment to make this clearer.

File: sw/device/lib/testing/test_rom/test_rom.c (hunk 3 above)
Comment (tjaychen) [reply sw/device/lib/testing/test_rom/test_rom.c]: updated comment

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 4 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c]: updated.

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 6 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c]: updated.

File: sw/device/lib/testing/test_rom/test_rom.c (hunk 7 above)
Comment (tjaychen) [reply sw/device/lib/testing/test_rom/test_rom.c]: i was actually wrong..the beginning of the bootstrap routine doesn't actually call reset.
So if I remove the software reset, the routine just times out waiting for certain register changes.
As a result, I've decided to just keep this here.

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 8 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c:118]: updated.

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 9 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c]: removed the usage of rst info, since it's not needed. 
I do still issue a software reset, but i don't need to look at the reset reason to determine anything.

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 10 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c]: updated to match.

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 11 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c]: updated.

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 12 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c]: updated.

File: sw/device/tests/sim_dv/inject_scramble_seed.c (hunk 14 above)
Comment (tjaychen) [reply sw/device/tests/sim_dv/inject_scramble_seed.c]: updated.

**Comment by tjaychen** [comment]
@moidx @alphan please have a look.
There are two things left:
1. how can we speed up the read verify (is it okay to use a define for now?)
2. how should we actually handle the scramble setup.

**Comment by tjaychen** [comment]
> @moidx @alphan please have a look. There are two things left:
> 
> 1. how can we speed up the read verify (is it okay to use a define for now?)
> 2. how should we actually handle the scramble setup.

i could also just keep the read verification for now... it's not critical that we have a way to remove it.  Maybe i can do that to make everyone's lives easier.

File: hw/top_earlgrey/dv/chip_sim_cfg.hjson [hunk 15]
```diff
@@ -383,6 +383,14 @@
       run_opts: ["+use_spi_load_bootstrap=1", "+calibrate_usb_clk=1"]
       run_timeout_mins: 180
     }
+    {
+      name: chip_sw_inject_scramble_seed
+      uvm_test_seq: chip_sw_inject_scramble_seed_vseq
+      sw_images: ["//sw/device/tests/sim_dv:inject_scramble_seed:1"]
+      en_run_modes: ["sw_test_mode_test_rom"]
+      run_opts: ["+lc_at_prod=1", "+flash_program_latency=5", "+sw_test_timeout_ns=150_000_000"]
```
Comment (cindychip) [inline hw/top_earlgrey/dv/chip_sim_cfg.hjson:391]: I will create an image for prod lc_state soon. Sorry for the inconvenience.

File: hw/top_earlgrey/dv/env/seq_lib/chip_sw_inject_scramble_seed_vseq.sv [hunk 16]
```diff
@@ -0,0 +1,71 @@
...
+
+  `uvm_object_new
+
+
+  virtual task dut_init(string reset_kind = "HARD");
+    super.dut_init(reset_kind);
+
+    // hint for rom to scramble
+    cfg.mem_bkdr_util_h[Otp].write32(otp_ctrl_reg_pkg::CreatorSwCfgFlashDataDefaultCfgOffset,
+                                     '0);
```
Comment (cindychip) [inline hw/top_earlgrey/dv/env/seq_lib/chip_sw_inject_scramble_seed_vseq.sv:16]: please correct me if I am wrong here - 
I thought `dut_init` only called once in this sequence, and in the img hjsons, you have already set this value to 0. Do you need to backdoor write it again?

File: sw/device/lib/testing/test_rom/test_rom.c [hunk 17]
```diff
@@ -122,7 +128,36 @@ bool rom_test_main(void) {
     LOG_INFO("Jitter is enabled");
   }
 
+#if !OT_IS_ENGLISH_BREAKFAST
+  // Check the otp to see if flash scramble should be enabled.
+  CHECK_DIF_OK(dif_otp_ctrl_init(
+      mmio_region_from_addr(TOP_EARLGREY_OTP_CTRL_CORE_BASE_ADDR), &otp_ctrl));
```
Comment (cindychip) [inline sw/device/lib/testing/test_rom/test_rom.c:134]: Nice! OTP init is in the test_rom now!
This is a comment for further enhancement, does not really apply to this PR :)
Do you think we can move it out of the `!OT_IS_ENGLISH_BREAKFAST` and just remove all the otp_init in chip level test?

**Review by cindychip — COMMENTED** [review]
DV side LGTM!

**Review by moidx — APPROVED** [review]

File: hw/top_earlgrey/dv/chip_sim_cfg.hjson (hunk 15 above)
Comment (tjaychen) [reply hw/top_earlgrey/dv/chip_sim_cfg.hjson:391]: no worries!

File: hw/top_earlgrey/dv/env/seq_lib/chip_sw_inject_scramble_seed_vseq.sv (hunk 16 above)
Comment (tjaychen) [reply hw/top_earlgrey/dv/env/seq_lib/chip_sw_inject_scramble_seed_vseq.sv:16]: yeah that's right, i actually don't need it here again.
I can't remember why I left it here. Maybe I did it just in case. I can remove it.

File: sw/device/lib/testing/test_rom/test_rom.c (hunk 17 above)
Comment (tjaychen) [reply sw/device/lib/testing/test_rom/test_rom.c:134]: o you mean persist the `otp_ctrl` declaration into the tests? 
I think @alphan / @timothytrippel can comment on that better, but I'm not sure if the stack is preserved between rom and ottf (effectively the rom_ext).  So even if I declare it global here, I'm not sure what additional things we need to do to pass it on.

However declaring it always as part of ottf would certainly be doable and we could remove it from all the downstream tests.  Maybe there's an argument to do that anyways, because we have situations inside the testutil where a handle is not passed in and they're doing it locally. 

@alphan / @timothytrippel let me know if I mis-characterized this.

Comment (timothytrippel) [reply sw/device/lib/testing/test_rom/test_rom.c:134]: Hmm I am little confused here, why do you need to call `dif_otp_ctrl_init()` and initialize a `otp_ctrl` DIF handle in the test ROM if you are just using an `abs_mmio_read32()` below?  it looks like the `otp_ctrl` DIF handle is unused in the test ROM, unless I am missing something?

Comment (tjaychen) [reply sw/device/lib/testing/test_rom/test_rom.c:134]: o oops, sorry that was legacy. I previously had been using a dif_routine to read, but then changed to absolute read.
Let me get rid of this.

File: sw/device/silicon_creator/rom/bootstrap.c (hunk 1 above)
Comment (alphan) [reply sw/device/silicon_creator/rom/bootstrap.c]: OK but since this is DV/sim specific, I don't think an OTP entry is the right approach. I'll keep this in mind when working on this.

File: sw/device/lib/testing/test_rom/test_rom.c (hunk 7 above)
Comment (alphan) [reply sw/device/lib/testing/test_rom/test_rom.c]: btw we also have `OT_ADDRESSABLE_LABEL`, not sure which one you prefer but that one is definitely leaner.

Comment (tjaychen) [reply sw/device/lib/testing/test_rom/test_rom.c]: i actually don't even know what that is. let me have a look.

Comment (alphan) [reply sw/device/lib/testing/test_rom/test_rom.c]: SG, just wanted to mention since it looked like it could also be used for this purpose.
