### PR TITLE
[sival,pwrmgr[ Add pwrmgr resets tests

### LINKED ISSUE #20135: [chip-test] chip_sw_pwrmgr_random_sleep_all_reset_reqs
### Test point name

[chip_sw_pwrmgr_random_sleep_all_reset_reqs](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson#L271)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [ ] Hyperdebug + CW310

### Contact person

matutem

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

### PR DESCRIPTION
**Pull request by matutem**
This has 10 simple commits, three commits each dealing with pwrmgr_*_sleep_reset_reqs and pwrmgr_*_sleep_por tests.
The three commits in each
- create the rust test harness
- move the C-code from tests/sim_dv to the parent
- create the cw310 bazel targets and add them to the testplan
The additional four commits:
- Change the pin for sysrst reset for for non-sim_dv targets
- Delay the sysrst synchronization message closer to the WFI
- Enable uart flow control on the C side for both reset_reqs and separately for por 

Fixes #20135

### CODE REVIEW

File: sw/device/tests/BUILD [hunk 1]
```diff
@@ -1622,6 +1590,219 @@ opentitan_test(
...
+        "//sw/device/lib/testing:rv_plic_testutils",
+        "//sw/device/lib/testing/test_framework:check",
+    ],
+)
+
+opentitan_test(
+    name = "pwrmgr_random_sleep_all_reset_reqs_test",
+    srcs = ["pwrmgr_random_sleep_all_reset_reqs_test.c"],
+    cw310 = new_cw310_params(
+        test_cmd = """
```
Comment (jdonjdon) [inline sw/device/tests/BUILD:1628]: Can you explain why you put line 1629,1630?

**Review by jdonjdon — APPROVED** [review]

**Comment by jdonjdon** [comment]
I think you have a trailing white space error in
Fixing file: "sw/host/tests/chip/pwrmgr/src/sleep_por.rs"

File: sw/device/tests/BUILD (hunk 1 above)
Comment (matutem) [reply sw/device/tests/BUILD:1628]: This seems needed by the BUILD rules: if we don't add some test_cmd the default command causes errors. You'll notice all tests that set a test_harness also add a test_cmd. I hope this will be fixed.

**Comment by matutem** [comment]
Trailng whitespace fixed.

File: sw/device/tests/BUILD (hunk 1 above)
Comment (pamaury) [reply sw/device/tests/BUILD:1628]: the default test_cmd assumes opentitantool, if you specify a test_harness, you almost always need to override the test_cmd since opentitantool and opentitanlib-based tests don't use the same command line arguments

File: sw/host/tests/chip/pwrmgr/src/sleep_por.rs [hunk 2]
```diff
@@ -0,0 +1,55 @@
...
+
+    /// Console receive timeout.
+    #[arg(long, value_parser = humantime::parse_duration, default_value = "600s")]
+    timeout: Duration,
+}
+
+// This test must be run manually since it
+fn sleep_por_test(opts: &Opts, transport: &TransportWrapper) -> Result<()> {
+    let uart = transport.uart("console")?;
+    uart.set_flow_control(true)?;
```
Comment (pamaury) [inline sw/host/tests/chip/pwrmgr/src/sleep_por.rs:27]: Control flow is not enabled on the device so this is not useful. If you need control flow for some reason, then you need
```c
OTTF_DEFINE_TEST_CONFIG(.enable_uart_flow_control = true);
```
in the C code.

**Comment by pamaury** [comment]
To debug the CI issue, I would suggest you add some logging on the Rust side. You can use `log::info!("this is a message")` to indicate were the Rust code is at and see where it gets stuck.

**Comment by matutem** [comment]
Thanks @pamaury, I think the message requesting a sysrst reset was sent too early, and the reset may not have been enabled. I moved it to the point right before going to sleep.

File: sw/host/tests/chip/pwrmgr/src/sleep_por.rs [hunk 3]
```diff
@@ -0,0 +1,55 @@
...
+struct Opts {
+    #[command(flatten)]
+    init: InitializeTest,
+
+    /// Console receive timeout.
+    #[arg(long, value_parser = humantime::parse_duration, default_value = "600s")]
+    timeout: Duration,
+}
+
+// This test must be run manually since it
```
Comment (pamaury) [inline sw/host/tests/chip/pwrmgr/src/sleep_por.rs:24]: This comment looks incomplete?

**Review by pamaury — APPROVED** [review]

File: sw/host/tests/chip/pwrmgr/src/sleep_por.rs (hunk 2 above)
Comment (matutem) [reply sw/host/tests/chip/pwrmgr/src/sleep_por.rs:26]: Done, thanks.
