### PR TITLE
[Sival, rv timer] Add the tick configuration test.

### LINKED ISSUE #19978: [chip-test, SiVal] RV_TIMER Tick configuration
### Test point name

[tick_configuration_test](https://github.com/lowRISC/opentitan/blob/365b6f9c4144ecc8753c58290e186bf80fca0254/hw/top_earlgrey/data/ip/chip_rv_timer_testplan.hjson#L25C9-L25C9)

### Host side component

None

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [x] CW310
- [x] Hyperdebug + CW310

### Contact person

matutem

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [x] Device-side (C) component developed
- [x] Bazel build rules developed
- [x] ~Host-side component developed~
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 2

### PR DESCRIPTION
**Pull request by engdoreis**
This PR:
 - Remove the 1ms test from the testplan because it would require a prescale bigger than available.
 - Reduce the test tolerance from 5% to 1%, this was empirically tested on the FPGA. 
 - Implement the test as described on the testplan.

Relates to #19978

### CODE REVIEW

File: sw/device/tests/rv_timer_systick_test.c [hunk 1]
```diff
@@ -0,0 +1,93 @@
...
+  TRY_CHECK(counter == 0, "Failed to write the counter");
+
+  TRY(dif_rv_timer_counter_set_enabled(&timer, kHart, kDifToggleEnabled));
+  busy_spin_micros(kReferenceTimeMicros);
+  TRY(dif_rv_timer_counter_set_enabled(&timer, kHart, kDifToggleDisabled));
+
+  TRY(dif_rv_timer_counter_read(&timer, kHart, &counter));
+  const uint64_t elapsed_micros = udiv64_slow(counter, tick_hz, NULL) * 1000000;
+
+  // Verify that `n * T ~= 1 second` within 1% of tolerance.
```
Comment (matutem) [inline sw/device/tests/rv_timer_systick_test.c:50]: The clocks in the AST are less accurate: they are spec'ed at +-3%. The fpga's clocks are better. You can expect 1% for kDeviceType == kDeviceFpgaCw310 (from sw/device/lib/arch/device.h). We will need to create a silicon device type, but its tolerance is expected to be similar to kDeviceSimDV.

**Review by matutem — APPROVED** [review]
Please relax the tolerance as requested so the test will run in silicon right away :)

File: hw/top_earlgrey/dv/chip_sim_cfg.hjson [hunk 2]
```diff
@@ -1050,6 +1050,12 @@
       sw_images: ["//sw/device/tests:rv_timer_smoketest:1"]
       en_run_modes: ["sw_test_mode_test_rom"]
     }
+    {
+      name: chip_sw_rv_timer_systick_test
+      uvm_test_seq: chip_sw_base_vseq
+      sw_images: ["//sw/device/tests:rv_timer_systick_test:1"]
```
Comment (moidx) [inline hw/top_earlgrey/dv/chip_sim_cfg.hjson:1056]: This in combination with the `opentitan_test` rule below.

```python
sw_images: ["//sw/device/tests:rv_timer_systick_test:1:new_rules"]
```

File: sw/device/tests/BUILD [hunk 3]
```diff
@@ -1691,6 +1691,20 @@ opentitan_functest(
...
+    deps = [
+        "//hw/top_earlgrey/sw/autogen:top_earlgrey",
+        "//sw/device/lib/dif:rv_timer",
+        "//sw/device/lib/runtime:hart",
+        "//sw/device/lib/runtime:ibex",
+        "//sw/device/lib/runtime:irq",
+        "//sw/device/lib/runtime:log",
+        "//sw/device/lib/testing/test_framework:ottf_main",
+    ],
+)
```
Comment (moidx) [inline sw/device/tests/BUILD:1706]: Use `opentitan_test` which will be rule supporting sival targets.

```python
opentitan_test(
    name = "rv_timer_systick_test",
    srcs = ["rv_timer_systick_test.c"],
    exec_env = EARLGREY_TEST_ENVS,
    deps = [
        "//hw/top_earlgrey/sw/autogen:top_earlgrey",
        "//sw/device/lib/dif:rv_timer",
        "//sw/device/lib/runtime:hart",
        "//sw/device/lib/runtime:ibex",
        "//sw/device/lib/runtime:irq",
        "//sw/device/lib/runtime:log",
        "//sw/device/lib/testing/test_framework:ottf_main",
    ],
)
```

**Review by moidx — APPROVED** [review]

File: sw/device/tests/BUILD (hunk 3 above)
Comment (engdoreis) [reply sw/device/tests/BUILD:1706]: Done

File: hw/top_earlgrey/dv/chip_sim_cfg.hjson [hunk 4]
```diff
@@ -1050,6 +1050,12 @@
       sw_images: ["//sw/device/tests:rv_timer_smoketest:1:new_rules"]
       en_run_modes: ["sw_test_mode_test_rom"]
     }
+    {
+      name: chip_sw_rv_timer_systick_test
+      uvm_test_seq: chip_sw_base_vseq
+      sw_images: ["//sw/device/tests:rv_timer_systick_test:1:new_rules"]
+      en_run_modes: ["sw_test_mode_test_rom"]
```
Comment (engdoreis) [inline hw/top_earlgrey/dv/chip_sim_cfg.hjson:1057]: @matutem, I'm running with dvsim before merging. It's taking more than one hour already and has not finished. Is it worth running this test in simulation?

Comment (matutem) [reply hw/top_earlgrey/dv/chip_sim_cfg.hjson:1057]: Yes, but you may want to avoid the longer times. See the suggestion in rv_timer_systick_test.

File: sw/device/tests/rv_timer_systick_test.c [hunk 5]
```diff
@@ -0,0 +1,93 @@
...
+      100 * 1000,       // 100kHz - 10us.
+      40 * 1000,        // 40kHz - 25us.
+      20 * 1000,        // 20kHz - 50us.
+      10 * 1000,        // 10kHz - 100us.
+      8 * 1000,         // 8kHz - 125us.
+      4 * 1000,         // 4kHz - 250us.
+      2 * 1000,         // 2kHz - 500us.
+  };
+
+  for (size_t i = 0; i < ARRAYSIZE(kTickHz); ++i) {
```
Comment (matutem) [inline sw/device/tests/rv_timer_systick_test.c:88]: Imagine the values i >= ARRAYSIZE(..) - 2 take too long to simulate. Include lib/arch/device.h, and do something like:

  size_t end_tick = kDeviceType == kDeviceSimDV ? ARRAYSIZE(..) - 2 : ARRAYSIZE(..);
  for (size_t i = 0; i < end_tick; ++i) {
    ....
  }

**Review by pamaury — APPROVED** [review]

**Comment by engdoreis** [comment]
The "CI (Hyperdebug CW310 Tests (Experimental))" failed but due to a flakness, so I'll merge the PR.
