### PR TITLE
[sysrst,sival] Port sysrst_ctrl_ulp_z3_wakeup

### LINKED ISSUE #19861: [chip-test] chip_sw_sysrst_ctrl_ulp_wakeup
### Test point name

[chip_sw_sysrst_ctrl_ulp_wakeup](https://github.com/lowRISC/opentitan/blob/cf8ffa811189c6c17285abae7eef19081213f739/hw/top_earlgrey/data/ip/chip_sysrst_ctrl_testplan.hjson#L64)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [X] Hyperdebug + CW310

### Contact person

crteja

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 2

### PR DESCRIPTION
**Pull request by pamaury**
The sival test goes a bit further than the DV and testplan. The testplan requires to check that a L2H transition on `lid_open_i` triggers a wakeup. The sysrst_ctrl block supports two other wakeup sources: a high level on the `ac_present_i` signal and a H->L transition on the `pwrb_in_i` signal. The sival test exercises those other two sources as well.

Fixes #19861

### CODE REVIEW

File: sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ulp_z3_wakeup.rs [hunk 1]
```diff
@@ -0,0 +1,195 @@
...
+fn main() -> Result<()> {
+    let opts = Opts::parse();
+    opts.init.init_logging();
+    let transport = opts.init.init_target()?;
+
+    /* Load the ELF binary and get the address of the `kPhase` variable
+     * in example_sival.c */
+    let elf_binary = fs::read(&opts.firmware_elf)?;
+    let elf_file = object::File::parse(&*elf_binary)?;
+    let mut symbols = HashMap::<String, (u32, u64)>::new();
```
Comment (jwnrt) [inline sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_ulp_z3_wakeup.rs:143]: NIT: This is fine so don't bother changing it, but might be simpler to do something like this for just one symbol:

```rust
elf_file
    .symbols()
    .find(|symbol| symbol.name() == Ok("kTestPhaseReal"))
    .expect("Provided ELF missing 'kTestPhaseReal' symbol")
    .address()
```

**Review by jwnrt — CHANGES_REQUESTED** [review]
Oops, I mean to request changes because of that `&& false`

File: sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl.rs
[the remark this answers is not in the document]
Comment (pamaury) [reply sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl.rs:1]: It seems a little bit specific to the tests: fundamentally it has little to do with sysrst_ctrl, it's just a common way to setup pins so that the sival and DV tests remain quite close.

File: sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c [hunk 2]
```diff
@@ -15,13 +15,19 @@
...
+/* We need control flow for the ujson messages exchanged
+ * with the host in OTTF_WAIT_FOR on real devices. */
+OTTF_DEFINE_TEST_CONFIG(.enable_uart_flow_control = true);
 
-// This is updated by the sv component of the test
-static volatile const uint8_t kTestPhase[1];
+// This is updated by the sv component of the test.
+// On DV, we must use variables in flash but on a real device,
+// we must use variables in RAM.
+static volatile const uint8_t kTestPhaseDV[1];
```
[the remark this answers is not in the document]
Comment (pamaury) [reply sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c:29]: I have no idea, I don't see why the DV code is doing that but I decided to keep it.

File: sw/host/opentitanlib/src/uart/console.rs [hunk 3]
```diff
@@ -56,7 +56,7 @@ impl UartConsole {
         if let Some(timeout) = &self.timeout {
             self.deadline = Some(Instant::now() + *timeout);
         }
-        if device.supports_nonblocking_read()? {
+        if device.supports_nonblocking_read()? && false {
```
[the remark this answers is not in the document]
Comment (pamaury) [reply sw/host/opentitanlib/src/uart/console.rs:59]: ah yes, good catch

File: hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ulp_z3_wakeup_vseq.sv [hunk 4]
```diff
@@ -69,7 +69,7 @@ class chip_sw_sysrst_ctrl_ulp_z3_wakeup_vseq extends chip_sw_base_vseq;
     bit [7:0] test_phase[1];
     test_phase[0] = phase;
     `uvm_info(`gfn, $sformatf("Writing test phase %0d", phase), UVM_MEDIUM)
-    sw_symbol_backdoor_overwrite("kTestPhase", test_phase);
+    sw_symbol_backdoor_overwrite("kTestPhaseDV", test_phase);
```
Comment (rswarbrick) [inline hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ulp_z3_wakeup_vseq.sv:72]: Doesn't this change need squashing with "[sysrs_ctrl,dv] Remove the "glitch lid open" phase", which changed the names?

File: sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (rswarbrick) [reply sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c:29]: Do we have something silly that needs the symbol with the name `kTestPhaseDV` to be a pointer to the test phase (so that it can be overridden)?

**Review by rswarbrick — COMMENTED** [review]
This looks sensible to me. Nitty question about what goes in which commit.

File: sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (pamaury) [reply sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c:29]: I don't think so but I don't know the DV side really well.

File: hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ulp_z3_wakeup_vseq.sv (hunk 4 above)
Comment (pamaury) [reply hw/top_earlgrey/dv/env/seq_lib/chip_sw_sysrst_ctrl_ulp_z3_wakeup_vseq.sv:72]: ah, I must have put it in the wrong commit

File: sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c [hunk 5]
```diff
@@ -15,13 +15,19 @@
...
+static volatile uint8_t kTestPhaseReal = 0;
```
Comment (engdoreis) [inline sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c:30]: It's not const:
```suggestion
static volatile uint8_t test_phase_real = 0;
```

File: sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c [hunk 6]
```diff
@@ -51,30 +58,44 @@ static const dif_pinmux_index_t kPeripheralInputs[] = {
...
+static const dif_pinmux_index_t kOutputPadsReal[] = {
+    kTopEarlgreyPinmuxMioOutIor5,
+};
+
 /**
  * Sets up the pinmux to assign input and output pads to the sysrst_ctrl
  * peripheral as required.
  */
 static void pinmux_setup(void) {
+  const dif_pinmux_index_t *kInputPads =
```
Comment (engdoreis) [inline sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c:90]: I'm not sure, is `kInputPads` a compile time const? If not it should use snake_case .

**Review by engdoreis — APPROVED** [review]

File: sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c (hunk 5 above)
Comment (pamaury) [reply sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c:30]: This variable is a bit weird: like `kTestPhaseDV`, it is backdoor-written to by the host using the OTTF and so must not be written by the device code. But it is not declared `const` so that the compiler will put it in RAM and not flash. I guess alternatively I could do
```c
// This variable must go to RAM so that the host can change it's value using the OTTF.
OT_SECTION(".data")
static volatile const uint8_t kTestPhaseReal = 0;
```
if you think that's clearer?

File: sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c (hunk 6 above)
Comment (pamaury) [reply sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c:90]: It is in the sense that `kDeviceType` is a constant variable defined in the arch header. Unfortunately, it is not technically a "constant expression" in the C sense because `kDeviceSimDV` is a const variable and not a macro, therefore `kInputPads` cannot be defined at the global scope.

File: sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c (hunk 5 above)
Comment (rswarbrick) [reply sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c:30]: I think I'd probably go for that change, since it's a bit more explicit (and doesn't require someone to have the "const vs non-const" / linker script rules in their head!)

File: sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c (hunk 2 above)
[the remark this answers is not in the document]
Comment (pamaury) [reply sw/device/tests/sysrst_ctrl_ulp_z3_wakeup_test.c:30]: I have updated the code.

File: sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl.rs [hunk 7]
```diff
@@ -50,3 +50,17 @@ pub fn set_pins(transport: &TransportWrapper, config: &Config, values: u8) -> Re
     }
     Ok(())
 }
+
+/// Read pins: the i-th bit of `values` corresponds to the i-th entry of `config.input_pins`.
+#[allow(dead_code)]
+pub fn read_pins(transport: &TransportWrapper, config: &Config) -> Result<u8> {
+    let mut values = 0u8;
+    // Set pins on the transport.
+    for (i, pin) in config.input_pins.iter().enumerate() {
```
Comment (jwnrt) [inline sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl.rs:59]: Should we add something like `ensure!(config.input_pins.len() <= 8);` just to avoid silent bugs where we overflow the `u8`?

File: sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl.rs [hunk 8]
```diff
@@ -50,3 +50,17 @@ pub fn set_pins(transport: &TransportWrapper, config: &Config, values: u8) -> Re
     }
     Ok(())
 }
+
+/// Read pins: the i-th bit of `values` corresponds to the i-th entry of `config.input_pins`.
+#[allow(dead_code)]
```
Comment (jwnrt) [inline sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl.rs:55]: Please can you remove this attribute in the next commit since it gets used?

**Review by jwnrt — APPROVED** [review]
LGTM modulo a couple of suggestions, thanks!

File: sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl.rs (hunk 8 above)
Comment (pamaury) [reply sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl.rs]: Done, but I had to turn this into a proper crate between it is used in several tests but not all routines are used in every test.

**Review by engdoreis — APPROVED** [review]
