### PR TITLE
[sival,pwrmgr] Port pwrmgr_random_sleep_all_wake_ups test

### LINKED ISSUE #20058: [chip-test] chip_sw_pwrmgr_random_sleep_all_wake_ups
### Test point name

[chip_sw_pwrmgr_random_sleep_all_wake_ups](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [ ] Hyperdebug + CW310

### Contact person

matutem

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

### PR DESCRIPTION
**Pull request by matutem**
Create a host side harness.
Change the C-side to use a cw310 friendly pad.

Fixes #20058

### CODE REVIEW

File: sw/device/tests/BUILD [hunk 1]
```diff
@@ -390,10 +390,18 @@ opentitan_test(
 opentitan_test(
     name = "pwrmgr_random_sleep_all_wake_ups",
     srcs = ["pwrmgr_random_sleep_all_wake_ups.c"],
-    exec_env = {"//hw/top_earlgrey:sim_dv": None},
+    cw310 = new_cw310_params(
+        test_cmd= "--bootstrap={firmware}",
```
Comment (a-will) [inline sw/device/tests/BUILD:394]: This probably needs a --bitstream to be programmed:

```suggestion
        test_cmd= " ".join([
            "--bootstrap=\"{firmware}\"",
            "--bitstream=\"{bitstream}\"",
        ]),
```

Comment (matutem) [reply sw/device/tests/BUILD]: Done

File: sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_wake_ups.c [hunk 2]
```diff
@@ -53,14 +53,18 @@ bool test_main(void) {
...
+      }
       LOG_INFO("Test %d begin", i);
       execute_test(i, /*deep_sleep=*/false);
       check_wakeup_reason(i);
       LOG_INFO("Woke up by source %d", i);
       cleanup(i);
       LOG_INFO("clean up done source %d", i);
     }
-
+    LOG_INFO("Done");
```
Comment (timothytrippel) [inline sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_wake_ups.c:67]: when the test returns true, the ottf will already print "pass" / "fail" to the console, which can be picked up manually, or using the UartConsole struct and a match expression, like here: https://cs.opensource.google/opentitan/opentitan/+/master:sw/host/tests/chip/power_virus/src/main.rs;drc=f6ce5b96271e414b01c103e568d392aafbcc1f7a;l=29

Perhaps we should turn lines 29--61 [here](https://cs.opensource.google/opentitan/opentitan/+/master:sw/host/tests/chip/power_virus/src/main.rs;drc=f6ce5b96271e414b01c103e568d392aafbcc1f7a;l=29) into an opentitanlib testutil to make this test exit scheme reusable across tests?

File: sw/host/tests/chip/pwrmgr/src/sleep_all_wakeups.rs [hunk 3]
```diff
@@ -0,0 +1,57 @@
...
+        }
+        let gs = UartConsole::wait_for(&*uart, r"Woke up by source ([0-9]+)", opts.timeout)?;
+        assert_eq!(gs.len(), 2, "Expected unit number");
+        let sleep_case: i32 = gs[1].parse().expect("expected a number");
+        match sleep_case {
+            0 => ioc0_pin.write(true)?,
+            2 => ioc0_pin.write(false)?,
+            _ => (),
+        }
+    }
```
Comment (timothytrippel) [inline sw/host/tests/chip/pwrmgr/src/sleep_all_wakeups.rs:56]: typical practice is to wrap this in a function, then invoke the function with the `execute_test!` macro, like here: https://cs.opensource.google/opentitan/opentitan/+/master:sw/host/tests/chip/jtag/src/openocd_test.rs;drc=2bd1d75d9ebb81877cb851b038ef95f80a558b88;l=217

**Review by timothytrippel — APPROVED** [review]

File: hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson [hunk 4]
```diff
@@ -69,7 +69,7 @@
         "PWRMGR.LOW_POWER.WAKE_INFO"
       ]
       tests: ["chip_sw_pwrmgr_random_sleep_all_wake_ups"]
-      bazel: []
+      bazel: ["//sw/device/tests:pwrmgr_random_sleep_all_wake_ups_fpga_cw310_test_rom"]
```
Comment (a-will) [inline hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson:72]: Random / off-topic: Is this testplan file actually supposed to be geared towards the FPGA? It seems a bit peculiar to call out the CW310's execution environment explicitly. I'm not sure how this file is actually used, though--If it's merely documentation, then perhaps it doesn't matter.

File: sw/host/tests/chip/pwrmgr/src/sleep_all_wakeups.rs [hunk 5]
```diff
@@ -0,0 +1,57 @@
...
+    opts.init.init_logging();
+    let transport = opts.init.init_target()?;
+
+    let uart = transport.uart("console")?;
+    uart.set_flow_control(true)?;
+    let ioc0_pin = transport.gpio_pin("Ioc0")?;
+    loop {
+        let gs = UartConsole::wait_for(&*uart, r"Done|Issue WFI to enter sleep ([0-9]+)", opts.timeout)?;
+        if gs[0] == "Done" {
+            return Ok(());
```
Comment (a-will) [inline sw/host/tests/chip/pwrmgr/src/sleep_all_wakeups.rs:33]: FYI: We have specific strings we conventionally wait for.

https://github.com/lowRISC/opentitan/blob/f419160a3d5e356a23038ca88d2cbb9a143d82d5/rules/opentitan_test.bzl#L55-L57

**Review by a-will — APPROVED** [review]
LGTM, with nits, but I don't feel strongly about them.

File: hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson (hunk 4 above)
Comment (matutem) [reply hw/top_earlgrey/data/ip/chip_pwrmgr_testplan.hjson:72]: It is really an indication that a non-sim-dv test is running, which is a strong hint that it may not be much more work for it to be silicon ready.

Incidentally, do we have a bazel target that corresponds to a silicon test? Even if we did, we would not be able to run it.

File: sw/device/tests/pwrmgr_random_sleep_all_wake_ups.c [hunk 6]
```diff
@@ -71,40 +73,63 @@ bool test_main(void) {
...
-    CHECK_STATUS_OK(ret_sram_testutils_counter_get(0, &wakeup_count));
-    wakeup_unit = get_wakeup_unit(wakeup_count);
-    deep_sleep = get_deep_sleep(wakeup_count);
-    delay_n_clear(4);
-    execute_test(wakeup_unit, deep_sleep);
+  dif_pwrmgr_wakeup_reason_t wakeup_reason;
+  CHECK_DIF_OK(dif_pwrmgr_wakeup_reason_get(&pwrmgr, &wakeup_reason));
+
+  if (wakeup_reason.request_sources == 0) {
+    // Clear any interrupt that may be pending.
```
[the remark this answers is not in the document]
Comment (matutem) [reply sw/device/tests/pwrmgr_random_sleep_all_wake_ups.c:80]: You are right, the comment makes no sense. Changed.

File: sw/device/tests/pwrmgr_random_sleep_all_wake_ups.c [hunk 7]
```diff
@@ -71,40 +73,63 @@ bool test_main(void) {
...
-        return true;
-      }
-      CHECK_STATUS_OK(ret_sram_testutils_counter_increment(0));
-      CHECK_STATUS_OK(ret_sram_testutils_counter_get(0, &wakeup_count));
-      wakeup_unit = get_wakeup_unit(wakeup_count);
-      deep_sleep = get_deep_sleep(wakeup_count);
-      delay_n_clear(4);
-      execute_test(wakeup_unit, deep_sleep);
+    CHECK(deep_sleep, "Should be deep sleep");
+    check_wakeup_reason(wakeup_unit);
```
[the remark this answers is not in the document]
Comment (matutem) [reply sw/device/tests/pwrmgr_random_sleep_all_wake_ups.c:93]: Good point. The header was missing comments. The pwrmgr dif calls these wakeup_reason, so the name seems okay. Comment added.

File: sw/device/tests/pwrmgr_random_sleep_all_wake_ups.c [hunk 8]
```diff
@@ -71,40 +73,63 @@ bool test_main(void) {
...
+    LOG_INFO("Woke up by source %d", wakeup_unit);
+    cleanup(wakeup_unit);
```
[the remark this answers is not in the document]
Comment (matutem) [reply sw/device/tests/pwrmgr_random_sleep_all_wake_ups.c:95]: It was no worse than TearDown :)
The comment will help, and renamed it to clear_wakeup. Thanks.

File: sw/device/tests/sim_dv/pwrmgr_sleep_all_wake_ups_impl.h [hunk 9]
```diff
@@ -26,6 +26,11 @@
 #include "sw/device/lib/testing/test_framework/check.h"
 #include "sw/device/lib/testing/test_framework/ottf_main.h"
 
+/**
+ * The non-volatile counter used in this test.
```
[the remark this answers is not in the document]
Comment (matutem) [reply sw/device/tests/sim_dv/pwrmgr_sleep_all_wake_ups_impl.h:30]: Well, retention sram is more specific.

File: sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_wake_ups.c (hunk 2 above)
Comment (matutem) [reply sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_wake_ups.c:67]: I don't think that will work: the power virus test is only waiting for a pass or fail, plus timeouts and Ctrl-C. This test is waiting for that and all sorts of other messages that will trigger some activity. Am I missing something?

File: sw/host/tests/chip/pwrmgr/src/sleep_all_wakeups.rs (hunk 5 above)
Comment (matutem) [reply sw/host/tests/chip/pwrmgr/src/sleep_all_wakeups.rs:33]: I removed the Done string, and I match PASS instead. What is a good example for handling all the other failure cases? It would be a bunch of regex alternatives. I suppose I'd have to pass a failure_rx arg to wait_for? Also, opentitanlib is injecting a PASS or FAIL string. Does it wrap the Fail in ExitStatus::ExitFailure? I am calling `wait_for(..)?` so I expected the ? to catch the not-okay cases...

File: sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_wake_ups.c (hunk 2 above)
Comment (matutem) [reply sw/device/tests/sim_dv/pwrmgr_normal_sleep_all_wake_ups.c]: However, I can see how to straighten up the test body to better handle the regex and ExitStatus... In some other PR...

File: sw/host/tests/chip/pwrmgr/src/sleep_all_wakeups.rs (hunk 3 above)
Comment (matutem) [reply sw/host/tests/chip/pwrmgr/src/sleep_all_wakeups.rs]: Done
