### PR TITLE
[sival,clkmgr] Add test for chip_sw_clkmgr_jitter_cycle_measurements testpoint

### LINKED ISSUE #20230: [chip_sw_clkmgr_jitter]
### Test point name

[chip_sw_clkmgr_jitter_cycle_measurements](https://github.com/lowRISC/opentitan/blob/master/hw/top_earlgrey/data/ip/chip_clkmgr_testplan.hjson#L235)

### Host side component

None Required

### OpenTitanTool infrastructure implemented

None

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [X] CW310
- [ ] Hyperdebug + CW310

### Contact person

matutem

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [ ] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [ ] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

### PR DESCRIPTION
**Pull request by matutem**
Fixes #20230

### CODE REVIEW

File: sw/device/lib/testing/clkmgr_testutils.c [hunk 1]
```diff
@@ -37,9 +37,14 @@ static expected_count_info_t kNoJitterCountInfos[kDifClkmgrMeasureClockUsb + 1];
 static expected_count_info_t kJitterCountInfos[kDifClkmgrMeasureClockUsb + 1];
 
 // The expected variability as a percentage. The AST guarantees 3% for all
-// clocks, including the AON, so this sets the effective variability to 5%.
+// clocks, including the AON, so the effective variability is set to 5%.
 static uint32_t kVariabilityPercentage = 5;
 
+// The expected variability when jitter is enabled as a percentage. The AST
+// guarantees 10% for jittery clocks and 3% for the AON clock, so the
+// effective variability is set to 12%.
```
Comment (rswarbrick) [inline sw/device/lib/testing/clkmgr_testutils.c:45]: When I read this the first time, I was confused (because 10% + 3% != 12%). This was silly of me! I wonder whether making the last bit something like "... is set to 12%, larger than either type of clock." would have avoided me being confused :-)

File: sw/device/tests/clkmgr_jitter_frequency_test.c [hunk 2]
```diff
@@ -0,0 +1,108 @@
...
+#include "sw/device/lib/testing/test_framework/check.h"
+#include "sw/device/lib/testing/test_framework/ottf_main.h"
+
+#include "hw/top_earlgrey/sw/autogen/top_earlgrey.h"
+#include "sw/device/lib/testing/autogen/isr_testutils.h"
+
+OTTF_DEFINE_TEST_CONFIG();
+
+/**
+ * This test measure clock counts with clkmgr frequency measurements and with
```
Comment (rswarbrick) [inline sw/device/tests/clkmgr_jitter_frequency_test.c:23]: Nit: I think this should be "measures"

File: sw/device/tests/clkmgr_jitter_frequency_test.c [hunk 3]
```diff
@@ -0,0 +1,108 @@
...
+ * jitter enabled, performing 100 measurements per round. Measurement errors
+ * (fast or slow clocks) are recorded as recoverable error in clkmgr.
```
Comment (rswarbrick) [inline sw/device/tests/clkmgr_jitter_frequency_test.c:25]: Nit: I think this should be "as recoverable errors"

File: sw/device/tests/clkmgr_jitter_frequency_test.c [hunk 4]
```diff
@@ -0,0 +1,108 @@
...
+        "IRQ peripheral: %d is incorrect", peripheral);
+  CHECK(irq_id == kDifPwrmgrIrqWakeup, "IRQ ID: %d is incorrect", irq_id);
+}
+
+bool test_main(void) {
+  dif_sensor_ctrl_t sensor_ctrl;
+
+  uint32_t delay_micros = 0;
+  CHECK_STATUS_OK(aon_timer_testutils_get_us_from_aon_cycles(
+      kMeasurementsPerRound, &delay_micros));
```
Comment (rswarbrick) [inline sw/device/tests/clkmgr_jitter_frequency_test.c:74]: I'm not certain I understand this. I think this function converts a number of cycles to a number of microseconds. If I understand correctly, `kMeasurementsPerRound` is supposed to be interpreted as a number of AON clock cycles here. Maybe it would make sense to add a note either here or on the definition of `kMeasurementsPerRound` to explain how a measurement corresponds to an aon clkc cycle.

File: sw/device/tests/clkmgr_jitter_frequency_test.c [hunk 5]
```diff
@@ -0,0 +1,108 @@
...
+  CHECK_STATUS_OK(clkmgr_testutils_enable_clock_counts_with_expected_thresholds(
+      &clkmgr, /*jitter_enabled=*/true, /*external_clk=*/false,
+      /*low_speed=*/false));
+  busy_spin_micros(delay_micros);
+
+  // check results
+  CHECK_STATUS_OK(clkmgr_testutils_check_measurement_counts(&clkmgr));
+  CHECK_STATUS_OK(clkmgr_testutils_disable_clock_counts(&clkmgr));
+
+  CHECK(!isr_entered);
```
Comment (rswarbrick) [inline sw/device/tests/clkmgr_jitter_frequency_test.c:105]: Another bit that I don't understand yet. I think the point is that we want to make sure there wasn't an IRQ while we were waiting for 100 AON cycles. If that's the case, do we ever want the body of the ISR to run on a passing test? (If not, maybe we can drop some of the CHECK lines?)

Comment (matutem) [reply sw/device/tests/clkmgr_jitter_frequency_test.c:105]: We never expect an interrupt. I guess if I remove ottf_external_isr and we took an interrupt the test should fail.

File: sw/device/lib/testing/clkmgr_testutils.c (hunk 1 above)
Comment (matutem) [reply sw/device/lib/testing/clkmgr_testutils.c:45]: I added a comment that should clarify the "math" involved :)

File: sw/device/tests/clkmgr_jitter_frequency_test.c (hunk 4 above)
Comment (matutem) [reply sw/device/tests/clkmgr_jitter_frequency_test.c:74]: I added text explaining a round is an AON cycle in the test description above kMeasurementsPerRound.

File: sw/device/tests/clkmgr_jitter_frequency_test.c (hunk 3 above)
Comment (matutem) [reply sw/device/tests/clkmgr_jitter_frequency_test.c]: Done.

File: sw/device/tests/clkmgr_jitter_frequency_test.c (hunk 2 above)
Comment (matutem) [reply sw/device/tests/clkmgr_jitter_frequency_test.c]: Done, thanks.

**Review by msfschaffner — APPROVED** [review]

File: sw/device/tests/clkmgr_jitter_frequency_test.c (hunk 4 above)
Comment (rswarbrick) [reply sw/device/tests/clkmgr_jitter_frequency_test.c:44]: Ahah, that's what I'd missed! Thanks for explaining things.
