### PR TITLE
[sival] sysrst_ctrl_in_irq test

### LINKED ISSUE #19860: [chip-test] chip_sw_sysrst_ctrl_input_interrupt
### Test point name

[chip_sw_sysrst_ctrl_input_interrupt](https://github.com/lowRISC/opentitan/blob/cf8ffa811189c6c17285abae7eef19081213f739/hw/top_earlgrey/data/ip/chip_sysrst_ctrl_testplan.hjson#L47)

### Host side component

Rust

### OpenTitanTool infrastructure implemented

Yes

### Silicon Validation (SiVal)

Yes

### Emulation Targets

- [ ] None
- [ ] CW310
- [x] Hyperdebug + CW310

### Contact person

crteja

### Checklist

Please fill out this checklist as items are completed. Link to PRs and issues as appropriate.
- [x] Check if existing test covers most or all of this testpoint (if so, either extend said test to cover all points, or skip the next 3 checkboxes)
- [ ] Device-side (C) component developed
- [ ] Bazel build rules developed
- [ ] Host-side component developed
- [x] HJSON test plan updated with test name (so it shows up in the dashboard)
- [ ] Test added to dvsim nightly regression (and passing at time of checking)
- [ ] For SiVal test cases, test is running relevant FPGA or silicon regression

> estimate 2

### PR DESCRIPTION
**Pull request by pamaury**
See commits for explanation of the various changes.

@matutem can you check if my function `wait_for_any_interrupt` is correct?

I wonder if the `setup_dio_pins` function should be part of the sysrst DIF? It seems like a useful and nontrivial routine.

Fixes #19860

### CODE REVIEW

**Review by rswarbrick — COMMENTED** [review]
Minor nitty style questions. And it's fun to properly read some Rust :-)

File: sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_inputs.rs [hunk 1]
```diff
@@ -12,13 +12,17 @@ use std::time::Duration;
 
 use object::{Object, ObjectSymbol};
 use opentitanlib::app::TransportWrapper;
-use opentitanlib::io::gpio::{PinMode, PullMode};
+use opentitanlib::io::uart::Uart;
```
[the remark this answers is not in the document]
Comment (pamaury) [reply sw/host/tests/chip/sysrst_ctrl/sysrst_ctrl_inputs.rs:15]: Yes, same as above.

File: sw/device/tests/sysrst_ctrl_in_irq_test.c [hunk 2]
```diff
@@ -12,30 +12,42 @@
...
-static volatile const uint8_t kCurrentTestPhase = 0;
+// On DV, we must use variables in flash but on a real device,
+// we must use variables in RAM.
+static volatile const uint8_t kCurrentTestPhaseDV = 0;
+// In DV, the sequence can ensure that the pins are set even before the test
+// runs. On a real device, this is not the case and if the initial value of
+// kCurrentTestPhaseReal is 0, the very first OTTF_WAIT_FOR could succeed before
+// the host can set the pins. To avoid this, and only on real devices, set the
+// initial value to an invalid value so that we have to wait for the host.
+static volatile uint8_t kCurrentTestPhaseReal = 0xff;
```
[the remark this answers is not in the document]
Comment (pamaury) [reply sw/device/tests/sysrst_ctrl_in_irq_test.c:45]: Ok, I will change that

[the remark this answers is not in the document]
Comment (rswarbrick) [reply sw/device/tests/sysrst_ctrl_in_irq_test.c]: I think the signals are still separated by the larger comment. Would it make sense to move `kCurrentTestPhaseDV` to appear on the line before `kCurrentTestPhaseReal`?

File: sw/device/tests/sysrst_ctrl_in_irq_test.c [hunk 3]
```diff
@@ -124,15 +191,21 @@ void sysrst_ctrl_key_combo_detect(dif_sysrst_ctrl_key_combo_t key_combo,
   CHECK_DIF_OK(dif_sysrst_ctrl_key_combo_detect_configure(
       &sysrst_ctrl, key_combo, sysrst_ctrl_key_combo_config));
 
+  LOG_INFO("tell host we a ready");
```
[the remark this answers is not in the document]
Comment (rswarbrick) [reply sw/device/tests/sysrst_ctrl_in_irq_test.c]: Oh! It's the same on line 126 as well. Would you mind fixing that too?

File: sw/device/tests/sysrst_ctrl_in_irq_test.c [hunk 4]
```diff
@@ -124,15 +191,21 @@ void sysrst_ctrl_key_combo_detect(dif_sysrst_ctrl_key_combo_t key_combo,
...
   test_phase_sync();
 
-  IBEX_SPIN_FOR(phase++ == kCurrentTestPhase, kCurrentTestPhaseTimeoutUsec);
+  // LOG_INFO("wait for host to send the glitch");
```
[the remark this answers is not in the document]
Comment (rswarbrick) [reply sw/device/tests/sysrst_ctrl_in_irq_test.c:196]: The comment is still there at the moment (line 196). Maybe it can still be deleted?

File: sw/device/tests/sysrst_ctrl_lib.c [hunk 5]
```diff
@@ -0,0 +1,68 @@
+// Copyright lowRISC contributors.
```
Comment (matutem) [inline sw/device/tests/sysrst_ctrl_lib.c:1]: I think this code should be moved to sw/device/lib/testing/sysrst_ctrl_testutils.[ch].

File: sw/device/tests/sysrst_ctrl_in_irq_test.c [hunk 6]
```diff
@@ -47,25 +59,61 @@ static const dif_pinmux_index_t kPeripheralInputs[] = {
...
 
+static void wait_for_any_interrupt(void) {
+  // Disable interrupts to be certain interrupt doesn't occur between while
+  // condition check and `wait_for_interrupt` (so WFI misses that interrupt).
+  irq_global_ctrl(false);
+
+  // Only enter WFI loop if we haven't already seen the interrupt.
+  while (peripheral == UINT32_MAX) {
+    wait_for_interrupt();
+    // WFI ignores global interrupt enable, so enable it now and then
```
Comment (matutem) [inline sw/device/tests/sysrst_ctrl_in_irq_test.c:89]: The WFI instruction is funny, since it is meant to ignore mstatus *ie bits, so it is not clear what this code accomplishes.
 I guess the intent is to continue to wait for interrupts until we get the one that sets peripheral? But then why bother calling irq_global_ctrl?

**Review by timothytrippel — APPROVED** [review]

File: sw/device/tests/sysrst_ctrl_in_irq_test.c (hunk 6 above)
Comment (pamaury) [reply sw/device/tests/sysrst_ctrl_in_irq_test.c:89]: This is to guard against the case where the interrupt was called before we wait for an interrupt: in this case the wait for interrupt will block forever. This means we have to check for the value of `peripheral` but we need to do so atomically because the interrupt could happen between the check and the call to wfi. The point of calling irq_global_ctrl is to control where the interrupt is called so that we can atomically check the `peripheral` variable. Hopefully this makes sense?

File: sw/device/tests/sysrst_ctrl_lib.c (hunk 5 above)
Comment (pamaury) [reply sw/device/tests/sysrst_ctrl_lib.c]: done

File: sw/device/tests/sysrst_ctrl_in_irq_test.c (hunk 6 above)
Comment (matutem) [reply sw/device/tests/sysrst_ctrl_in_irq_test.c:89]: You explanation here is clearer than the comments. Perhaps the comments could be improved?

**Review by matutem — APPROVED** [review]
I'll leave it up to you to deal with the comments in wait_for_any_interrupt. Otherwise LGTM.

File: sw/device/tests/sysrst_ctrl_in_irq_test.c (hunk 6 above)
Comment (pamaury) [reply sw/device/tests/sysrst_ctrl_in_irq_test.c:89]: Thanks @matutem , I will change the comment.

Comment (pamaury) [reply sw/device/tests/sysrst_ctrl_in_irq_test.c]: I have updated the comment, hopefully this is better.
