### PR TITLE
Fix pwrmgr_sleep_all_wake_ups

### LINKED ISSUE #23303: [test-triage] chip_sw_pwrmgr_normal_sleep_all_wake_ups is flaky
### Hierarchy of regression failure

Chip level

### Failure Description

```
UVM_INFO @ 2576.271356 us: (sw_logger_if.sv:524) [test_rom_sim_dv(sw/device/lib/testing/test_framework/status.c:40)] test_status_set to 0xb090
UVM_INFO @ 2576.571356 us: (sw_test_status_if.sv:61) [tb.u_sim_sram.u_sim_sram_if.u_sw_test_status_if] SW test transitioned to SwTestStatusInBootRom.
UVM_INFO @ 2837.961356 us: (sw_logger_if.sv:524) [test_rom_sim_dv(sw/device/lib/testing/test_rom/test_rom.c:158)] kChipInfo: scm_revision=54697461
UVM_INFO @ 2844.371356 us: (sw_logger_if.sv:524) [test_rom_sim_dv(sw/device/lib/testing/test_rom/test_rom.c:230)] Test ROM complete, jumping to flash (addr: 20000480)!
UVM_INFO @ 2853.541356 us: (sw_logger_if.sv:524) [pwrmgr_normal_sleep_all_wake_ups_sim_dv(w/device/lib/testing/test_framework/status.c:40)] test_status_set to 0x4354
UVM_INFO @ 2853.821356 us: (sw_test_status_if.sv:61) [tb.u_sim_sram.u_sim_sram_if.u_sw_test_status_if] SW test transitioned to SwTestStatusInTest.
UVM_INFO @ 2903.121356 us: (sw_logger_if.sv:524) [pwrmgr_normal_sleep_all_wake_ups_sim_dv(sw/device/tests/pwrmgr_normal_sleep_all_wake_ups.c:59)] POR reset
UVM_INFO @ 2904.051356 us: (sw_logger_if.sv:524) [pwrmgr_normal_sleep_all_wake_ups_sim_dv(sw/device/tests/pwrmgr_normal_sleep_all_wake_ups.c:67)] Test 0 begin
UVM_INFO @ 2933.511356 us: (sw_logger_if.sv:524) [pwrmgr_normal_sleep_all_wake_ups_sim_dv(sw/device/tests/sim_dv/pwrmgr_sleep_all_wake_ups_impl.c:226)] Issue WFI to enter sleep 0
UVM_INFO @ 3174.361356 us: (sw_logger_if.sv:524) [pwrmgr_normal_sleep_all_wake_ups_sim_dv(sw/device/tests/pwrmgr_normal_sleep_all_wake_ups.c:70)] Woke up by source 0
UVM_INFO @ 3203.861356 us: (sw_logger_if.sv:524) [pwrmgr_normal_sleep_all_wake_ups_sim_dv(sw/device/tests/pwrmgr_normal_sleep_all_wake_ups.c:72)] clean up done source 0
UVM_INFO @ 3204.551356 us: (sw_logger_if.sv:524) [pwrmgr_normal_sleep_all_wake_ups_sim_dv(sw/device/tests/pwrmgr_normal_sleep_all_wake_ups.c:67)] Test 1 begin
UVM_INFO @ 3263.511356 us: (sw_logger_if.sv:524) [pwrmgr_normal_sleep_all_wake_ups_sim_dv(sw/device/tests/sim_dv/pwrmgr_sleep_all_wake_ups_impl.c:226)] Issue WFI to enter sleep 1
UVM_ERROR @ 6357.611356 us: (sw_logger_if.sv:526) [pwrmgr_normal_sleep_all_wake_ups_sim_dv(sw/device/tests/sim_dv/pwrmgr_sleep_all_wake_ups_impl.c:250)] CHECK-fail: Expected bits 5 and 8 set in filter status, got status 0x100
UVM_INFO @ 6357.611356 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
```

From `sw/device/tests/sim_dv/pwrmgr_sleep_all_wake_ups_impl.c`:, last quoted line:
```c
    case PWRMGR_PARAM_ADC_CTRL_AON_WKUP_REQ_IDX: {
      uint32_t filter_status = 0;
      CHECK_DIF_OK(dif_adc_ctrl_get_filter_status(&adc_ctrl, &filter_status));
      CHECK(filter_status ==
                ((1 << kDifAdcCtrlFilter5) | (1 << kDifAdcCtrlTrans)),
            "Expected bits %d and %d set in filter status, got status 0x%x",
            kDifAdcCtrlFilter5, kDifAdcCtrlTrans, filter_status);
```

### Steps to Reproduce

- GitHub Revision: c4666f429474acc507064e5448fa4d347fe5e611
- dvsim invocation command to reproduce the failure: `./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_pwrmgr_normal_sleep_all_wake_ups --build-seed 85829748320245376283659198434338498577935164172956485671224275001047693479661 --fixed-seed 41776559245041544122491462787668555008901039128546595375705424509999547060428`

It is easy to find other failing seeds of the same test, as it has a fairly high failure rate.

### Tests with similar or related failures

_No response_

### PR DESCRIPTION
**Pull request by pamaury**
See #23303 for explanation. In short, the ADC `FILTER_STATUS` register may a take a while to update after wake up due to the hardware writes going through the CDC. This PR fixes this issues by adding a new DIF method to wait long enough for any CDC update to finish and then uses this method in the problematic tests.

Fixes #23303

### CODE REVIEW

File: sw/device/lib/dif/dif_adc_ctrl.c [hunk 1]
```diff
@@ -513,3 +515,12 @@ dif_result_t dif_adc_ctrl_irq_cause_get_enabled(const dif_adc_ctrl_t *adc_ctrl,
 
   return kDifOk;
 }
+
+dif_result_t dif_adc_ctrl_wait_cdc_sync(const dif_adc_ctrl_t *adc_ctrl) {
+  if (adc_ctrl == NULL) {
+    return kDifBadArg;
+  }
+  // Wait 5 AON ticks.
+  busy_spin_micros(3 * 1000000 / (uint32_t)kClockFreqAonHz);
```
Comment (rswarbrick) [inline sw/device/lib/dif/dif_adc_ctrl.c:524]: This might be a stupid question, but I think this is "(3 * 1e6 / frequency_in_hz) microseconds". Won't that wait 3 cycles, rather than 5?

Comment (pamaury) [reply sw/device/lib/dif/dif_adc_ctrl.c:524]: Ah oops, this indeed should be a 5 not a 3. I am actually not entirely sure about which value to use, I based it off a comment in the ROM which says that it takes up to 4 AON cycles to synchronize.

**Review by vogelpi — APPROVED** [review]
Thanks for taking care of this @pamaury . The change looks good to me.

**Comment by pamaury** [comment]
There is a stupid issue: by using `kClockFreqAonHz`, I have now introduced a dependency on `arch.h` from the DIF which breaks the unittest because this library is device/silicon specific. The options that I can see are:
- modify `dif_adc_ctrl_wait_cdc_sync` to take the aon freq as a parameter, or
- modify `dif_adc_ctrl_config_t` to take add a field containing the aon frequency.

Any thoughts?

**Comment by vogelpi** [comment]
> There is a stupid issue: by using `kClockFreqAonHz`, I have now introduced a dependency on `arch.h` from the DIF which breaks the unittest because this library is device/silicon specific. The options that I can see are:
> 
>     * modify `dif_adc_ctrl_wait_cdc_sync` to take the aon freq as a parameter, or
> 
>     * modify `dif_adc_ctrl_config_t` to take add a field containing the aon frequency.
> 
> 
> Any thoughts?

I think providing the aon freq as function argument would be perfectly fine. It can be argued that this makes the function more generic (different implementation may clock the slower domain on a different clock).

**Comment by a-will** [comment]
> > There is a stupid issue: by using `kClockFreqAonHz`, I have now introduced a dependency on `arch.h` from the DIF which breaks the unittest because this library is device/silicon specific. The options that I can see are:
> > ```
> > * modify `dif_adc_ctrl_wait_cdc_sync` to take the aon freq as a parameter, or
> > 
> > * modify `dif_adc_ctrl_config_t` to take add a field containing the aon frequency.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Any thoughts?
> 
> I think providing the aon freq as function argument would be perfectly fine. It can be argued that this makes the function more generic (different implementation may clock the slower domain on a different clock).

Later, if you do the top device info lookup in the DIF libraries instead of the main binary, then you get the other option (multi-top topic).
