### PR TITLE
[sw/host/opentitanlib] Add SFDP signature check

### LINKED ISSUE #13477: opentitantool panics when bootstrapping cw310: 'attempt to add with overflow'
At commit d8af32ff61026d72a7586c66870feaa162335654, I'm seeing a opentitantool panic with 'attempt to add with overflow' in [sfdp.rs:449](https://cs.opensource.google/opentitan/opentitan/+/d8af32ff61026d72a7586c66870feaa162335654:sw/host/opentitanlib/src/spiflash/sfdp.rs;l=449).

@cfrantz Based on nothing but the stack trace and git blame, could this have something to do with cfc6ac6b090fde10caaac52fae1acdba76abce22 or f5ba7fd0dfe9f0bb25463f8e4d6243912b8fa019? They both touched the impl of [UpdateProtocol::update() for Eeprom](https://cs.opensource.google/opentitan/opentitan/+/d8af32ff61026d72a7586c66870feaa162335654:sw/host/opentitanlib/src/bootstrap/eeprom.rs;l=47-52).

```
$ ./bazelisk.sh test --cache_test_results=no --test_tag_filters=cw310  --test_output=streamed //sw/device/tests:uart_smoketest
[...]
Invoking: sw/host/opentitantool/opentitantool --rcfile= --logging=info --interface=cw310 --conf=sw/host/opentitantool/config/opentitan_cw310.json --exec=load-bitstream --rom-kind=testrom external/bitstreams/cache/dd97ef8a84a055a0f0b4d730cdf61bcb6535020e/lowrisc_systems_chip_earlgrey_cw310_0.1.bit.orig --exec=bootstrap sw/device/tests/uart_smoketest_prog_fpga_cw310.test_key_0.signed.bin console --exit-failure=(FAIL|FAULT).*\n --exit-success=PASS.*\n --timeout=3600s
[2022-06-30T17:29:17Z INFO  opentitantool::command::load_bitstream] Loading bitstream: "external/bitstreams/cache/dd97ef8a84a055a0f0b4d730cdf61bcb6535020e/lowrisc_systems_chip_earlgrey_cw310_0.1.bit.orig"
[2022-06-30T17:29:17Z INFO  opentitanlib::util::rom_detect] Bitstream file USR_ACCESS value: 0xf32cd682
[2022-06-30T17:29:19Z INFO  opentitanlib::util::rom_detect] Did not detect the ROM identification message.
[2022-06-30T17:29:19Z INFO  opentitanlib::transport::cw310] Programming the FPGA bitstream.
[2022-06-30T17:29:35Z INFO  opentitantool] Command result: success.
[2022-06-30T17:29:35Z INFO  opentitanlib::bootstrap] Asserting bootstrap pins...
[2022-06-30T17:29:35Z INFO  opentitanlib::app] Asserting the reset signal
[2022-06-30T17:29:36Z INFO  opentitanlib::app] Clearing the UART RX buffer
[2022-06-30T17:29:36Z INFO  opentitanlib::app] Deasserting the reset signal
[2022-06-30T17:29:36Z INFO  opentitanlib::bootstrap] Performing bootstrap...
thread 'main' panicked at 'attempt to add with overflow', sw/host/opentitanlib/src/spiflash/sfdp.rs:449:25
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:143:14
   2: core::panicking::panic
             at /rustc/7737e0b5c4103216d6fd8cf941b7ab9bdbaace7c/library/core/src/panicking.rs:48:5
   3: <opentitanlib::spiflash::sfdp::Sfdp as core::convert::TryFrom<&[u8]>>::try_from
   4: opentitanlib::spiflash::flash::SpiFlash::read_sfdp
   5: opentitanlib::spiflash::flash::SpiFlash::from_spi
   6: <opentitanlib::bootstrap::eeprom::Eeprom as opentitanlib::bootstrap::UpdateProtocol>::update
   7: opentitanlib::bootstrap::Bootstrap::do_update
   8: opentitanlib::bootstrap::Bootstrap::update_with_progress
   9: <opentitantool::command::bootstrap::BootstrapCommand as opentitanlib::app::command::CommandDispatch>::run
  10: opentitantool::_::<impl opentitanlib::app::command::CommandDispatch for opentitantool::RootCommandHierarchy>::run
  11: opentitantool::execute
  12: opentitantool::main
  13: core::ops::function::FnOnce::call_once
```

### PR DESCRIPTION
**Pull request by dmcardle**
My CW310 FPGA is producing 256 0xff bytes for the SFDP buffer instead of
something valid. As a result, we're parsing a signature of 0xffffffff
instead of the expected 0x50444653.

This commit changes Sfdp::try_from() to fail fast with an informative
error message about the invalid header, rather than blunder on and fail
farther down the line with "attempt to add with overflow".

Fixes #13477 

Signed-off-by: Dan McArdle <dmcardle@google.com>

### CODE REVIEW

File: sw/host/opentitanlib/src/spiflash/sfdp.rs [hunk 1]
```diff
@@ -502,4 +510,18 @@ mod test {
         assert_eq!(sfdp.jedec.density, 128 * 1024 * 1024);
         Ok(())
     }
+
+    // Regression test for https://github.com/lowRISC/opentitan/issues/13477
```
Comment (alphan) [inline sw/host/opentitanlib/src/spiflash/sfdp.rs:514]: nit: If you want you can  use one of the following shorthand(s) in the future: `#13477` or `lowRISC/opentitan#13477`

File: sw/host/opentitanlib/src/spiflash/sfdp.rs [hunk 2]
```diff
@@ -502,4 +510,18 @@ mod test {
...
+    #[test]
+    fn test_bad_header_signature() -> Result<()> {
+        let buf: &[u8] = &[255u8; 256];
```
Comment (alphan) [inline sw/host/opentitanlib/src/spiflash/sfdp.rs:517]:
```suggestion
        let buf = &[255u8; 256];
```

File: sw/host/opentitanlib/src/spiflash/sfdp.rs [hunk 3]
```diff
@@ -18,6 +18,8 @@ pub enum Error {
     TryFromIntError(#[from] std::num::TryFromIntError),
     #[error("the range {0}..{1} is out of bounds")]
     SliceRange(usize, usize),
+    #[error("SFDP header contains incorrect signature: {0:x}")]
```
Comment (alphan) [inline sw/host/opentitanlib/src/spiflash/sfdp.rs:21]:
```suggestion
    #[error("SFDP header contains incorrect signature: {0:#010x}")]
```

File: sw/host/opentitanlib/src/spiflash/sfdp.rs [hunk 4]
```diff
@@ -502,4 +510,18 @@ mod test {
...
+    // Regression test for https://github.com/lowRISC/opentitan/issues/13477
+    #[test]
+    fn test_bad_header_signature() -> Result<()> {
+        let buf: &[u8] = &[255u8; 256];
+        let sfdp = Sfdp::try_from(buf);
+        assert!(sfdp.is_err());
+        let err = sfdp.unwrap_err();
+        assert_eq!(
+            err.to_string(),
+            "SFDP header contains incorrect signature: ffffffff"
```
Comment (alphan) [inline sw/host/opentitanlib/src/spiflash/sfdp.rs:523]:
```suggestion
            "SFDP header contains incorrect signature: 0xffffffff"
```

File: sw/host/opentitanlib/src/spiflash/sfdp.rs [hunk 5]
```diff
@@ -38,14 +40,20 @@ pub struct SfdpHeader {
...
             minor: reader.read_u8()?,
             major: reader.read_u8()?,
             nph: reader.read_u8()?,
             reserved: reader.read_u8()?,
-        })
+        };
+        if header.signature != SFDP_HEADER_SIGNATURE {
+            return Result::Err(Error::WrongHeaderSignature(header.signature));
+        }
+        Ok(header)
```
Comment (alphan) [inline sw/host/opentitanlib/src/spiflash/sfdp.rs:56]:
```suggestion
    match header.signature {
        SFDP_HEADER_SIGNATURE => Ok(header),
        v => Err(WrongHeaderSignature(v)),
    }
```

**Review by alphan — APPROVED** [review]
Thanks @dmcardle, just a few nits.

File: sw/host/opentitanlib/src/spiflash/sfdp.rs (hunk 1 above)
Comment (dmcardle) [reply sw/host/opentitanlib/src/spiflash/sfdp.rs:514]: Noted! The downside of that shorter notation is it's no longer a URL. Chrome has a custom link shortener for bugs, so you can link to `crbug.com/1234`. Maybe we should think about setting up something like that.

File: sw/host/opentitanlib/src/spiflash/sfdp.rs (hunk 5 above)
Comment (dmcardle) [reply sw/host/opentitanlib/src/spiflash/sfdp.rs:56]: Ah! C++ has rotted my brain :P

File: sw/host/opentitanlib/src/spiflash/sfdp.rs (hunk 2 above)
Comment (dmcardle) [reply sw/host/opentitanlib/src/spiflash/sfdp.rs:517]: I actually did this to coerce `buf` into being a `&[u8]` instead of `&[u8; 256]`, so it would match the `impl TryFrom<&[u8]> for Sfdp`.

I don't particularly care either way, I'll just take your suggestion.

File: sw/host/opentitanlib/src/spiflash/sfdp.rs (hunk 1 above)
Comment (dmcardle) [reply sw/host/opentitanlib/src/spiflash/sfdp.rs:514]: If you don't mind, I'll leave this as URL for ease of clicking. Especially since it fits on one line.

**Comment by dmcardle** [comment]
OK, that round of review should be done. Merge at your convenience!

**Comment by dmcardle** [comment]
(Really done now. The last push just updated the commit message to include `Fixes #13477` like the PR description does.)

File: sw/host/opentitanlib/src/spiflash/sfdp.rs (hunk 2 above)
Comment (alphan) [reply sw/host/opentitanlib/src/spiflash/sfdp.rs]: Oh, I see, makes sense. Sorry for missing that :)

File: sw/host/opentitanlib/src/spiflash/sfdp.rs (hunk 5 above)
Comment (alphan) [reply sw/host/opentitanlib/src/spiflash/sfdp.rs]: Haha, suffering from the same ailment :)

**Comment by tjaychen** [comment]
sorry just to chime in a bit, is the SFDP failure by any chance a bug with the `spi_device` that only manifests in fpgas..?
or have you guys tracked it down to something else already?

**Comment by dmcardle** [comment]
Haven't tracked it down yet, but I left issue #13477 open for that purpose!

**Comment by alphan** [comment]
> sorry just to chime in a bit, is the SFDP failure by any chance a bug with the `spi_device` that only manifests in fpgas..?
> or have you guys tracked it down to something else already? 

I wouldn't expect this to be a widespread issue since we are using the same protocol everywhere to catch issues like this as early as possible. CI seems to be OK.
