### PR TITLE
[sysrst_ctrl] Fix sysrst_ctrl_in_irq test

### LINKED ISSUE #16633: [test-triage] chip_sw_sysrst_ctrl_in_irq
### Hierarchy of regression failure

Block level

### Failure Description

```
UVM_FATAL @ * us: (chip_sw_sysrst_ctrl_in_irq_vseq.sv:55) [chip_sw_sysrst_ctrl_in_irq_vseq] wait timeout occurred! has 3 failures:

Test chip_sw_sysrst_ctrl_in_irq has 3 failures.
0.chip_sw_sysrst_ctrl_in_irq.2779851072
Line 532, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/0.chip_sw_sysrst_ctrl_in_irq/latest/run.log

  UVM_FATAL @ 13880.838008 us: (chip_sw_sysrst_ctrl_in_irq_vseq.sv:55) [uvm_test_top.env.virtual_sequencer.chip_sw_sysrst_ctrl_in_irq_vseq] wait timeout occurred!
  UVM_INFO @ 13880.838008 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
  
  
1.chip_sw_sysrst_ctrl_in_irq.1319353672
Line 529, in log /container/opentitan-public/scratch/os_regression/chip_earlgrey_asic-sim-vcs/1.chip_sw_sysrst_ctrl_in_irq/latest/run.log

  UVM_FATAL @ 12996.821730 us: (chip_sw_sysrst_ctrl_in_irq_vseq.sv:55) [uvm_test_top.env.virtual_sequencer.chip_sw_sysrst_ctrl_in_irq_vseq] wait timeout occurred!
  UVM_INFO @ 12996.821730 us: (uvm_report_catcher.svh:705) [UVM/REPORT/CATCHER]
  --- UVM Report catcher Summary ---
```

### Steps to Reproduce

- GitHub Revision: https://github.com/lowrisc/opentitan/tree/553cdde7227cc9d1f0ab6caa6285cdcdd3c678ac
- dvsim invocation command to reproduce the failure, inclusive of build and run seeds:
  ./util/dvsim/dvsim.py hw/top_earlgrey/dv/chip_sim_cfg.hjson -i chip_sw_sysrst_ctrl_in_irq --build-seed 1443698744 --fixed-seed 2779851072 --waves fsdb
- Kokoro build number if applicable

### Tests with similar or related failures

- [ ] chip_sw_sysrst_ctrl_in_irq

### PR DESCRIPTION
**Pull request by abdullahvarici**
The changes in PR #16584 broke sysrst_ctrl_in_irq test. Update sysrst_ctrl_input indexes to fix that.

Fixes #16633.

Signed-off-by: Abdullah Varici <abdullah.varici@lowrisc.org>

### CODE REVIEW

**Comment by weicaiyang** [comment]
> sysrst_ctrl dif unit tests in CI are failing. Do you have any idea why, @engdoreis?

a DIF update may require to update DIF unit test as well. @timothytrippel may be able to quickly fix it

**Comment by timothytrippel** [comment]
yes, @weicaiyang is correct, you will need to update the sysrst_ctrl DIF unit tests to pass CI. lmk if you need help, I can create a PR to replicate this change + the unit test change to show what needs to be updated

**Comment by abdullahvarici** [comment]
Thanks @timothytrippel. No idea how to do that, if you can show me, I would be appreciated.

**Comment by timothytrippel** [comment]
No problem. I created a branch here with the fix: https://github.com/timothytrippel/opentitan/commit/36ce47179cb3322b1c6bf1d7cfdbc4477f3b97b3

**Review by msfschaffner — APPROVED** [review]
Good catch, thanks for fixing it. 

LGTM, modulo the DIF unit test.

**Comment by abdullahvarici** [comment]
Thanks for helping. I've updated DIF too. Hopefully it will pass CI now.

File: sw/device/tests/sim_dv/sysrst_ctrl_in_irq_test.c [hunk 1]
```diff
@@ -76,11 +76,7 @@ void sysrst_ctrl_input_change_detect(
...
   // Configure for input change.
   dif_sysrst_ctrl_input_change_t input_change;
-  if (expected_key_intr_src >= kDifSysrstCtrlKeyIntrStatusInputPowerButtonL2H) {
-    input_change = (dif_sysrst_ctrl_input_change_t)expected_key_intr_src << 1;
-  } else {
-    input_change = (dif_sysrst_ctrl_input_change_t)expected_key_intr_src;
-  }
+  input_change = (dif_sysrst_ctrl_input_change_t)expected_key_intr_src;
   dif_sysrst_ctrl_input_change_config_t config = {
       .input_changes = input_change,
```
Comment (engdoreis) [inline sw/device/tests/sim_dv/sysrst_ctrl_in_irq_test.c:81]: Nit. I would just remove the line above and do as below.
```suggestion
      .input_changes = (dif_sysrst_ctrl_input_change_t)expected_key_intr_src,
```

**Review by engdoreis — APPROVED** [review]
Thanks @abdullahvarici for the Fix. I just a minor comment, otherwise LGTM.

File: sw/device/tests/sim_dv/sysrst_ctrl_in_irq_test.c (hunk 1 above)
Comment (abdullahvarici) [reply sw/device/tests/sim_dv/sysrst_ctrl_in_irq_test.c]: Thanks! Updated.
